import dynamic from 'next/dynamic'
import type { ComponentType } from 'react'

type UniqueActivityComponent = ComponentType<{ onComplete?: () => void }>

const REGISTRY: Record<string, () => Promise<{ default: UniqueActivityComponent }>> = {
  OrderChallengeL14: () => import('./OrderChallengeL14'),
  SpellingChallengeL11: () => import('./SpellingChallengeL11'),
  ConversationBuilderL12: () => import('./ConversationBuilderL12'),
  NumberDictationL13: () => import('./NumberDictationL13'),
  DirectionRaceL15: () => import('./DirectionRaceL15'),
  PictureMatchL16: () => import('./PictureMatchL16'),
  MenuBuilderL17: () => import('./MenuBuilderL17'),
  ScheduleBuilderL18: () => import('./ScheduleBuilderL18'),
  SymptomCheckerL21: () => import('./SymptomCheckerL21'),
  WeatherForecastL22: () => import('./WeatherForecastL22'),
  PlanBuilderL23: () => import('./PlanBuilderL23'),
  HotelCheckinL24: () => import('./HotelCheckinL24'),
  BoardingPassL25: () => import('./BoardingPassL25'),
  OutfitBuilderL26: () => import('./OutfitBuilderL26'),
  WhoIsItL27: () => import('./WhoIsItL27'),
  JobInterviewL28: () => import('./JobInterviewL28'),
  StoryBuilderL31: () => import('./StoryBuilderL31'),
  RoomDesignerL32: () => import('./RoomDesignerL32'),
  AppNavigatorL33: () => import('./AppNavigatorL33'),
  RecipeBuilderL34: () => import('./RecipeBuilderL34'),
  HobbyMatchL35: () => import('./HobbyMatchL35'),
  EcoQuizL36: () => import('./EcoQuizL36'),
  FestivalMatchL37: () => import('./FestivalMatchL37'),
  PostcardWriterL38: () => import('./PostcardWriterL38'),
  MemoryLaneL41: () => import('./MemoryLaneL41'),
  SubjunctiveDetectorL42: () => import('./SubjunctiveDetectorL42'),
  RegisterSwitchL43: () => import('./RegisterSwitchL43'),
  HeadlineReaderL44: () => import('./HeadlineReaderL44'),
  WellnessCoachL45: () => import('./WellnessCoachL45'),
  BankTellerL46: () => import('./BankTellerL46'),
  CriticCornerL47: () => import('./CriticCornerL47'),
  DreamBoardL48: () => import('./DreamBoardL48'),
  TimelineWeaverL51: () => import('./TimelineWeaverL51'),
  ParallelWorldL52: () => import('./ParallelWorldL52'),
  NewsroomEditorL53: () => import('./NewsroomEditorL53'),
  DebateArenaL54: () => import('./DebateArenaL54'),
  InboxManagerL55: () => import('./InboxManagerL55'),
  IdiomDetectiveL56: () => import('./IdiomDetectiveL56'),
  LectureSummarizerL57: () => import('./LectureSummarizerL57'),
  ToneTunerL58: () => import('./ToneTunerL58'),
  ClauseArchitectL61: () => import('./ClauseArchitectL61'),
  PoetryForgeL62: () => import('./PoetryForgeL62'),
  LegalNavigatorL63: () => import('./LegalNavigatorL63'),
  SlangEvolutionL64: () => import('./SlangEvolutionL64'),
  TranslatorBoothL65: () => import('./TranslatorBoothL65'),
  PhilosophyCircleL66: () => import('./PhilosophyCircleL66'),
  LanguageTimelineL67: () => import('./LanguageTimelineL67'),
  SpeechCrafterL68: () => import('./SpeechCrafterL68'),
  DialectDecoderL71: () => import('./DialectDecoderL71'),
  PunMasterL72: () => import('./PunMasterL72'),
  BiasDetectorL73: () => import('./BiasDetectorL73'),
  LabReportL74: () => import('./LabReportL74'),
  EmotionMapperL75: () => import('./EmotionMapperL75'),
  PeaceTableL76: () => import('./PeaceTableL76'),
  StoryWeaverL77: () => import('./StoryWeaverL77'),
  IdentityMosaicL78: () => import('./IdentityMosaicL78'),
  TriageSimulatorL81: () => import('./TriageSimulatorL81'),
  MarketAnalystL82: () => import('./MarketAnalystL82'),
  TechSpecL83: () => import('./TechSpecL83'),
  ChefChallengeL84: () => import('./ChefChallengeL84'),
  LiveCommentaryL85: () => import('./LiveCommentaryL85'),
  RhythmDecoderL86: () => import('./RhythmDecoderL86'),
  CabinetDebateL87: () => import('./CabinetDebateL87'),
  LessonPlannerL88: () => import('./LessonPlannerL88'),
  BlueprintReaderL91: () => import('./BlueprintReaderL91'),
  StyleCuratorL92: () => import('./StyleCuratorL92'),
  HarvestPlannerL93: () => import('./HarvestPlannerL93'),
  ConciergeDeskL94: () => import('./ConciergeDeskL94'),
  SourceVerifierL95: () => import('./SourceVerifierL95'),
  CampaignBuilderL96: () => import('./CampaignBuilderL96'),
  RitualGuideL97: () => import('./RitualGuideL97'),
  PitchPerfectL98: () => import('./PitchPerfectL98'),
  ConversationMasterL101: () => import('./ConversationMasterL101'),
  FinalShowcaseL102: () => import('./FinalShowcaseL102'),
}

export function getUniqueActivity(id: string) {
  const loader = REGISTRY[id]
  if (!loader) return null
  return dynamic(loader, { ssr: false })
}
