import type { LessonData } from '@/lib/types/lesson'

// The Spanish alphabet — each letter is a "phrase" in the engine format
// spanish = the letter, english = name + hint, pronunciation = phonetic
const PHRASES = [
  // Vowels
  { spanish: 'A', english: 'a — "ah" as in father', pronunciation: 'AH', category: 'vowels', audio: 'a' },
  { spanish: 'E', english: 'e — "eh" as in met', pronunciation: 'EH', category: 'vowels', audio: 'e' },
  { spanish: 'I', english: 'i — "ee" as in see', pronunciation: 'EE', category: 'vowels', audio: 'i' },
  { spanish: 'O', english: 'o — "oh" as in hope', pronunciation: 'OH', category: 'vowels', audio: 'o' },
  { spanish: 'U', english: 'u — "oo" as in food', pronunciation: 'OO', category: 'vowels', audio: 'u' },
  // Standard Consonants
  { spanish: 'B', english: 'be — like English "b"', pronunciation: 'BEH', category: 'consonants', audio: 'b' },
  { spanish: 'C', english: 'ce — "s" before e/i, "k" otherwise', pronunciation: 'SEH', category: 'consonants', audio: 'c' },
  { spanish: 'D', english: 'de — softer than English "d"', pronunciation: 'DEH', category: 'consonants', audio: 'd' },
  { spanish: 'F', english: 'efe — like English "f"', pronunciation: 'EH-feh', category: 'consonants', audio: 'f' },
  { spanish: 'G', english: 'ge — soft before e/i, hard otherwise', pronunciation: 'HEH', category: 'consonants', audio: 'g' },
  { spanish: 'H', english: 'hache — always silent', pronunciation: 'AH-cheh', category: 'consonants', audio: 'h' },
  { spanish: 'J', english: 'jota — like English "h"', pronunciation: 'HOH-tah', category: 'consonants', audio: 'j' },
  { spanish: 'K', english: 'ka — like English "k"', pronunciation: 'KAH', category: 'consonants', audio: 'k' },
  { spanish: 'L', english: 'ele — like English "l"', pronunciation: 'EH-leh', category: 'consonants', audio: 'l' },
  { spanish: 'M', english: 'eme — like English "m"', pronunciation: 'EH-meh', category: 'consonants', audio: 'm' },
  { spanish: 'N', english: 'ene — like English "n"', pronunciation: 'EH-neh', category: 'consonants', audio: 'n' },
  { spanish: 'P', english: 'pe — like English "p"', pronunciation: 'PEH', category: 'consonants', audio: 'p' },
  { spanish: 'Q', english: 'cu — "k" sound (always with u)', pronunciation: 'KOO', category: 'consonants', audio: 'q' },
  { spanish: 'R', english: 'erre — rolled / trilled', pronunciation: 'EH-rreh', category: 'consonants', audio: 'r' },
  { spanish: 'S', english: 'ese — like English "s"', pronunciation: 'EH-seh', category: 'consonants', audio: 's' },
  { spanish: 'T', english: 'te — softer than English "t"', pronunciation: 'TEH', category: 'consonants', audio: 't' },
  { spanish: 'V', english: 'uve — sounds like "b"', pronunciation: 'OO-beh', category: 'consonants', audio: 'v' },
  { spanish: 'W', english: 'doble uve — rare in Spanish', pronunciation: 'DOH-bleh OO-beh', category: 'consonants', audio: 'w' },
  { spanish: 'X', english: 'equis — "ks" or "s"', pronunciation: 'EH-kees', category: 'consonants', audio: 'x' },
  { spanish: 'Y', english: 'ye — "y" as in yes', pronunciation: 'YEH', category: 'consonants', audio: 'y' },
  { spanish: 'Z', english: 'zeta — "s" in Latin America', pronunciation: 'SEH-tah', category: 'consonants', audio: 'z' },
  // Unique Spanish Letters & Digraphs
  { spanish: '\u00d1', english: 'e\u00f1e — "ny" as in canyon', pronunciation: 'EH-nyeh', category: 'unique', audio: 'enie' },
  { spanish: 'LL', english: 'elle — "y" as in yes (most countries)', pronunciation: 'EH-yeh', category: 'unique', audio: 'elle' },
  { spanish: 'RR', english: 'doble erre — full rolled/trilled R', pronunciation: 'EH-rreh', category: 'unique', audio: 'doble-erre' },
  { spanish: 'CH', english: 'che — "ch" as in church', pronunciation: 'CHEH', category: 'unique', audio: 'che' },
]

const phraseByAudio: Record<string, (typeof PHRASES)[number]> = {}
PHRASES.forEach((p) => { phraseByAudio[p.audio] = p })

export const L11Data: LessonData = {
  id: 'L1.1',
  hero: {
    lessonId: 'L1.1',
    title: 'Sounds & Letters',
    subtitle: 'The Spanish alphabet & pronunciation foundations',
    description: 'The Spanish alphabet has 27 letters, including the unique \u00f1. It is entirely phonetic \u2014 each letter has a consistent sound. Mastering pronunciation here builds the foundation for everything that follows.',
    image: '/images/L1.1/L1.1.jpg',
    gradient: 'from-blue-800/70 via-blue-700/60 to-purple-700/70',
    accentColor: 'amber-300',
  },
  sectionTransitions: [
    { afterSection: 'vowels', text: 'Great \u2014 you now know the 5 vowels! Unlike English, each one has only ONE sound. Let\'s move to consonants.' },
    { afterSection: 'consonants', text: 'You\'ve covered the standard consonants. Now let\'s discover letters that are unique to Spanish.' },
    { afterSection: 'unique', text: 'Now you know the full alphabet! Time to sharpen your pronunciation with key tips.' },
    { afterSection: 'pronunciation-tips', text: 'Nice work on the tips. Let\'s put your knowledge to the test with interactive practice.' },
    { afterSection: 'dialogues', text: 'You just heard real Spanish spelling in action. Let\'s explore some cultural facts about the alphabet.' },
    { afterSection: 'cultural', text: 'Time to put your spelling skills to the test!' },
    { afterSection: 'spelling-challenge', text: 'Final stretch \u2014 let\'s see how much you\'ve learned!' },
  ],
  personalizedVocab: [
    { spanish: 'A, E, I, O, U', english: 'The five vowels' },
    { spanish: '\u00d1', english: 'Unique Spanish letter' },
    { spanish: 'LL', english: 'Double L digraph' },
    { spanish: 'RR', english: 'Rolled R' },
    { spanish: 'H (silent)', english: 'Always silent in Spanish' },
    { spanish: 'J (jota)', english: 'Breathy H sound' },
  ],
  pronunciationChallenges: [
    { spanish: 'Hola, buenos d\u00edas', pronunciation: 'OH-lah BWEH-nohs DEE-ahs', english: 'Hello, good morning', audio: 'hola-buenos-dias', tip: 'Remember: H is ALWAYS silent! Start with the O sound.' },
    { spanish: 'Ni\u00f1o', pronunciation: 'NEE-nyoh', english: 'Child / Boy', audio: 'nino', tip: 'The \u00d1 sounds like "ny" in "canyon." This is NOT just an N!' },
    { spanish: 'Guitarra', pronunciation: 'gee-TAH-rah', english: 'Guitar', audio: 'guitarra', tip: 'The U after G before E/I is silent. GU + I = "gee" not "goo-ee."' },
    { spanish: 'Perro vs Pero', pronunciation: 'PEH-rroh vs PEH-roh', english: 'Dog vs But', audio: 'perro-vs-pero', tip: 'RR is a full trill, R is a quick tap. The difference changes the meaning!' },
    { spanish: 'Zapato', pronunciation: 'sah-PAH-toh', english: 'Shoe', audio: 'zapato', tip: 'In Latin America, Z = "s" sound. In Spain, Z = "th" sound. Both are correct!' },
    { spanish: 'Calle', pronunciation: 'KAH-yeh', english: 'Street', audio: 'calle', tip: 'LL sounds like "y" in most countries. In Argentina, it sounds like "sh."' },
  ],
  objectives: [
    { icon: '\uD83C\uDDE6', title: 'The 27 Letters', desc: 'Learn every letter of the Spanish alphabet and its name' },
    { icon: '\uD83D\uDD0A', title: 'Pronunciation Rules', desc: 'Master the consistent sounds each letter makes' },
    { icon: '\u2728', title: 'Unique Letters', desc: 'Discover \u00d1, LL, RR, CH \u2014 sounds that don\'t exist in English' },
    { icon: '\uD83C\uDFAF', title: 'Spell in Spanish', desc: 'Spell names and words using Spanish letter names' },
  ],
  sections: [
    { id: 'welcome', label: 'Welcome' },
    { id: 'objectives', label: 'What You\'ll Learn' },
    { id: 'personalized-context', label: 'See in YOUR Context' },
    { id: 'vowels', label: 'Spanish Vowels' },
    { id: 'consonants', label: 'Standard Consonants' },
    { id: 'unique', label: 'Unique Spanish Letters' },
    { id: 'pronunciation-tips', label: 'Pronunciation Tips' },
    { id: 'pronunciation-practice', label: 'Pronunciation Practice' },
    { id: 'flashcards', label: 'Flashcards' },
    { id: 'matching-game', label: 'Matching Game' },
    { id: 'letter-sorting', label: 'Letter Sorting' },
    { id: 'dialogues', label: 'Real-World Dialogues' },
    { id: 'cultural', label: 'The Alphabet in Action' },
    { id: 'spelling-challenge', label: 'Spelling Challenge' },
    { id: 'knowledge-check', label: 'Knowledge Check' },
  ],
  audioBase: '/audio/L1.1/letters',
  phraseSections: [
    {
      id: 'vowels',
      title: 'Spanish Vowels',
      description: 'Spanish has 5 vowels, each with ONE consistent sound \u2014 unlike English where vowels change. Click to hear each one.',
      tabs: [
        { label: 'All Vowels', color: 'blue', phrases: PHRASES.filter(p => p.category === 'vowels') },
      ],
    },
    {
      id: 'consonants',
      title: 'Standard Consonants',
      description: 'Most consonants are similar to English, but some have key differences. Pay special attention to H, J, V, and Z.',
      tabs: [
        { label: 'Similar to English', color: 'emerald', phrases: PHRASES.filter(p => p.category === 'consonants' && ['b', 'd', 'f', 'k', 'l', 'm', 'n', 'p', 's', 't'].includes(p.audio)) },
        { label: 'Sound Different', color: 'amber', phrases: PHRASES.filter(p => p.category === 'consonants' && ['c', 'g', 'h', 'j', 'q', 'r', 'v', 'w', 'x', 'y', 'z'].includes(p.audio)) },
      ],
    },
    {
      id: 'unique',
      title: 'Unique Spanish Letters',
      description: 'These letters or combinations don\'t exist in English \u2014 they\'re what make Spanish sound distinctly Spanish.',
      tabs: [
        { label: '\u00d1, LL, RR, CH', color: 'purple', phrases: PHRASES.filter(p => p.category === 'unique') },
      ],
    },
  ],
  pronunciationTips: [
    {
      title: 'The 5 Vowels: A, E, I, O, U',
      content: 'Spanish vowels are simple and consistent \u2014 each one always makes the same sound, unlike English. A = "ah" (amigo). E = "eh" (escuela). I = "ee" (isla). O = "oh" (ojo). U = "oo" (uva).',
      example: 'A = AH | E = EH | I = EE | O = OH | U = OO',
    },
    {
      title: 'Consonants That Sound Different from English',
      content: 'H is always silent ("Hola" = "oh-lah"). J is a strong breathy sound ("Jam\u00f3n" = "hah-MOHN"). \u00d1 is "ny" as in "canyon." R/RR: single R is a quick tap, double RR is a full trill. LL is "y" in most countries. Z is "s" in Latin America, "th" in Spain. V sounds almost like B.',
      example: 'H silent: Hola = OH-lah | J breathy: Jota = HOH-tah | V = B: Vaca \u2248 Baca',
    },
    {
      title: 'Letters That Change Sound: C and G',
      content: 'C before A, O, U is hard "k": casa, coco. C before E, I is soft "s": cielo, cena. G before A, O, U is hard "g": gato. G before E, I is breathy "h": gente, gigante. Tip: when C or G see E or I, they "soften up."',
      example: 'Casa (KAH-sah) vs Cielo (see-EH-loh) | Gato (GAH-toh) vs Gente (HEN-teh)',
    },
    {
      title: 'Rare Letters: K, W, X',
      content: 'K (ka), W (doble uve), and X (equis) appear mostly in borrowed words. K: kilo, kayak. W: wifi, whisky. X has multiple sounds! In "M\u00e9xico" = "h" sound. In "examen" = "ks" sound. In Nahuatl words like "Xochimilco" = "sh" sound.',
      example: 'M\u00e9xico = MEH-hee-koh | Examen = ek-SAH-men | Xochimilco = soh-chee-MEEL-koh',
    },
  ],
  flashcardGroups: [
    { key: 'vowels', label: 'Vowels', audioKeys: ['a', 'e', 'i', 'o', 'u'] },
    { key: 'tricky-consonants', label: 'Tricky Consonants', audioKeys: ['c', 'g', 'h', 'j', 'q', 'r', 'v', 'z'] },
    { key: 'unique', label: 'Unique Letters', audioKeys: ['enie', 'elle', 'doble-erre', 'che'] },
  ],
  matchPairs: [
    { left: '\u00d1', right: 'e\u00f1e' },
    { left: 'H', right: 'hache (silent)' },
    { left: 'J', right: 'jota' },
    { left: 'G', right: 'ge' },
    { left: 'Q', right: 'cu' },
    { left: 'Z', right: 'zeta' },
    { left: 'LL', right: 'elle' },
    { left: 'RR', right: 'doble erre' },
  ],
  matchLabels: { left: 'Letter', right: 'Name / Sound' },
  sortActivities: [
    {
      title: 'Vowels vs. Consonants',
      instruction: 'Drag each letter to the correct category.',
      buckets: ['Vowels', 'Consonants'],
      items: [
        { text: 'A', bucket: 'Vowels' }, { text: 'E', bucket: 'Vowels' },
        { text: 'I', bucket: 'Vowels' }, { text: 'O', bucket: 'Vowels' },
        { text: 'U', bucket: 'Vowels' }, { text: 'B', bucket: 'Consonants' },
        { text: 'F', bucket: 'Consonants' }, { text: 'J', bucket: 'Consonants' },
        { text: '\u00d1', bucket: 'Consonants' }, { text: 'R', bucket: 'Consonants' },
      ],
    },
    {
      title: 'Similar to English vs. Sounds Different',
      instruction: 'Sort each letter based on whether it sounds similar to English or different in Spanish.',
      buckets: ['Similar to English', 'Sounds Different'],
      items: [
        { text: 'B', bucket: 'Similar to English' }, { text: 'D', bucket: 'Similar to English' },
        { text: 'F', bucket: 'Similar to English' }, { text: 'K', bucket: 'Similar to English' },
        { text: 'M', bucket: 'Similar to English' }, { text: 'C', bucket: 'Sounds Different' },
        { text: 'G', bucket: 'Sounds Different' }, { text: 'H', bucket: 'Sounds Different' },
        { text: 'J', bucket: 'Sounds Different' }, { text: '\u00d1', bucket: 'Sounds Different' },
      ],
    },
    {
      title: 'True or False?',
      instruction: 'Sort each statement as True or False.',
      buckets: ['True', 'False'],
      items: [
        { text: 'The letter H is always silent in Spanish', bucket: 'True' },
        { text: 'B and V sound almost identical in Spanish', bucket: 'True' },
        { text: '\u00d1 is a letter that does not exist in English', bucket: 'True' },
        { text: 'Spanish has 27 letters in its alphabet', bucket: 'True' },
        { text: 'The letter J sounds like a strong English H', bucket: 'True' },
        { text: 'Spanish has 26 letters, same as English', bucket: 'False' },
        { text: 'The letter H is pronounced like English H', bucket: 'False' },
        { text: 'Z always sounds like "z" in "zoo" in Spanish', bucket: 'False' },
        { text: '\u00d1 is just an N with a decoration \u2014 same sound', bucket: 'False' },
        { text: 'Q is always followed by the letter A in Spanish', bucket: 'False' },
      ],
    },
  ],
  sortSectionId: 'letter-sorting',
  sortTitle: 'Letter Sorting',
  dialogues: [
    {
      id: 'dialogue-airport',
      title: 'Spelling Your Name \u2014 At the Airport',
      location: 'Airport',
      lines: [
        { speaker: 'Agent', text: 'Hola, buenos d\u00edas. \u00bfC\u00f3mo se escribe su nombre?', audio: '/audio/L1.1/dialogue_0_0.mp3' },
        { speaker: 'Anna', text: 'Me llamo Anna. Se escribe: a, ene, ene, a.', audio: '/audio/L1.1/dialogue_0_1.mp3' },
        { speaker: 'Agent', text: 'Gracias. \u00bfY su apellido?', audio: '/audio/L1.1/dialogue_0_2.mp3' },
        { speaker: 'Anna', text: 'Lee. Se escribe: ele, e, e.', audio: '/audio/L1.1/dialogue_0_3.mp3' },
        { speaker: 'Agent', text: '\u00bfPuede repetir? \u00bfEle, e, e?', audio: '/audio/L1.1/dialogue_0_4.mp3' },
        { speaker: 'Anna', text: 'S\u00ed, correcto. Ele, e, e. Lee.', audio: '/audio/L1.1/dialogue_0_5.mp3' },
      ],
    },
    {
      id: 'dialogue-classroom',
      title: 'Spelling Practice \u2014 In the Classroom',
      location: 'Classroom',
      lines: [
        { speaker: 'Teacher', text: '\u00bfC\u00f3mo se escribe guitarra?', audio: '/audio/L1.1/dialogue_1_0.mp3' },
        { speaker: 'Student', text: 'Se escribe: ge, u, i, te, a, erre, erre, a.', audio: '/audio/L1.1/dialogue_1_1.mp3' },
        { speaker: 'Teacher', text: 'Muy bien. \u00bfY hola?', audio: '/audio/L1.1/dialogue_1_2.mp3' },
        { speaker: 'Student', text: 'Hache, o, ele, a.', audio: '/audio/L1.1/dialogue_1_3.mp3' },
        { speaker: 'Teacher', text: 'Excelente. Ahora una dif\u00edcil: zapato.', audio: '/audio/L1.1/dialogue_1_4.mp3' },
        { speaker: 'Student', text: 'Zeta, a, pe, a, te, o.', audio: '/audio/L1.1/dialogue_1_5.mp3' },
        { speaker: 'Teacher', text: '\u00a1Perfecto! Ya conoces bien las letras.', audio: '/audio/L1.1/dialogue_1_6.mp3' },
      ],
    },
  ],
  dialogueDescription: 'Hear how Spanish speakers spell names and words using letter names \u2014 a skill you\'ll use every day.',
  culturalNotes: [
    {
      title: 'The \u00d1 \u2014 A Symbol of Identity',
      content: 'The letter \u00d1 is more than just a letter \u2014 it\'s a symbol of Hispanic identity. In 1991, Spain even passed a law requiring keyboards sold in Spain to include the \u00d1 key.',
    },
    {
      title: 'B and V \u2014 The Eternal Confusion',
      content: 'In most varieties of Spanish, B and V are pronounced nearly identically. To distinguish them while spelling, Spanish speakers use phrases like: "b de burro" (B as in donkey) and "v de vaca" (V as in cow).',
    },
    {
      title: 'Z and C \u2014 Regional Variations',
      content: 'In Latin America, Z sounds like "s" (zapato = "sah-PAH-toh"). In central and northern Spain, Z sounds like "th" in "think." This feature is called "distinci\u00f3n." Neither pronunciation is "more correct."',
    },
  ],
  culturalGradient: 'from-amber-50 to-orange-50',
  quiz: [
    { id: 1, type: 'mc', text: 'How many letters are in the Spanish alphabet?', options: ['26', '27', '28', '30'], answer: 1 },
    { id: 2, type: 'mc', text: 'Which letter is unique to the Spanish alphabet?', options: ['LL', '\u00d1', 'CH', 'RR'], answer: 1 },
    { id: 3, type: 'tf', text: 'The Spanish alphabet is entirely phonetic \u2014 words are pronounced as they are written.', answer: true },
    { id: 4, type: 'mc', text: 'How is "a" pronounced in Spanish?', options: ['Like "a" in "cat"', 'Like "a" in "father"', 'Like "a" in "cake"', 'Like "a" in "about"'], answer: 1 },
    { id: 5, type: 'mc', text: 'Which of these is a Spanish vowel?', options: ['\u00d1', 'LL', 'U', 'R'], answer: 2 },
    { id: 6, type: 'tf', text: 'The letter "h" is always silent in Spanish.', answer: true },
    { id: 7, type: 'mc', text: 'How is "\u00f1" pronounced?', options: ['Like "n" in "no"', 'Like "ny" in "canyon"', 'Like "gn" in "sign"', 'Like "nn" in "inner"'], answer: 1 },
    { id: 8, type: 'fill', text: 'The Spanish word for "child" is ni_o. Fill in the missing letter.', answer: '\u00f1' },
    { id: 9, type: 'mc', text: 'The letter "c" before "e" or "i" sounds like:', options: ['"k"', '"s"', '"ch"', '"th"'], answer: 1 },
    { id: 10, type: 'tf', text: 'The letter "r" in Spanish is rolled or trilled.', answer: true },
    { id: 11, type: 'mc', text: '"LL" is pronounced similar to:', options: ['"l" in "love"', '"y" in "yes"', '"j" in "jar"', '"ll" in "llama" (English)'], answer: 1 },
    { id: 12, type: 'fill', text: 'The Spanish word for "rain" is __uvia. Fill in the missing letters.', answer: 'll' },
    { id: 13, type: 'mc', text: 'Which word contains a silent letter?', options: ['Casa', 'Hola', 'Perro', 'Gato'], answer: 1 },
    { id: 14, type: 'mc', text: '"G" before "e" or "i" sounds:', options: ['Hard like "go"', 'Soft, similar to "h"', 'Like "j" in English', 'Silent'], answer: 1 },
    { id: 15, type: 'tf', text: 'Each Spanish vowel has only one consistent sound.', answer: true },
  ],
  uniqueActivity: {
    id: 'SpellingChallengeL11',
    sectionId: 'spelling-challenge',
    sectionColor: 'bg-blue-50/40',
    sectionBorder: 'border-blue-100',
  },
  sectionColors: {
    'objectives': { bg: 'bg-white', border: '' },
    'personalized-context': { bg: 'bg-violet-50/30', border: 'border-violet-100' },
    'vowels': { bg: 'bg-blue-50/40', border: 'border-blue-100' },
    'consonants': { bg: 'bg-purple-50/40', border: 'border-purple-100' },
    'unique': { bg: 'bg-indigo-50/40', border: 'border-indigo-100' },
    'pronunciation-tips': { bg: 'bg-amber-50/30', border: 'border-amber-100' },
    'pronunciation-practice': { bg: 'bg-blue-50/30', border: 'border-blue-200' },
    'flashcards': { bg: 'bg-indigo-50/30', border: 'border-indigo-100' },
    'matching-game': { bg: 'bg-emerald-50/30', border: 'border-emerald-100' },
    'letter-sorting': { bg: 'bg-blue-50/30', border: 'border-blue-100' },
    'dialogues': { bg: 'bg-purple-50/30', border: 'border-purple-100' },
    'cultural': { bg: 'bg-rose-50/30', border: 'border-rose-100' },
    'spelling-challenge': { bg: 'bg-blue-50/40', border: 'border-blue-100' },
    'knowledge-check': { bg: 'bg-indigo-50/40', border: 'border-indigo-100' },
  },
}

// Export phrase lookup for flashcard component
export const L11PhraseByAudio = phraseByAudio

// Spelling Challenge rounds — student hears a word, must spell it using letter names
export const SPELLING_CHALLENGE_ROUNDS = [
  {
    word: 'Hola',
    english: 'Hello',
    audio: 'hola',
    spelling: ['H', 'O', 'L', 'A'],
    options: ['H', 'O', 'L', 'A', 'E', 'N', 'S', 'R'],
    hint: '4 letters',
  },
  {
    word: 'Niño',
    english: 'Child / Boy',
    audio: 'nino',
    spelling: ['N', 'I', 'Ñ', 'O'],
    options: ['N', 'I', 'Ñ', 'O', 'A', 'E', 'L', 'R'],
    hint: '4 letters — includes a unique Spanish letter',
  },
  {
    word: 'Queso',
    english: 'Cheese',
    audio: 'queso',
    spelling: ['Q', 'U', 'E', 'S', 'O'],
    options: ['Q', 'U', 'E', 'S', 'O', 'A', 'I', 'C'],
    hint: '5 letters — starts with QU',
  },
  {
    word: 'Calle',
    english: 'Street',
    audio: 'calle',
    spelling: ['C', 'A', 'L', 'L', 'E'],
    options: ['C', 'A', 'L', 'L', 'E', 'O', 'N', 'R'],
    hint: '5 letters — has a double letter',
  },
  {
    word: 'Perro',
    english: 'Dog',
    audio: 'perro-vs-pero',
    spelling: ['P', 'E', 'R', 'R', 'O'],
    options: ['P', 'E', 'R', 'R', 'O', 'A', 'L', 'S'],
    hint: '5 letters — has RR',
  },
  {
    word: 'Guitarra',
    english: 'Guitar',
    audio: 'guitarra',
    spelling: ['G', 'U', 'I', 'T', 'A', 'R', 'R', 'A'],
    options: ['G', 'U', 'I', 'T', 'A', 'R', 'R', 'A', 'E', 'O'],
    hint: '8 letters — GU + I, double RR',
  },
  {
    word: 'Zapato',
    english: 'Shoe',
    audio: 'zapato',
    spelling: ['Z', 'A', 'P', 'A', 'T', 'O'],
    options: ['Z', 'A', 'P', 'A', 'T', 'O', 'E', 'S'],
    hint: '6 letters — starts with Z',
  },
  {
    word: 'México',
    english: 'Mexico',
    audio: 'mexico',
    spelling: ['M', 'É', 'X', 'I', 'C', 'O'],
    options: ['M', 'É', 'X', 'I', 'C', 'O', 'A', 'E'],
    hint: '6 letters — the X sounds like "h"',
  },
]
