import type { LessonData } from '@/lib/types/lesson'

const PHRASES = [
  // Greetings
  { spanish: 'Hola', english: 'Hello', pronunciation: 'OH-lah', category: 'greeting', audio: 'hola' },
  { spanish: 'Buenos días', english: 'Good morning', pronunciation: 'BWEH-nos DEE-ahs', category: 'greeting', audio: 'buenos-dias' },
  { spanish: 'Buenas tardes', english: 'Good afternoon', pronunciation: 'BWEH-nahs TAR-dehs', category: 'greeting', audio: 'buenas-tardes' },
  { spanish: 'Buenas noches', english: 'Good evening / Good night', pronunciation: 'BWEH-nahs NOH-chehs', category: 'greeting', audio: 'buenas-noches' },
  { spanish: '¿Cómo está?', english: 'How are you? (formal)', pronunciation: 'KOH-moh ehs-TAH', category: 'greeting', audio: 'como-esta' },
  { spanish: '¿Qué tal?', english: "How's it going? (informal)", pronunciation: 'keh tahl', category: 'greeting', audio: 'que-tal' },
  // Farewells
  { spanish: 'Adiós', english: 'Goodbye', pronunciation: 'ah-dee-OHS', category: 'farewell', audio: 'adios' },
  { spanish: 'Hasta luego', english: 'See you later', pronunciation: 'AHS-tah LWEH-goh', category: 'farewell', audio: 'hasta-luego' },
  { spanish: 'Hasta mañana', english: 'See you tomorrow', pronunciation: 'AHS-tah mah-NYAH-nah', category: 'farewell', audio: 'hasta-manana' },
  { spanish: 'Nos vemos', english: 'See you', pronunciation: 'nohs VEH-mohs', category: 'farewell', audio: 'nos-vemos' },
  { spanish: 'Chao', english: 'Bye (informal)', pronunciation: 'chow', category: 'farewell', audio: 'chao' },
  { spanish: 'Hasta pronto', english: 'See you soon', pronunciation: 'AHS-tah PROHN-toh', category: 'farewell', audio: 'hasta-pronto' },
  // Polite expressions
  { spanish: 'Gracias', english: 'Thank you', pronunciation: 'GRAH-see-ahs', category: 'polite', audio: 'gracias' },
  { spanish: 'Muchas gracias', english: 'Thank you very much', pronunciation: 'MOO-chahs GRAH-see-ahs', category: 'polite', audio: 'muchas-gracias' },
  { spanish: 'Por favor', english: 'Please', pronunciation: 'pohr fah-BOHR', category: 'polite', audio: 'por-favor' },
  { spanish: 'Disculpe', english: 'Excuse me (formal)', pronunciation: 'dees-KOOL-peh', category: 'polite', audio: 'disculpe' },
  { spanish: 'Lo siento', english: "I'm sorry", pronunciation: 'loh see-EHN-toh', category: 'polite', audio: 'lo-siento' },
  { spanish: 'Perdón', english: 'Pardon', pronunciation: 'pehr-DOHN', category: 'polite', audio: 'perdon' },
  { spanish: 'Bien, gracias', english: 'Fine, thank you', pronunciation: 'bee-EHN GRAH-see-ahs', category: 'polite', audio: 'bien-gracias' },
  { spanish: 'Mil gracias', english: 'A thousand thanks', pronunciation: 'meel GRAH-see-ahs', category: 'polite', audio: 'mil-gracias' },
  // Introductions
  { spanish: 'Me llamo...', english: 'My name is...', pronunciation: 'meh YAH-moh', category: 'introduction', audio: 'me-llamo' },
  { spanish: 'Mucho gusto', english: 'Nice to meet you', pronunciation: 'MOO-choh GOOS-toh', category: 'introduction', audio: 'mucho-gusto' },
  { spanish: 'Encantado', english: 'Delighted to meet you', pronunciation: 'ehn-kahn-TAH-doh', category: 'introduction', audio: 'encantado' },
  { spanish: 'Soy de...', english: "I'm from...", pronunciation: 'soy deh', category: 'introduction', audio: 'soy-de' },
  { spanish: '¿Cómo te llamas?', english: "What's your name? (informal)", pronunciation: 'KOH-moh teh YAH-mahs', category: 'introduction', audio: 'como-te-llamas' },
  { spanish: '¿Cómo se llama?', english: "What's your name? (formal)", pronunciation: 'KOH-moh seh YAH-mah', category: 'introduction', audio: 'como-se-llama' },
  { spanish: '¿De dónde eres?', english: 'Where are you from? (informal)', pronunciation: 'deh DOHN-deh EH-rehs', category: 'introduction', audio: 'de-donde-eres' },
  { spanish: '¿De dónde es?', english: 'Where are you from? (formal)', pronunciation: 'deh DOHN-deh ehs', category: 'introduction', audio: 'de-donde-es' },
  { spanish: 'Soy...', english: 'I am...', pronunciation: 'soy', category: 'introduction', audio: 'soy' },
  { spanish: 'El gusto es mío', english: 'The pleasure is mine', pronunciation: 'ehl GOOS-toh ehs MEE-oh', category: 'introduction', audio: 'el-gusto-es-mio' },
  { spanish: 'Muy bien, gracias', english: 'Very well, thank you', pronunciation: 'mooy bee-EHN GRAH-see-ahs', category: 'introduction', audio: 'muy-bien' },
  { spanish: 'Más o menos', english: 'So-so', pronunciation: 'mahs oh MEH-nohs', category: 'introduction', audio: 'mas-o-menos' },
  // Essential questions
  { spanish: '¿Habla inglés?', english: 'Do you speak English?', pronunciation: 'AH-blah een-GLEHS', category: 'question', audio: 'habla-ingles' },
  { spanish: 'No entiendo', english: "I don't understand", pronunciation: 'noh ehn-tee-EHN-doh', category: 'question', audio: 'no-entiendo' },
  { spanish: 'No hablo español', english: "I don't speak Spanish", pronunciation: 'noh AH-bloh ehs-pah-NYOHL', category: 'question', audio: 'no-hablo-espanol' },
  { spanish: '¿Puede repetir?', english: 'Can you repeat that?', pronunciation: 'PWEH-deh reh-peh-TEER', category: 'question', audio: 'puede-repetir' },
  { spanish: 'Más despacio, por favor', english: 'Slower, please', pronunciation: 'mahs dehs-PAH-see-oh pohr fah-BOHR', category: 'question', audio: 'mas-despacio' },
  { spanish: 'No sé', english: "I don't know", pronunciation: 'noh seh', category: 'question', audio: 'no-se' },
]

const phraseByAudio: Record<string, (typeof PHRASES)[number]> = {}
PHRASES.forEach((p) => { phraseByAudio[p.audio] = p })

export const L12Data: LessonData = {
  id: 'L1.2',
  hero: {
    lessonId: 'L1.2',
    title: 'Meeting People',
    subtitle: 'Greetings, introductions & polite expressions',
    description: 'Learn to greet people, introduce yourself, and navigate basic social situations. In Spanish-speaking cultures, greetings are never skipped — they are the foundation of every interaction.',
    image: '/images/L1.2/hero-meeting.png',
    gradient: 'from-emerald-800/65 via-teal-700/55 to-cyan-700/65',
    accentColor: 'emerald-200',
  },
  priorKnowledge: [
    {
      fromLesson: 'L1.1',
      label: 'Pronunciation Rules',
      detail: 'H is silent in "Hola" (OH-lah). LL sounds like "y" in "llamo." The Ñ in "mañana" = "ny" in canyon.',
    },
    {
      fromLesson: 'L1.1',
      label: 'Spelling Your Name',
      detail: 'You can now spell your name using Spanish letter names — useful when introducing yourself.',
    },
  ],
  sectionTransitions: [
    { afterSection: 'greetings', text: 'You know how to say hello! Now let\'s learn how to say goodbye.' },
    { afterSection: 'farewells', text: 'Great farewells! Now let\'s add the magic words that make everything smoother.' },
    { afterSection: 'polite', text: 'With these polite phrases, you\'ll make a great impression. Now let\'s introduce yourself.' },
    { afterSection: 'introductions', text: 'You can now introduce yourself! Let\'s add some essential survival questions.' },
    { afterSection: 'essential-questions', text: 'You now have a complete social toolkit. Let\'s sharpen your pronunciation.' },
    { afterSection: 'dialogues', text: 'You just heard real Spanish conversations in action. Let\'s explore the culture behind these phrases.' },
    { afterSection: 'cultural', text: 'Now let\'s put it all together — build a complete conversation!' },
    { afterSection: 'conversation-builder', text: 'Final stretch — let\'s check how much you\'ve learned!' },
  ],
  personalizedVocab: [
    { spanish: 'Hola, Buenos días', english: 'Hello / Good morning' },
    { spanish: 'Me llamo...', english: 'My name is...' },
    { spanish: 'Mucho gusto', english: 'Nice to meet you' },
    { spanish: 'Gracias, Por favor', english: 'Thank you / Please' },
    { spanish: '¿De dónde eres?', english: 'Where are you from?' },
    { spanish: 'No entiendo', english: "I don't understand" },
  ],
  pronunciationChallenges: [
    { spanish: 'Hola, buenos días', pronunciation: 'OH-lah BWEH-nos DEE-ahs', english: 'Hello, good morning', audio: 'buenos-dias', tip: 'Remember from L1.1: H is ALWAYS silent! "Hola" starts with the O sound.' },
    { spanish: 'Me llamo Ana', pronunciation: 'meh YAH-moh AH-nah', english: 'My name is Ana', audio: 'me-llamo', tip: 'LL sounds like "y" — "llamo" = "YAH-moh." You learned this in L1.1!' },
    { spanish: 'Mucho gusto', pronunciation: 'MOO-choh GOOS-toh', english: 'Nice to meet you', audio: 'mucho-gusto', tip: 'CH = "ch" as in "church." GU before O = hard "g" — "GOOS-toh."' },
    { spanish: 'Hasta mañana', pronunciation: 'AHS-tah mah-NYAH-nah', english: 'See you tomorrow', audio: 'hasta-manana', tip: 'The Ñ from L1.1! "Mañana" has the "ny" sound — mah-NYAH-nah.' },
    { spanish: 'Más despacio, por favor', pronunciation: 'mahs dehs-PAH-see-oh pohr fah-BOHR', english: 'Slower, please', audio: 'mas-despacio', tip: 'Your most useful survival phrase! Stress the -PA- in "despacio."' },
    { spanish: 'Encantado de conocerle', pronunciation: 'ehn-kahn-TAH-doh deh koh-noh-SEHR-leh', english: 'Delighted to meet you', audio: 'encantado', tip: 'A formal, elegant phrase. The C before O = "k" sound (L1.1 rule).' },
  ],
  objectives: [
    { icon: '\uD83D\uDC4B', title: 'Greet & Say Goodbye', desc: 'Use the right greeting for any time of day and say farewell naturally' },
    { icon: '\uD83E\uDD1D', title: 'Introduce Yourself', desc: 'Share your name, origin, and respond to introductions' },
    { icon: '\u2728', title: 'Be Polite', desc: 'Master "please," "thank you," "excuse me," and "sorry"' },
    { icon: '\uD83C\uDD98', title: 'Survival Questions', desc: 'Ask for help when you don\'t understand or need something repeated' },
  ],
  sections: [
    { id: 'welcome', label: 'Welcome' },
    { id: 'prior-knowledge', label: 'What You Already Know' },
    { id: 'objectives', label: "What You'll Learn" },
    { id: 'personalized-context', label: 'See in YOUR Context' },
    { id: 'greetings', label: 'Greetings' },
    { id: 'farewells', label: 'Farewells' },
    { id: 'polite', label: 'Polite Expressions' },
    { id: 'introductions', label: 'Introducing Yourself' },
    { id: 'essential-questions', label: 'Essential Questions' },
    { id: 'pronunciation-tips', label: 'Pronunciation Tips' },
    { id: 'pronunciation-practice', label: 'Pronunciation Practice' },
    { id: 'flashcards', label: 'Flashcards' },
    { id: 'matching-game', label: 'Matching Game' },
    { id: 'phrase-sorting', label: 'Sort the Phrases' },
    { id: 'dialogues', label: 'Real-World Dialogues' },
    { id: 'cultural', label: 'Culture & Real Life' },
    { id: 'conversation-builder', label: 'Conversation Builder' },
    { id: 'knowledge-check', label: 'Knowledge Check' },
  ],
  audioBase: '/audio/L1.2/phrases',
  phraseSections: [
    {
      id: 'greetings',
      title: 'Spanish Greetings',
      description: 'In Spanish-speaking cultures, greetings are NEVER skipped. Even a quick "Hola" is expected before any conversation.',
      tabs: [
        { label: 'All Greetings', color: 'emerald', phrases: PHRASES.filter(p => p.category === 'greeting') },
      ],
    },
    {
      id: 'farewells',
      title: 'Farewells',
      description: 'Spanish has many ways to say goodbye — from formal "Adiós" to casual "Chao." Choose based on the situation.',
      tabs: [
        { label: 'All Farewells', color: 'blue', phrases: PHRASES.filter(p => p.category === 'farewell') },
      ],
    },
    {
      id: 'polite',
      title: 'Polite Expressions',
      description: 'These words open doors everywhere. "Por favor" and "Gracias" are the most important words you\'ll learn.',
      tabs: [
        { label: 'Polite Phrases', color: 'purple', phrases: PHRASES.filter(p => p.category === 'polite'), columns: 2 },
      ],
    },
    {
      id: 'introductions',
      title: 'Introducing Yourself',
      description: 'Learn to share your name and where you\'re from. Notice the difference between tú (informal) and usted (formal).',
      tabs: [
        { label: 'Informal (tú)', color: 'amber', phrases: PHRASES.filter(p => p.category === 'introduction' && ['como-te-llamas', 'de-donde-eres', 'mas-o-menos'].includes(p.audio)) },
        { label: 'Formal (usted)', color: 'teal', phrases: PHRASES.filter(p => p.category === 'introduction' && ['como-se-llama', 'de-donde-es', 'encantado', 'el-gusto-es-mio'].includes(p.audio)) },
        { label: 'Both', color: 'emerald', phrases: PHRASES.filter(p => p.category === 'introduction' && ['me-llamo', 'mucho-gusto', 'soy-de', 'soy', 'muy-bien'].includes(p.audio)) },
      ],
    },
    {
      id: 'essential-questions',
      title: 'Essential Survival Questions',
      description: 'These phrases will save you when you\'re lost, confused, or need help. Memorize them — they\'re your safety net.',
      tabs: [
        { label: 'Survival Kit', color: 'rose', phrases: PHRASES.filter(p => p.category === 'question'), columns: 2 },
      ],
    },
  ],
  pronunciationTips: [
    {
      title: 'Greetings: Silent H and Stress',
      content: '"Hola" starts with an O sound — the H is silent (L1.1). "Buenos días" stresses DEE-ahs. "Buenas tardes" stresses TAR-dehs. "Buenas noches" stresses NOH-chehs. The pattern: "buenos/buenas" + time of day.',
      example: 'Hola = OH-lah | Buenos días = BWEH-nos DEE-ahs',
      reviewFrom: 'L1.1',
    },
    {
      title: 'Tú vs. Usted — It\'s All About Respect',
      content: 'Use "tú" (informal) with friends, peers, and children. Use "usted" (formal) with strangers, elders, and professional settings. Listen for the difference: "¿Cómo te llamas?" (tú) vs. "¿Cómo se llama?" (usted). When in doubt, use usted — it\'s always safe.',
      example: 'Tú: ¿Cómo te llamas? | Usted: ¿Cómo se llama?',
    },
    {
      title: 'The LL Sound in "Llamo"',
      content: 'From L1.1: LL sounds like "y" in most countries. "Me llamo" = "meh YAH-moh." In Argentina and Uruguay, LL sounds more like "sh" — so "me llamo" = "meh SHA-moh." Both are correct!',
      example: 'Me llamo = meh YAH-moh (most countries) | meh SHA-moh (Argentina)',
      reviewFrom: 'L1.1',
    },
    {
      title: '"Disculpe" vs. "Lo siento" — Not the Same!',
      content: '"Disculpe" = Excuse me (to get attention or pass by). "Lo siento" = I\'m sorry (expressing regret). "Perdón" works for both but is lighter. Think of it this way: "Disculpe" = before something happens, "Lo siento" = after something bad happens.',
      example: 'Disculpe, ¿habla inglés? | Lo siento, no entiendo.',
    },
  ],
  flashcardGroups: [
    { key: 'greetings-farewells', label: 'Greetings & Farewells', audioKeys: ['hola', 'buenos-dias', 'buenas-tardes', 'buenas-noches', 'que-tal', 'adios', 'hasta-luego', 'hasta-manana', 'nos-vemos', 'chao'] },
    { key: 'polite-intro', label: 'Polite & Introductions', audioKeys: ['gracias', 'muchas-gracias', 'por-favor', 'disculpe', 'lo-siento', 'me-llamo', 'mucho-gusto', 'encantado', 'soy-de', 'el-gusto-es-mio'] },
    { key: 'survival', label: 'Survival Questions', audioKeys: ['habla-ingles', 'no-entiendo', 'no-hablo-espanol', 'puede-repetir', 'mas-despacio', 'no-se'] },
  ],
  matchPairs: [
    { left: 'Hola', right: 'Hello' },
    { left: 'Adiós', right: 'Goodbye' },
    { left: 'Gracias', right: 'Thank you' },
    { left: 'Por favor', right: 'Please' },
    { left: 'Hasta luego', right: 'See you later' },
    { left: 'Lo siento', right: "I'm sorry" },
    { left: 'Buenos días', right: 'Good morning' },
    { left: 'No entiendo', right: "I don't understand" },
  ],
  matchLabels: { left: 'Spanish', right: 'English' },
  sortActivities: [
    {
      title: 'Formal vs. Informal',
      instruction: 'Sort each phrase into Formal or Informal.',
      buckets: ['Formal', 'Informal'],
      items: [
        { text: '¿Cómo está usted?', bucket: 'Formal' },
        { text: 'Mucho gusto', bucket: 'Formal' },
        { text: 'Disculpe', bucket: 'Formal' },
        { text: '¿Cómo se llama?', bucket: 'Formal' },
        { text: '¿Qué tal?', bucket: 'Informal' },
        { text: 'Chao', bucket: 'Informal' },
        { text: 'Nos vemos', bucket: 'Informal' },
        { text: '¿Cómo te llamas?', bucket: 'Informal' },
      ],
    },
    {
      title: 'Greetings vs. Farewells',
      instruction: 'Sort each phrase into Greetings or Farewells.',
      buckets: ['Greetings', 'Farewells'],
      items: [
        { text: 'Hola', bucket: 'Greetings' },
        { text: 'Buenos días', bucket: 'Greetings' },
        { text: 'Buenas tardes', bucket: 'Greetings' },
        { text: '¿Cómo está?', bucket: 'Greetings' },
        { text: 'Adiós', bucket: 'Farewells' },
        { text: 'Hasta luego', bucket: 'Farewells' },
        { text: 'Hasta mañana', bucket: 'Farewells' },
        { text: 'Nos vemos', bucket: 'Farewells' },
      ],
    },
    {
      title: 'True or False?',
      instruction: 'Sort each statement as True or False.',
      buckets: ['True', 'False'],
      items: [
        { text: '"Buenas noches" = greeting & farewell', bucket: 'True' },
        { text: 'Skipping a greeting is rude in Spanish', bucket: 'True' },
        { text: '"Me llamo" = "I call myself"', bucket: 'True' },
        { text: '"Encantado/a" changes by gender', bucket: 'True' },
        { text: '"Tú" is the formal "you"', bucket: 'False' },
        { text: '"Adiós" is the most casual farewell', bucket: 'False' },
        { text: '"Disculpe" and "Lo siento" = same', bucket: 'False' },
        { text: '"Buenos días" works at any time', bucket: 'False' },
      ],
    },
  ],
  sortSectionId: 'phrase-sorting',
  sortTitle: 'Sort the Phrases',
  dialogues: [
    {
      id: 'dialogue-conference',
      title: 'Meeting Someone New — At a Conference',
      location: 'Conference',
      lines: [
        { speaker: 'Ana', text: 'Hola, buenos días. Me llamo Ana. ¿Cómo se llama?', audio: '/audio/L1.2/dialogues/d1-line1.mp3' },
        { speaker: 'Luis', text: 'Buenos días. Soy Luis. Mucho gusto.', audio: '/audio/L1.2/dialogues/d1-line2.mp3' },
        { speaker: 'Ana', text: 'Encantada. ¿De dónde es?', audio: '/audio/L1.2/dialogues/d1-line3.mp3' },
        { speaker: 'Luis', text: 'Soy de Colombia. ¿Y usted?', audio: '/audio/L1.2/dialogues/d1-line4.mp3' },
        { speaker: 'Ana', text: 'Soy de México. ¿Cómo está?', audio: '/audio/L1.2/dialogues/d1-line5.mp3' },
        { speaker: 'Luis', text: 'Muy bien, gracias. El gusto es mío.', audio: '/audio/L1.2/dialogues/d1-line6.mp3' },
      ],
    },
    {
      id: 'dialogue-goodbye',
      title: 'Saying Goodbye — After Class',
      location: 'School',
      lines: [
        { speaker: 'Ana', text: 'Disculpe, ¿habla inglés?', audio: '/audio/L1.2/dialogues/d2-line1.mp3' },
        { speaker: 'Luis', text: 'No, lo siento. No hablo inglés.', audio: '/audio/L1.2/dialogues/d2-line2.mp3' },
        { speaker: 'Ana', text: 'Más despacio, por favor. No entiendo bien.', audio: '/audio/L1.2/dialogues/d2-line3.mp3' },
        { speaker: 'Luis', text: 'Sí, por supuesto. Hasta mañana.', audio: '/audio/L1.2/dialogues/d2-line4.mp3' },
        { speaker: 'Ana', text: '¡Muchas gracias! ¡Chao!', audio: '/audio/L1.2/dialogues/d2-line5.mp3' },
        { speaker: 'Luis', text: '¡Chao! Que te vaya bien.', audio: '/audio/L1.2/dialogues/d2-line6.mp3' },
      ],
    },
  ],
  dialogueDescription: 'Listen to real conversations where Spanish speakers meet for the first time and say goodbye. Notice the formal (usted) and informal (tú) forms.',
  culturalNotes: [
    {
      title: 'Never Skip the Greeting',
      content: 'In Spanish-speaking cultures, jumping straight to business without a greeting is considered rude. Even a quick "Hola, ¿cómo está?" before asking a question makes a huge difference. At stores, restaurants, and even with strangers — always greet first.',
    },
    {
      title: 'Tú vs. Usted — The Cultural Map',
      content: 'Usage varies by country. In Colombia, "usted" is common even between friends. In Spain, "tú" dominates casual settings. In Mexico, "usted" is standard with strangers and elders. In Argentina, "vos" replaces "tú" entirely. When in doubt, use "usted" — no one is offended by too much respect.',
    },
    {
      title: 'Physical Greetings — Cheek Kisses & Handshakes',
      content: 'In most of Latin America and Spain, people greet with a kiss on the cheek (women with everyone, men sometimes with women). In Mexico and Central America, a handshake is more common in professional settings. Argentina: one kiss. Spain: two kisses (left, then right). Colombia: one kiss (women) or handshake (men).',
    },
  ],
  culturalGradient: 'from-emerald-50 to-teal-50',
  quiz: [
    { id: 1, type: 'mc', text: 'Which greeting would you use at 10 AM?', options: ['Buenas tardes', 'Buenos días', 'Buenas noches', 'Hasta luego'], answer: 1 },
    { id: 2, type: 'mc', text: "What does 'Hasta luego' mean?", options: ['Goodbye forever', 'See you later', 'Good night', 'Thank you'], answer: 1 },
    { id: 3, type: 'tf', text: "'Buenas noches' can be used both as a greeting and farewell.", answer: true },
    { id: 4, type: 'mc', text: "How do you say 'Please' in Spanish?", options: ['Gracias', 'De nada', 'Por favor', 'Disculpe'], answer: 2 },
    { id: 5, type: 'mc', text: 'Which phrase would you use to apologize for bumping into someone?', options: ['Lo siento', 'Gracias', 'Hola', 'Chao'], answer: 0 },
    { id: 6, type: 'tf', text: "'Chao' is a formal way to say goodbye.", answer: false },
    { id: 7, type: 'mc', text: "What is the formal way to ask 'How are you?'", options: ['¿Qué tal?', '¿Qué onda?', '¿Cómo está usted?', '¿Cómo estás?'], answer: 2 },
    { id: 8, type: 'fill', text: "Complete: 'Muchas ___' (Thank you very much)", answer: 'gracias' },
    { id: 9, type: 'mc', text: 'Someone is talking too fast. What do you say?', options: ['No sé', 'Más despacio, por favor', 'Lo siento', 'Perdón'], answer: 1 },
    { id: 10, type: 'tf', text: "'Disculpe' and 'Lo siento' mean exactly the same thing.", answer: false },
    { id: 11, type: 'mc', text: "You're leaving work and will see your coworker tomorrow. You say:", options: ['Adiós', 'Hasta mañana', 'Chao', 'Buenas noches'], answer: 1 },
    { id: 12, type: 'fill', text: "Complete: 'No hablo ___' (I don't speak Spanish)", answer: 'español' },
    { id: 13, type: 'mc', text: "What does 'No entiendo' mean?", options: ["I don't know", "I don't speak", "I don't understand", "I'm sorry"], answer: 2 },
    { id: 14, type: 'mc', text: 'What is the most universal, all-purpose greeting in Spanish?', options: ['Buenos días', 'Buenas tardes', 'Hola', '¿Qué tal?'], answer: 2 },
    { id: 15, type: 'tf', text: "It's OK to skip greetings and go straight to business in Spanish-speaking cultures.", answer: false },
  ],
  uniqueActivity: {
    id: 'ConversationBuilderL12',
    sectionId: 'conversation-builder',
    sectionColor: 'bg-emerald-50/40',
    sectionBorder: 'border-emerald-100',
  },
  sectionColors: {
    'prior-knowledge': { bg: 'bg-indigo-50/30', border: 'border-indigo-100' },
    objectives: { bg: 'bg-white', border: '' },
    'personalized-context': { bg: 'bg-violet-50/30', border: 'border-violet-100' },
    greetings: { bg: 'bg-emerald-50/30', border: 'border-emerald-100' },
    farewells: { bg: 'bg-blue-50/30', border: 'border-blue-100' },
    polite: { bg: 'bg-purple-50/30', border: 'border-purple-100' },
    introductions: { bg: 'bg-amber-50/30', border: 'border-amber-100' },
    'essential-questions': { bg: 'bg-rose-50/30', border: 'border-rose-100' },
    'pronunciation-tips': { bg: 'bg-yellow-50/30', border: 'border-yellow-100' },
    'pronunciation-practice': { bg: 'bg-blue-50/30', border: 'border-blue-200' },
    flashcards: { bg: 'bg-emerald-50/30', border: 'border-emerald-100' },
    'matching-game': { bg: 'bg-teal-50/30', border: 'border-teal-100' },
    'phrase-sorting': { bg: 'bg-blue-50/30', border: 'border-blue-100' },
    dialogues: { bg: 'bg-purple-50/30', border: 'border-purple-100' },
    cultural: { bg: 'bg-rose-50/30', border: 'border-rose-100' },
    'conversation-builder': { bg: 'bg-emerald-50/40', border: 'border-emerald-100' },
    'knowledge-check': { bg: 'bg-indigo-50/40', border: 'border-indigo-100' },
  },
}

export const L12PhraseByAudio = phraseByAudio

// Conversation Builder rounds — student arranges scrambled lines into a coherent conversation
export const CONVERSATION_BUILDER_ROUNDS = [
  {
    title: 'Meeting at a Party',
    correctOrder: [
      'Hola, buenos días.',
      'Buenos días. ¿Cómo se llama?',
      'Me llamo María. Mucho gusto.',
      'Encantado. Soy Luis. ¿De dónde es?',
      'Soy de México. ¿Y usted?',
      'Soy de Colombia.',
    ],
  },
  {
    title: 'Asking for Help',
    correctOrder: [
      'Disculpe, ¿habla inglés?',
      'No, lo siento. No hablo inglés.',
      'No entiendo. ¿Puede repetir?',
      'Más despacio, por favor.',
      'Sí, por supuesto.',
      'Muchas gracias.',
    ],
  },
  {
    title: 'Saying Goodbye After Class',
    correctOrder: [
      '¡Gracias por la clase!',
      'De nada. ¿Vienes mañana?',
      'Sí, hasta mañana.',
      '¡Nos vemos! ¡Chao!',
      '¡Chao! Que te vaya bien.',
    ],
  },
]
