import type { LessonData } from '@/lib/types/lesson'

const PHRASES = [
  // Numbers 0-10
  { spanish: 'Cero', english: 'Zero (0)', pronunciation: 'SEH-roh', category: 'number-basic', audio: 'cero' },
  { spanish: 'Uno', english: 'One (1)', pronunciation: 'OO-noh', category: 'number-basic', audio: 'uno' },
  { spanish: 'Dos', english: 'Two (2)', pronunciation: 'dohs', category: 'number-basic', audio: 'dos' },
  { spanish: 'Tres', english: 'Three (3)', pronunciation: 'trehs', category: 'number-basic', audio: 'tres' },
  { spanish: 'Cuatro', english: 'Four (4)', pronunciation: 'KWAH-troh', category: 'number-basic', audio: 'cuatro' },
  { spanish: 'Cinco', english: 'Five (5)', pronunciation: 'SEEN-koh', category: 'number-basic', audio: 'cinco' },
  { spanish: 'Seis', english: 'Six (6)', pronunciation: 'says', category: 'number-basic', audio: 'seis' },
  { spanish: 'Siete', english: 'Seven (7)', pronunciation: 'see-EH-teh', category: 'number-basic', audio: 'siete' },
  { spanish: 'Ocho', english: 'Eight (8)', pronunciation: 'OH-choh', category: 'number-basic', audio: 'ocho' },
  { spanish: 'Nueve', english: 'Nine (9)', pronunciation: 'NWEH-beh', category: 'number-basic', audio: 'nueve' },
  { spanish: 'Diez', english: 'Ten (10)', pronunciation: 'dee-EHS', category: 'number-basic', audio: 'diez' },
  // Numbers 11-20
  { spanish: 'Once', english: 'Eleven (11)', pronunciation: 'OHN-seh', category: 'number-basic', audio: 'once' },
  { spanish: 'Doce', english: 'Twelve (12)', pronunciation: 'DOH-seh', category: 'number-basic', audio: 'doce' },
  { spanish: 'Trece', english: 'Thirteen (13)', pronunciation: 'TREH-seh', category: 'number-basic', audio: 'trece' },
  { spanish: 'Catorce', english: 'Fourteen (14)', pronunciation: 'kah-TOHR-seh', category: 'number-basic', audio: 'catorce' },
  { spanish: 'Quince', english: 'Fifteen (15)', pronunciation: 'KEEN-seh', category: 'number-basic', audio: 'quince' },
  { spanish: 'Dieciséis', english: 'Sixteen (16)', pronunciation: 'dee-eh-see-SAYS', category: 'number-basic', audio: 'dieciseis' },
  { spanish: 'Diecisiete', english: 'Seventeen (17)', pronunciation: 'dee-eh-see-see-EH-teh', category: 'number-basic', audio: 'diecisiete' },
  { spanish: 'Dieciocho', english: 'Eighteen (18)', pronunciation: 'dee-eh-see-OH-choh', category: 'number-basic', audio: 'dieciocho' },
  { spanish: 'Diecinueve', english: 'Nineteen (19)', pronunciation: 'dee-eh-see-NWEH-beh', category: 'number-basic', audio: 'diecinueve' },
  { spanish: 'Veinte', english: 'Twenty (20)', pronunciation: 'BAYN-teh', category: 'number-basic', audio: 'veinte' },
  // Numbers 21-100
  { spanish: 'Veintiuno', english: 'Twenty-one (21)', pronunciation: 'bayn-tee-OO-noh', category: 'number-advanced', audio: 'veintiuno' },
  { spanish: 'Veintidós', english: 'Twenty-two (22)', pronunciation: 'bayn-tee-DOHS', category: 'number-advanced', audio: 'veintidos' },
  { spanish: 'Veinticinco', english: 'Twenty-five (25)', pronunciation: 'bayn-tee-SEEN-koh', category: 'number-advanced', audio: 'veinticinco' },
  { spanish: 'Treinta', english: 'Thirty (30)', pronunciation: 'TRAYN-tah', category: 'number-advanced', audio: 'treinta' },
  { spanish: 'Cuarenta', english: 'Forty (40)', pronunciation: 'kwah-REHN-tah', category: 'number-advanced', audio: 'cuarenta' },
  { spanish: 'Cincuenta', english: 'Fifty (50)', pronunciation: 'seen-KWEHN-tah', category: 'number-advanced', audio: 'cincuenta' },
  { spanish: 'Sesenta', english: 'Sixty (60)', pronunciation: 'seh-SEHN-tah', category: 'number-advanced', audio: 'sesenta' },
  { spanish: 'Setenta', english: 'Seventy (70)', pronunciation: 'seh-TEHN-tah', category: 'number-advanced', audio: 'setenta' },
  { spanish: 'Ochenta', english: 'Eighty (80)', pronunciation: 'oh-CHEHN-tah', category: 'number-advanced', audio: 'ochenta' },
  { spanish: 'Noventa', english: 'Ninety (90)', pronunciation: 'noh-BEHN-tah', category: 'number-advanced', audio: 'noventa' },
  { spanish: 'Cien', english: 'One hundred (100)', pronunciation: 'see-EHN', category: 'number-advanced', audio: 'cien' },
  // Time
  { spanish: '¿Qué hora es?', english: 'What time is it?', pronunciation: 'keh OH-rah ehs', category: 'time', audio: 'que-hora-es' },
  { spanish: 'Es la una', english: "It's 1:00", pronunciation: 'ehs lah OO-nah', category: 'time', audio: 'es-la-una' },
  { spanish: 'Son las dos', english: "It's 2:00", pronunciation: 'sohn lahs dohs', category: 'time', audio: 'son-las-dos' },
  { spanish: 'Son las tres', english: "It's 3:00", pronunciation: 'sohn lahs trehs', category: 'time', audio: 'son-las-tres' },
  { spanish: 'y cuarto', english: ':15 (quarter past)', pronunciation: 'ee KWAHR-toh', category: 'time', audio: 'y-cuarto' },
  { spanish: 'y media', english: ':30 (half past)', pronunciation: 'ee MEH-dee-ah', category: 'time', audio: 'y-media' },
  { spanish: 'menos cuarto', english: ':45 (quarter to)', pronunciation: 'MEH-nohs KWAHR-toh', category: 'time', audio: 'menos-cuarto' },
  { spanish: 'Mediodía', english: 'Noon', pronunciation: 'meh-dee-oh-DEE-ah', category: 'time', audio: 'mediodia' },
  { spanish: 'Medianoche', english: 'Midnight', pronunciation: 'meh-dee-ah-NOH-cheh', category: 'time', audio: 'medianoche' },
  { spanish: 'de la mañana', english: 'in the morning (AM)', pronunciation: 'deh lah mah-NYAH-nah', category: 'time', audio: 'de-la-manana' },
  { spanish: 'de la tarde', english: 'in the afternoon (PM)', pronunciation: 'deh lah TAR-deh', category: 'time', audio: 'de-la-tarde' },
  { spanish: 'de la noche', english: 'at night (PM)', pronunciation: 'deh lah NOH-cheh', category: 'time', audio: 'de-la-noche' },
  // Age
  { spanish: 'Tengo ___ años', english: 'I am ___ years old', pronunciation: 'TEHN-goh ... AH-nyohs', category: 'age', audio: 'tengo-anos' },
  { spanish: '¿Cuántos años tienes?', english: 'How old are you?', pronunciation: 'KWAHN-tohs AH-nyohs', category: 'age', audio: 'cuantos-anos-tienes' },
  { spanish: 'Tengo veinte años', english: 'I am twenty years old', pronunciation: 'TEHN-goh BAYN-teh AH-nyohs', category: 'age', audio: 'tengo-veinte-anos' },
  // Phone & Calendar
  { spanish: '¿Cuál es tu número?', english: 'What is your number?', pronunciation: 'kwahl ehs too NOO-meh-roh', category: 'phone-date', audio: 'cual-es-tu-numero' },
  { spanish: 'Mi número es...', english: 'My number is...', pronunciation: 'mee NOO-meh-roh ehs', category: 'phone-date', audio: 'mi-numero-es' },
  // Days
  { spanish: 'Lunes', english: 'Monday', pronunciation: 'LOO-nehs', category: 'phone-date', audio: 'lunes' },
  { spanish: 'Martes', english: 'Tuesday', pronunciation: 'MAR-tehs', category: 'phone-date', audio: 'martes' },
  { spanish: 'Miércoles', english: 'Wednesday', pronunciation: 'mee-EHR-koh-lehs', category: 'phone-date', audio: 'miercoles' },
  { spanish: 'Jueves', english: 'Thursday', pronunciation: 'HWEH-behs', category: 'phone-date', audio: 'jueves' },
  { spanish: 'Viernes', english: 'Friday', pronunciation: 'bee-EHR-nehs', category: 'phone-date', audio: 'viernes' },
  { spanish: 'Sábado', english: 'Saturday', pronunciation: 'SAH-bah-doh', category: 'phone-date', audio: 'sabado' },
  { spanish: 'Domingo', english: 'Sunday', pronunciation: 'doh-MEEN-goh', category: 'phone-date', audio: 'domingo' },
  // Months
  { spanish: 'Enero', english: 'January', pronunciation: 'eh-NEH-roh', category: 'phone-date', audio: 'enero' },
  { spanish: 'Febrero', english: 'February', pronunciation: 'feh-BREH-roh', category: 'phone-date', audio: 'febrero' },
  { spanish: 'Marzo', english: 'March', pronunciation: 'MAR-soh', category: 'phone-date', audio: 'marzo' },
  { spanish: 'Abril', english: 'April', pronunciation: 'ah-BREEL', category: 'phone-date', audio: 'abril' },
  { spanish: 'Mayo', english: 'May', pronunciation: 'MAH-yoh', category: 'phone-date', audio: 'mayo' },
  { spanish: 'Junio', english: 'June', pronunciation: 'HOO-nee-oh', category: 'phone-date', audio: 'junio' },
  { spanish: 'Julio', english: 'July', pronunciation: 'HOO-lee-oh', category: 'phone-date', audio: 'julio' },
  { spanish: 'Agosto', english: 'August', pronunciation: 'ah-GOHS-toh', category: 'phone-date', audio: 'agosto' },
  { spanish: 'Septiembre', english: 'September', pronunciation: 'sehp-tee-EHM-breh', category: 'phone-date', audio: 'septiembre' },
  { spanish: 'Octubre', english: 'October', pronunciation: 'ohk-TOO-breh', category: 'phone-date', audio: 'octubre' },
  { spanish: 'Noviembre', english: 'November', pronunciation: 'noh-bee-EHM-breh', category: 'phone-date', audio: 'noviembre' },
  { spanish: 'Diciembre', english: 'December', pronunciation: 'dee-see-EHM-breh', category: 'phone-date', audio: 'diciembre' },
]

const phraseByAudio: Record<string, (typeof PHRASES)[number]> = {}
PHRASES.forEach((p) => { phraseByAudio[p.audio] = p })

export const L13Data: LessonData = {
  id: 'L1.3',
  hero: {
    lessonId: 'L1.3',
    title: 'Numbers & Time',
    subtitle: 'Counting, telling time & sharing your age',
    description: 'Learn numbers 0–100, tell time, say your age, and share your phone number. These are the building blocks for real conversations — from ordering at a restaurant to making plans.',
    image: '/images/L1.3/hero-numbers.png',
    gradient: 'from-orange-800/65 via-amber-700/55 to-yellow-600/65',
    accentColor: 'amber-200',
  },
  priorKnowledge: [
    {
      fromLesson: 'L1.1',
      label: 'Pronunciation Rules',
      detail: 'C before E/I = "s" sound — now in "cinco" (5), "cero" (0), "doce" (12). V sounds like B — "veinte" = "BAYN-teh."',
    },
    {
      fromLesson: 'L1.2',
      label: 'Greetings & Polite Phrases',
      detail: '"Buenos días," "por favor," "gracias" — essential for polite interactions where you\'ll use numbers.',
    },
  ],
  sectionTransitions: [
    { afterSection: 'numbers-0-20', text: 'Great — you know 0 to 20! Now let\'s go higher.' },
    { afterSection: 'numbers-21-100', text: 'You can now count to 100! Time to use those numbers to tell the time.' },
    { afterSection: 'telling-time', text: 'You can tell time in Spanish! Let\'s add age, days, and months.' },
    { afterSection: 'age-calendar', text: 'Your number toolkit is complete. Let\'s sharpen your pronunciation.' },
    { afterSection: 'dialogues', text: 'You just heard numbers in real conversations. Let\'s explore the cultural side.' },
    { afterSection: 'cultural', text: 'Ready for a challenge? Listen to numbers and write them down!' },
    { afterSection: 'number-dictation', text: 'Final stretch — let\'s see how much you\'ve learned!' },
  ],
  personalizedVocab: [
    { spanish: 'Uno, dos, tres...', english: 'Numbers 1-10' },
    { spanish: '¿Qué hora es?', english: 'What time is it?' },
    { spanish: 'Tengo ___ años', english: 'I am ___ years old' },
    { spanish: '¿Cuál es tu número?', english: 'What is your number?' },
    { spanish: 'Lunes, martes...', english: 'Days of the week' },
    { spanish: 'Enero, febrero...', english: 'Months of the year' },
  ],
  pronunciationChallenges: [
    { spanish: 'Veinticinco', pronunciation: 'bayn-tee-SEEN-koh', english: 'Twenty-five', audio: 'veinticinco', tip: 'Numbers 21-29 are ONE word. "Veinti-" + the ones digit. Stress the last syllable.' },
    { spanish: 'Son las tres y media', pronunciation: 'sohn lahs trehs ee MEH-dee-ah', english: 'It\'s 3:30', audio: 'son-las-tres', tip: '"Son las" for all hours except 1:00 (which uses "Es la"). "Y media" = half past.' },
    { spanish: 'Tengo veinte años', pronunciation: 'TEHN-goh BAYN-teh AH-nyohs', english: 'I am 20 years old', audio: 'tengo-veinte-anos', tip: 'In Spanish you "have" years, not "are" years. The Ñ in "años" = "ny" sound (L1.1).' },
    { spanish: 'Cincuenta y ocho', pronunciation: 'seen-KWEHN-tah ee OH-choh', english: 'Fifty-eight', audio: 'cincuenta', tip: 'From 30 up, compound numbers use "y" (and): treinta y uno, cuarenta y dos, etc.' },
    { spanish: 'Son las nueve de la noche', pronunciation: 'sohn lahs NWEH-beh deh lah NOH-cheh', english: 'It\'s 9:00 PM', audio: 'son-las-tres', tip: '"De la mañana" = AM, "de la tarde" = afternoon PM, "de la noche" = evening PM.' },
    { spanish: 'Mi número es cinco, tres, dos, ocho, uno, cero, nueve', pronunciation: 'mee NOO-meh-roh ehs...', english: 'My number is 5-3-2-8-1-0-9', audio: 'mi-numero-es', tip: 'Phone numbers are said one digit at a time in Spanish, not grouped like in English.' },
  ],
  objectives: [
    { icon: '\uD83D\uDD22', title: 'Count to 100', desc: 'Master numbers 0–100 including the tricky teens and twenties' },
    { icon: '\u23F0', title: 'Tell Time', desc: 'Say what time it is using "es la" and "son las"' },
    { icon: '\uD83C\uDF82', title: 'Say Your Age', desc: 'Use "tengo ___ años" to share your age in Spanish' },
    { icon: '\uD83D\uDCC5', title: 'Days & Months', desc: 'Learn the calendar vocabulary and share your phone number' },
  ],
  sections: [
    { id: 'welcome', label: 'Welcome' },
    { id: 'prior-knowledge', label: 'What You Already Know' },
    { id: 'objectives', label: "What You'll Learn" },
    { id: 'personalized-context', label: 'See in YOUR Context' },
    { id: 'numbers-0-20', label: 'Numbers 0–20' },
    { id: 'numbers-21-100', label: 'Numbers 21–100' },
    { id: 'telling-time', label: 'Telling Time' },
    { id: 'age-calendar', label: 'Age, Days & Months' },
    { id: 'pronunciation-tips', label: 'Pronunciation Tips' },
    { id: 'pronunciation-practice', label: 'Pronunciation Practice' },
    { id: 'flashcards', label: 'Flashcards' },
    { id: 'matching-game', label: 'Matching Game' },
    { id: 'number-sorting', label: 'Sort the Numbers' },
    { id: 'dialogues', label: 'Real-World Dialogues' },
    { id: 'cultural', label: 'Cultural Insights' },
    { id: 'number-dictation', label: 'Number Dictation' },
    { id: 'knowledge-check', label: 'Knowledge Check' },
  ],
  audioBase: '/audio/L1.3/phrases',
  phraseSections: [
    {
      id: 'numbers-0-20',
      title: 'Numbers 0–20',
      description: 'The foundation. Numbers 0–15 are unique words you must memorize. 16–19 follow the pattern "dieci-" + digit. Click to hear each one.',
      tabs: [
        { label: '0–10', color: 'amber', phrases: PHRASES.filter(p => p.category === 'number-basic').slice(0, 11) },
        { label: '11–20', color: 'orange', phrases: PHRASES.filter(p => p.category === 'number-basic').slice(11) },
      ],
    },
    {
      id: 'numbers-21-100',
      title: 'Numbers 21–100',
      description: '21–29 are one word ("veinti-"). From 30 up, use two words with "y": treinta y uno, cuarenta y dos...',
      tabs: [
        { label: '21–29', color: 'blue', phrases: PHRASES.filter(p => p.category === 'number-advanced' && ['veintiuno', 'veintidos', 'veinticinco'].includes(p.audio)) },
        { label: 'Tens (30–100)', color: 'purple', phrases: PHRASES.filter(p => p.category === 'number-advanced' && !p.audio.startsWith('veinti')) },
      ],
    },
    {
      id: 'telling-time',
      title: 'Telling Time',
      description: 'Key rule: "Es la una" (1:00 only, singular) vs. "Son las dos/tres/cuatro..." (all other hours, plural).',
      tabs: [
        { label: 'Hours', color: 'teal', phrases: PHRASES.filter(p => p.category === 'time' && ['que-hora-es', 'es-la-una', 'son-las-dos', 'son-las-tres', 'mediodia', 'medianoche'].includes(p.audio)), columns: 2 },
        { label: 'Minutes', color: 'emerald', phrases: PHRASES.filter(p => p.category === 'time' && ['y-cuarto', 'y-media', 'menos-cuarto', 'de-la-manana', 'de-la-tarde', 'de-la-noche'].includes(p.audio)), columns: 2 },
      ],
    },
    {
      id: 'age-calendar',
      title: 'Age, Days & Months',
      description: 'In Spanish you "have" years (tengo 25 años), you don\'t "are" them. Days and months are NOT capitalized.',
      tabs: [
        { label: 'Age & Phone', color: 'rose', phrases: PHRASES.filter(p => p.category === 'age' || ['cual-es-tu-numero', 'mi-numero-es'].includes(p.audio)), columns: 2 },
        { label: 'Days', color: 'amber', phrases: PHRASES.filter(p => ['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo'].includes(p.audio)) },
        { label: 'Months', color: 'orange', phrases: PHRASES.filter(p => ['enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre'].includes(p.audio)) },
      ],
    },
  ],
  pronunciationTips: [
    {
      title: 'Numbers 16–19: The "Dieci-" Pattern',
      content: 'Numbers 16–19 combine "diez" + digit into ONE word: dieciséis (16), diecisiete (17), dieciocho (18), diecinueve (19). The "z" in diez changes to "c" before "i." This is a regular L1.1 rule: C before I = "s" sound.',
      example: 'Dieciséis = dee-eh-see-SAYS | Dieciocho = dee-eh-see-OH-choh',
      reviewFrom: 'L1.1',
    },
    {
      title: 'Numbers 21–29 vs. 30+',
      content: '21–29 are ONE word: veintiuno, veintidós, veintitrés... From 30 up, they become TWO words with "y" (and): treinta y uno, cuarenta y dos. This "y" is pronounced "ee."',
      example: 'Veintiuno (21) = ONE word | Treinta y uno (31) = TWO words with "y"',
    },
    {
      title: '"Es la" vs. "Son las" — The Only Exception',
      content: '1:00 is singular: "Es la una." Every other hour is plural: "Son las dos," "Son las tres," etc. This is because "hora" (hour) is feminine: la una, las dos, las tres.',
      example: 'Es LA una y media (1:30) | Son LAS cinco y cuarto (5:15)',
    },
    {
      title: 'Age: "Tener" Not "Ser"',
      content: 'English says "I am 25 years old." Spanish says "I HAVE 25 years": Tengo veinticinco años. Using "soy" (I am) with age is one of the most common beginner mistakes. The Ñ in "años" = "ny" sound from L1.1.',
      example: '"I am 30" = Tengo treinta años (NOT "Soy treinta")',
      reviewFrom: 'L1.1',
    },
  ],
  flashcardGroups: [
    { key: 'numbers', label: 'Numbers', audioKeys: ['cero', 'uno', 'dos', 'tres', 'cuatro', 'cinco', 'seis', 'siete', 'ocho', 'nueve', 'diez', 'once', 'quince', 'veinte', 'treinta', 'cuarenta', 'cincuenta', 'cien'] },
    { key: 'time', label: 'Time & Age', audioKeys: ['que-hora-es', 'es-la-una', 'son-las-dos', 'son-las-tres', 'y-cuarto', 'y-media', 'menos-cuarto', 'medianoche', 'mediodia', 'de-la-manana', 'de-la-tarde', 'de-la-noche', 'cuantos-anos-tienes', 'tengo-veinte-anos'] },
    { key: 'calendar', label: 'Calendar', audioKeys: ['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo', 'enero', 'marzo', 'mayo', 'julio', 'septiembre', 'diciembre', 'cual-es-tu-numero'] },
  ],
  matchPairs: [
    { left: 'Diez', right: '10' },
    { left: 'Veinticinco', right: '25' },
    { left: 'Cincuenta', right: '50' },
    { left: 'Cien', right: '100' },
    { left: 'Es la una', right: '1:00' },
    { left: 'Son las tres', right: '3:00' },
    { left: 'y media', right: ':30' },
    { left: 'menos cuarto', right: ':45' },
  ],
  matchLabels: { left: 'Spanish', right: 'Number / Time' },
  sortActivities: [
    {
      title: 'Less than 50 vs. More than 50',
      instruction: 'Drag each number to the correct category.',
      buckets: ['Less than 50', 'More than 50'],
      items: [
        { text: 'Quince (15)', bucket: 'Less than 50' },
        { text: 'Treinta (30)', bucket: 'Less than 50' },
        { text: 'Doce (12)', bucket: 'Less than 50' },
        { text: 'Cuarenta y cinco (45)', bucket: 'Less than 50' },
        { text: 'Sesenta (60)', bucket: 'More than 50' },
        { text: 'Ochenta (80)', bucket: 'More than 50' },
        { text: 'Setenta y cinco (75)', bucket: 'More than 50' },
        { text: 'Cien (100)', bucket: 'More than 50' },
      ],
    },
    {
      title: 'Morning vs. Afternoon / Evening',
      instruction: 'Sort each time by morning or afternoon/evening.',
      buckets: ['Morning', 'Afternoon / Evening'],
      items: [
        { text: 'Las ocho de la mañana', bucket: 'Morning' },
        { text: 'Las diez de la mañana', bucket: 'Morning' },
        { text: 'Las siete de la mañana', bucket: 'Morning' },
        { text: 'Las once de la mañana', bucket: 'Morning' },
        { text: 'Las tres de la tarde', bucket: 'Afternoon / Evening' },
        { text: 'Las seis de la tarde', bucket: 'Afternoon / Evening' },
        { text: 'Las nueve de la noche', bucket: 'Afternoon / Evening' },
        { text: 'Las diez de la noche', bucket: 'Afternoon / Evening' },
      ],
    },
    {
      title: 'True or False?',
      instruction: 'Sort each statement as True or False.',
      buckets: ['True', 'False'],
      items: [
        { text: 'Spanish uses "tener" for age', bucket: 'True' },
        { text: 'Numbers 16\u201319 use "dieci-"', bucket: 'True' },
        { text: '"Es la una" is singular', bucket: 'True' },
        { text: 'Days are not capitalized in Spanish', bucket: 'True' },
        { text: '"Menos cuarto" = quarter past', bucket: 'False' },
        { text: '21\u201329 are written as separate words', bucket: 'False' },
        { text: '"Son las una" for 1:00', bucket: 'False' },
        { text: '"Ciento" is used alone for 100', bucket: 'False' },
      ],
    },
  ],
  sortSectionId: 'number-sorting',
  sortTitle: 'Sort the Numbers',
  dialogues: [
    {
      id: 'dialogue-restaurant',
      title: 'Making a Reservation \u2014 At a Restaurant',
      location: 'Restaurant',
      lines: [
        { speaker: 'Cliente', text: 'Buenas tardes. Una mesa para cuatro personas, por favor.', audio: '/audio/L1.3/dialogues/d1-line1.mp3',
          annotations: [{ phrase: 'Buenas tardes', fromLesson: 'L1.2', note: 'Greeting' }, { phrase: 'por favor', fromLesson: 'L1.2', note: 'Polite request' }] },
        { speaker: 'Mesero', text: '\u00bfPara qu\u00e9 hora?', audio: '/audio/L1.3/dialogues/d1-line2.mp3' },
        { speaker: 'Cliente', text: 'Para las ocho de la noche.', audio: '/audio/L1.3/dialogues/d1-line3.mp3' },
        { speaker: 'Mesero', text: 'Perfecto. Mesa para cuatro a las ocho. \u00bfA nombre de qui\u00e9n?', audio: '/audio/L1.3/dialogues/d1-line4.mp3' },
        { speaker: 'Cliente', text: 'A nombre de Ana. Muchas gracias.', audio: '/audio/L1.3/dialogues/d1-line5.mp3',
          annotations: [{ phrase: 'Muchas gracias', fromLesson: 'L1.2', note: 'Thank you very much' }] },
      ],
    },
    {
      id: 'dialogue-plans',
      title: 'Making Plans \u2014 With a Friend',
      location: 'Caf\u00e9',
      lines: [
        { speaker: 'Mar\u00eda', text: 'Hola, Carlos. \u00bfNos vemos el viernes?', audio: '/audio/L1.3/dialogues/d2-line1.mp3',
          annotations: [{ phrase: 'Hola', fromLesson: 'L1.2', note: 'Greeting' }, { phrase: 'Nos vemos', fromLesson: 'L1.2', note: 'See you' }] },
        { speaker: 'Carlos', text: '\u00a1S\u00ed! \u00bfA qu\u00e9 hora?', audio: '/audio/L1.3/dialogues/d2-line2.mp3' },
        { speaker: 'Mar\u00eda', text: '\u00bfA las cuatro de la tarde?', audio: '/audio/L1.3/dialogues/d2-line3.mp3' },
        { speaker: 'Carlos', text: 'Perfecto. El viernes a las cuatro. \u00a1Hasta luego!', audio: '/audio/L1.3/dialogues/d2-line4.mp3',
          annotations: [{ phrase: 'Hasta luego', fromLesson: 'L1.2', note: 'See you later' }] },
      ],
    },
  ],
  dialogueDescription: 'Listen to real conversations where numbers and time are used naturally \u2014 making reservations and plans with friends.',
  culturalNotes: [
    {
      title: 'Time is Flexible \u2014 "La Hora Latina"',
      content: 'In many Spanish-speaking countries, arriving 15\u201330 minutes "late" is normal for social events. "A las ocho" might really mean 8:15\u20138:30. However, for business and medical appointments, punctuality IS expected. When in doubt, ask: "\u00bfEn punto?" (sharp/exactly?).',
    },
    {
      title: 'Monday Starts the Week',
      content: 'In Spanish-speaking countries and most of Europe, the week starts on Monday (lunes), not Sunday. Calendars reflect this. Also, days and months are NEVER capitalized in Spanish: lunes, enero \u2014 not Lunes, Enero.',
    },
    {
      title: 'Phone Numbers \u2014 Digit by Digit',
      content: 'Phone numbers are typically said one digit at a time: "cinco, tres, dos, ocho, uno..." Some people group them in pairs: "cincuenta y tres, veintiocho, diez..." There is no standard \u2014 both ways are correct.',
    },
  ],
  culturalGradient: 'from-amber-50 to-orange-50',
  quiz: [
    { id: 1, type: 'mc', text: "Your friend asks '\u00bfCu\u00e1ntos a\u00f1os tienes?' You are 28. Which is correct?", options: ['Soy veintiocho a\u00f1os', 'Tengo veintiocho a\u00f1os', 'Estoy veintiocho', 'Mi edad es veintiocho'], answer: 1 },
    { id: 2, type: 'mc', text: 'Numbers 21\u201329 are one word. What happens from 30 onward?', options: ['Also one word', "Three words with 'y' (treinta y uno)", 'They drop the ones digit', 'They use a hyphen'], answer: 1 },
    { id: 3, type: 'mc', text: 'It is 1:45 PM. Which form is correct?', options: ['Es la una y cuarenta y cinco', 'Son las una menos cuarto', 'Son las dos menos cuarto', 'Es la una menos cuarto'], answer: 0 },
    { id: 4, type: 'fill', text: "Complete: 'Me llamo Ana. Soy de Colombia. ___ veinticinco a\u00f1os.'", answer: 'Tengo' },
    { id: 5, type: 'mc', text: 'How do you say 58 in Spanish?', options: ['Cinco ocho', 'Cincuenta y ocho', 'Cincoenta ocho', 'Cincuenta ocho'], answer: 1 },
    { id: 6, type: 'tf', text: "At noon you say 'Son las doce del mediod\u00eda.'", answer: false },
    { id: 7, type: 'mc', text: "A student writes 'Son las una y media.' What is the error?", options: ["Should be 'y cuarto'", "'Una' needs 'Es la' not 'Son las'", "Should use 'menos'", "'Media' should be 'treinta'"], answer: 1 },
    { id: 8, type: 'fill', text: "The clock shows 8:30. Complete: 'Son las ocho y ___'", answer: 'media' },
    { id: 9, type: 'mc', text: 'Which number is written INCORRECTLY?', options: ['Veinticuatro (24)', 'Treinta y seis (36)', 'Diecisiete (17)', 'Cuarenta uno (41)'], answer: 3 },
    { id: 10, type: 'fill', text: "9:15 AM. Complete: 'Son las nueve y ___ de la ma\u00f1ana'", answer: 'cuarto' },
    { id: 11, type: 'tf', text: "'Cien' and 'ciento' both mean 100 and are interchangeable.", answer: false },
    { id: 12, type: 'mc', text: "'Son ochenta y cinco pesos.' How much do you owe?", options: ['58 pesos', '80 pesos', '85 pesos', '850 pesos'], answer: 2 },
    { id: 13, type: 'fill', text: 'The first day of the week in Spanish-speaking countries is ___ (Monday).', answer: 'lunes' },
    { id: 14, type: 'mc', text: "'Mi clase empieza a las diez y cuarto de la ma\u00f1ana.' What time?", options: ['10:40 AM', '10:15 AM', '10:45 AM', '4:10 AM'], answer: 1 },
    { id: 15, type: 'tf', text: "'Tengo treinta y un a\u00f1os' means 31 years old.", answer: true },
  ],
  uniqueActivity: {
    id: 'NumberDictationL13',
    sectionId: 'number-dictation',
    sectionColor: 'bg-amber-50/40',
    sectionBorder: 'border-amber-100',
  },
  sectionColors: {
    'prior-knowledge': { bg: 'bg-indigo-50/30', border: 'border-indigo-100' },
    objectives: { bg: 'bg-white', border: '' },
    'personalized-context': { bg: 'bg-violet-50/30', border: 'border-violet-100' },
    'numbers-0-20': { bg: 'bg-amber-50/30', border: 'border-amber-100' },
    'numbers-21-100': { bg: 'bg-orange-50/30', border: 'border-orange-100' },
    'telling-time': { bg: 'bg-teal-50/30', border: 'border-teal-100' },
    'age-calendar': { bg: 'bg-rose-50/30', border: 'border-rose-100' },
    'pronunciation-tips': { bg: 'bg-yellow-50/30', border: 'border-yellow-100' },
    'pronunciation-practice': { bg: 'bg-blue-50/30', border: 'border-blue-200' },
    flashcards: { bg: 'bg-amber-50/30', border: 'border-amber-100' },
    'matching-game': { bg: 'bg-teal-50/30', border: 'border-teal-100' },
    'number-sorting': { bg: 'bg-blue-50/30', border: 'border-blue-100' },
    dialogues: { bg: 'bg-purple-50/30', border: 'border-purple-100' },
    cultural: { bg: 'bg-rose-50/30', border: 'border-rose-100' },
    'number-dictation': { bg: 'bg-amber-50/40', border: 'border-amber-100' },
    'knowledge-check': { bg: 'bg-indigo-50/40', border: 'border-indigo-100' },
  },
}

export const L13PhraseByAudio = phraseByAudio

// Number Dictation rounds — student hears a number/time and types it
export const NUMBER_DICTATION_ROUNDS = [
  { audio: 'siete', display: '7', answer: '7', hint: 'A single digit' },
  { audio: 'quince', display: '15', answer: '15', hint: 'A teen number' },
  { audio: 'veinticinco', display: '25', answer: '25', hint: 'A twenties number' },
  { audio: 'treinta', display: '30', answer: '30', hint: 'A round tens number' },
  { audio: 'cuarenta', display: '40', answer: '40', hint: 'A round tens number' },
  { audio: 'sesenta', display: '60', answer: '60', hint: 'A round tens number' },
  { audio: 'ochenta', display: '80', answer: '80', hint: 'A round tens number' },
  { audio: 'cien', display: '100', answer: '100', hint: 'The biggest number in this lesson' },
  { audio: 'es-la-una', display: '1:00', answer: '1:00', hint: 'A time (use : format)' },
  { audio: 'son-las-tres', display: '3:00', answer: '3:00', hint: 'A time (use : format)' },
]
