import type { LessonData } from '@/lib/types/lesson'

const PHRASES = [
  // Personal Info
  { spanish: 'Me llamo', english: 'My name is', pronunciation: 'meh YAH-moh', category: 'personal_info', audio: 'me-llamo' },
  { spanish: '¿Cómo te llamas?', english: 'What is your name?', pronunciation: 'KOH-moh teh YAH-mahs', category: 'personal_info', audio: 'como-te-llamas' },
  { spanish: 'Soy de', english: 'I am from', pronunciation: 'soh-ee deh', category: 'personal_info', audio: 'soy-de' },
  { spanish: 'Tengo __ años', english: 'I am __ years old', pronunciation: 'TEHN-goh __ AH-nyos', category: 'personal_info', audio: 'tengo-anos' },
  { spanish: 'Vivo en', english: 'I live in', pronunciation: 'VEE-voh en', category: 'personal_info', audio: 'vivo-en' },
  // Asking Questions
  { spanish: '¿De dónde eres?', english: 'Where are you from?', pronunciation: 'deh DON-deh EH-res', category: 'asking_questions', audio: 'de-donde-eres' },
  { spanish: '¿Cuántos años tienes?', english: 'How old are you?', pronunciation: 'KWAN-tos AH-nyos TYEH-nes', category: 'asking_questions', audio: 'cuantos-anos-tienes' },
  { spanish: '¿Eres estudiante?', english: 'Are you a student?', pronunciation: 'EH-res es-too-DYAN-teh', category: 'asking_questions', audio: 'eres-estudiante' },
  { spanish: '¿Dónde vives?', english: 'Where do you live?', pronunciation: 'DON-deh VEE-ves', category: 'asking_questions', audio: 'donde-vives' },
  { spanish: '¿Cuál es tu nacionalidad?', english: 'What is your nationality?', pronunciation: 'KWAL es too nah-syo-nah-lee-DAD', category: 'asking_questions', audio: 'cual-es-tu-nacionalidad' },
  // Nationalities
  { spanish: 'Yo soy colombiano', english: 'I am Colombian', pronunciation: 'yoh SOY koh-lom-BEE-ah-no', category: 'nationalities', audio: 'yo-soy-colombiano' },
  { spanish: 'Él es mexicano', english: 'He is Mexican', pronunciation: 'el es meh-hee-KAH-no', category: 'nationalities', audio: 'el-es-mexicano' },
  { spanish: 'Ella es española', english: 'She is Spanish', pronunciation: 'EH-yah es es-pah-NYOH-lah', category: 'nationalities', audio: 'ella-es-espanola' },
  { spanish: 'Ellos son americanos', english: 'They are American', pronunciation: 'EH-yos son ah-meh-ree-KAH-nos', category: 'nationalities', audio: 'ellos-son-americanos' },
  { spanish: 'Nosotros somos argentinos', english: 'We are Argentine', pronunciation: 'noh-SOH-tros SOH-mos ar-hen-TEE-nos', category: 'nationalities', audio: 'nosotros-somos-argentinos' },
  { spanish: 'Soy francés', english: 'I am French', pronunciation: 'soy fran-SEHS', category: 'nationalities', audio: 'soy-frances' },
  { spanish: '¿Eres italiano?', english: 'Are you Italian?', pronunciation: 'EH-res ee-ta-lee-AH-no', category: 'nationalities', audio: 'eres-italiano' },
  { spanish: 'Ella es alemana', english: 'She is German', pronunciation: 'EH-yah es ah-leh-MAH-nah', category: 'nationalities', audio: 'ella-es-alemana' },
  { spanish: 'Él es japonés', english: 'He is Japanese', pronunciation: 'el es ha-po-NES', category: 'nationalities', audio: 'el-es-japones' },
  { spanish: 'Soy canadiense', english: 'I am Canadian', pronunciation: 'soy ka-na-DYEN-se', category: 'nationalities', audio: 'soy-canadiense' },
  // Professions
  { spanish: 'Soy estudiante', english: 'I am a student', pronunciation: 'soy es-too-DYAN-teh', category: 'professions', audio: 'soy-estudiante' },
  { spanish: 'Soy doctor', english: 'I am a doctor', pronunciation: 'soy dok-TOR', category: 'professions', audio: 'soy-doctor' },
  { spanish: 'Es enfermera', english: 'She is a nurse', pronunciation: 'es en-fer-MEH-rah', category: 'professions', audio: 'es-enfermera' },
  { spanish: 'Soy ingeniero', english: 'I am an engineer', pronunciation: 'soy een-heh-NYEH-roh', category: 'professions', audio: 'soy-ingeniero' },
  { spanish: 'Es profesor', english: 'He is a teacher', pronunciation: 'es pro-feh-SOR', category: 'professions', audio: 'es-profesor' },
  { spanish: 'Soy artista', english: 'I am an artist', pronunciation: 'soy ar-TEES-tah', category: 'professions', audio: 'soy-artista' },
  { spanish: 'Es abogado', english: 'He is a lawyer', pronunciation: 'es ah-boh-GAH-doh', category: 'professions', audio: 'es-abogado' },
  { spanish: 'Soy músico', english: 'I am a musician', pronunciation: 'soy MOO-see-ko', category: 'professions', audio: 'soy-musico' },
  { spanish: 'Es carpintero', english: 'He is a carpenter', pronunciation: 'es kar-peen-TEH-roh', category: 'professions', audio: 'es-carpintero' },
  { spanish: 'Soy chef', english: 'I am a chef', pronunciation: 'soy SHEF', category: 'professions', audio: 'soy-chef' },
]

const phraseByAudio: Record<string, (typeof PHRASES)[number]> = {}
PHRASES.forEach((p) => { phraseByAudio[p.audio] = p })

export const L15Data: LessonData = {
  id: 'L1.5',
  hero: {
    lessonId: 'L1.5',
    title: 'Introducing Yourself',
    subtitle: 'Name, age, nationality & where you\'re from',
    description: 'Learn how to introduce yourself, including your name, age, nationality, and where you are from.',
    image: '/images/L1.5/hero-introductions.png',
    gradient: 'from-rose-800/65 via-pink-700/55 to-red-700/65',
    accentColor: 'rose-200',
  },
  priorKnowledge: [
    {
      fromLesson: 'L1.1',
      label: 'Spanish Alphabet',
      detail: 'Understanding pronunciation and spelling of names.',
    },
    {
      fromLesson: 'L1.2',
      label: 'Greetings',
      detail: 'Building on polite expressions for introductions.',
    },
  ],
  sectionTransitions: [
    { afterSection: 'personal_info', text: 'Now that you can share basic personal details, let\'s explore how to ask questions about others.' },
    { afterSection: 'asking_questions', text: 'You\'ve mastered asking questions! Next, let\'s learn about nationalities.' },
    { afterSection: 'nationalities', text: 'Great job! Let\'s move on to discussing professions.' },
    { afterSection: 'professions', text: 'You\'ve got the basics of professions down. Time for some dialogues to practice your skills!' },
    { afterSection: 'dialogues', text: 'These dialogues were a good practice. Let’s test your knowledge with the quiz!' },
  ],
  personalizedVocab: [
    { spanish: 'nombre', english: 'name' },
    { spanish: 'edad', english: 'age' },
    { spanish: 'nacionalidad', english: 'nationality' },
    { spanish: 'profesión', english: 'profession' },
    { spanish: 'vivir', english: 'to live' },
    { spanish: 'ser', english: 'to be' },
  ],
  pronunciationChallenges: [
    { spanish: '¿Cuántos años tienes?', pronunciation: 'KWAN-tos AH-nyos TYEH-nes', english: 'How old are you?', audio: 'cuantos-anos-tienes', tip: 'Focus on the ñ sound, similar to \'ny\' in \'canyon\'.' },
    { spanish: 'Soy ingeniero', pronunciation: 'soy een-heh-NYEH-roh', english: 'I am an engineer', audio: 'soy-ingeniero', tip: 'Pay attention to the \'j\' sound, similar to \'h\' in \'hello\'.' },
    { spanish: 'Ella es española', pronunciation: 'EH-yah es es-pah-NYOH-lah', english: 'She is Spanish', audio: 'ella-es-espanola', tip: 'Remember the ñ sound, which is unique to Spanish.' },
    { spanish: 'Soy canadiense', pronunciation: 'soy ka-na-DYEN-se', english: 'I am Canadian', audio: 'soy-canadiense', tip: 'Practice the \'d\' sound, which is softer in Spanish.' },
    { spanish: '¿De dónde eres?', pronunciation: 'deh DON-deh EH-res', english: 'Where are you from?', audio: 'de-donde-eres', tip: 'Remember that \'d\' between vowels can sound like \'th\'.' },
    { spanish: 'Es enfermera', pronunciation: 'es en-fer-MEH-rah', english: 'She is a nurse', audio: 'es-enfermera', tip: 'Focus on rolling the \'r\' sound slightly.' },
  ],
  objectives: [
    { icon: '👤', title: 'Introduce Yourself', desc: 'Learn to share your name, age, and where you\'re from.' },
    { icon: '❓', title: 'Ask Questions', desc: 'Master basic questions to learn about others.' },
    { icon: '🌍', title: 'Nationalities', desc: 'Identify and express different nationalities.' },
    { icon: '💼', title: 'Discuss Professions', desc: 'Talk about various professions clearly.' },
  ],
  sections: [
    { id: 'welcome', label: 'Welcome' },
    { id: 'prior-knowledge', label: 'What You Already Know' },
    { id: 'objectives', label: 'What You\'ll Learn' },
    { id: 'personalized-context', label: 'See in YOUR Context' },
    { id: 'personal_info', label: 'Personal Information' },
    { id: 'asking_questions', label: 'Asking Questions' },
    { id: 'nationalities', label: 'Nationalities' },
    { id: 'professions', label: 'Professions' },
    { id: 'pronunciation-tips', label: 'Pronunciation Tips' },
    { id: 'pronunciation-practice', label: 'Pronunciation Practice' },
    { id: 'flashcards', label: 'Flashcards' },
    { id: 'matching-game', label: 'Matching Game' },
    { id: 'introductions-sorting', label: 'Introducing Yourself Sorting' },
    { id: 'dialogues', label: 'Dialogues' },
    { id: 'cultural', label: 'Cultural Insights' },
    { id: 'knowledge-check', label: 'Knowledge Check' },
  ],
  audioBase: '/audio/L1.5/phrases',
  phraseSections: [
    {
      id: 'personal_info',
      title: 'Personal Information',
      description: 'Essential phrases for sharing your basic details.',
      tabs: [
        { label: 'Names & Ages', color: 'amber', phrases: PHRASES.filter((_p, i) => [0, 1, 2, 3].includes(i)) },
        { label: 'Locations', color: 'blue', phrases: PHRASES.filter((_p, i) => [4, 5].includes(i)) },
      ],
    },
    {
      id: 'asking_questions',
      title: 'Asking Questions',
      description: 'Learn how to ask about others\' information.',
      tabs: [
        { label: 'Basic Questions', color: 'orange', phrases: PHRASES.filter((_p, i) => [6, 7, 8, 9].includes(i)) },
      ],
    },
    {
      id: 'nationalities',
      title: 'Nationalities',
      description: 'Identify and express nationalities.',
      tabs: [
        { label: 'Common Nationalities', color: 'rose', phrases: PHRASES.filter((_p, i) => [10, 11, 12, 13].includes(i)) },
      ],
    },
    {
      id: 'professions',
      title: 'Professions',
      description: 'Discuss various professions.',
      tabs: [
        { label: 'Professions', color: 'purple', phrases: PHRASES.filter((_p, i) => [20, 21, 22, 23].includes(i)) },
      ],
    },
  ],
  pronunciationTips: [
    {
      title: 'The Ñ Sound',
      content: 'The \'ñ\' in Spanish is pronounced like the \'ny\' in \'canyon\'.',
      example: 'española (es-pah-NYOH-lah), año (AH-nyoh)',
      reviewFrom: 'L1.1',
    },
    {
      title: 'Soft D Sound',
      content: 'Between vowels, \'d\' can sound like \'th\' as in \'this\'.',
      example: 'dónde (DON-deh), cada (CAH-tha)',
      reviewFrom: 'L1.1',
    },
    {
      title: 'Rolling R',
      content: 'The \'r\' is slightly rolled, especially at the start of words.',
      example: 'rápido (RAH-pee-doh), carro (KAH-roh)',
      reviewFrom: 'L1.1',
    },
  ],
  flashcardGroups: [
    { key: 'personal-info', label: 'Personal Info', audioKeys: ['me-llamo', 'como-te-llamas', 'soy-de', 'tengo-anos'] },
    { key: 'asking-questions', label: 'Questions', audioKeys: ['de-donde-eres', 'cuantos-anos-tienes', 'eres-estudiante'] },
    { key: 'nationalities', label: 'Nationalities', audioKeys: ['yo-soy-colombiano', 'el-es-mexicano', 'ella-es-espanola'] },
  ],
  matchPairs: [
    { left: 'Me llamo', right: 'My name is' },
    { left: '¿Cómo te llamas?', right: 'What is your name?' },
    { left: 'Soy de', right: 'I am from' },
    { left: 'Tengo __ años', right: 'I am __ years old' },
    { left: '¿De dónde eres?', right: 'Where are you from?' },
    { left: '¿Cuántos años tienes?', right: 'How old are you?' },
    { left: 'Yo soy colombiano', right: 'I am Colombian' },
    { left: 'Soy estudiante', right: 'I am a student' },
  ],
  matchLabels: { left: 'Spanish', right: 'English' },
  sortActivities: [
    {
      title: 'Identify Professions',
      instruction: 'Sort these professions into \'Medical\' or \'Arts\'.',
      buckets: ['Medical', 'Arts'],
      items: [
        { text: 'Doctor', bucket: 'Medical' },
        { text: 'Nurse', bucket: 'Medical' },
        { text: 'Chef', bucket: 'Arts' },
        { text: 'Musician', bucket: 'Arts' },
        { text: 'Artist', bucket: 'Arts' },
        { text: 'Lawyer', bucket: 'Medical' },
        { text: 'Student', bucket: 'Arts' },
        { text: 'Engineer', bucket: 'Medical' },
        { text: 'Carpenter', bucket: 'Arts' },
        { text: 'Teacher', bucket: 'Arts' },
      ],
    },
    {
      title: 'Nationality Sort',
      instruction: 'Sort these phrases into \'American\' or \'European\'.',
      buckets: ['American', 'European'],
      items: [
        { text: 'Colombiano', bucket: 'American' },
        { text: 'Mexicano', bucket: 'American' },
        { text: 'Española', bucket: 'European' },
        { text: 'Argentino', bucket: 'American' },
        { text: 'Francés', bucket: 'European' },
        { text: 'Italiano', bucket: 'European' },
        { text: 'Alemana', bucket: 'European' },
        { text: 'Japonés', bucket: 'European' },
        { text: 'Canadiense', bucket: 'American' },
        { text: 'Americano', bucket: 'American' },
      ],
    },
  ],
  sortSectionId: 'introductions-sorting',
  sortTitle: 'Introducing Yourself Sorting',
  dialogues: [
    {
      id: 'dialogue-1',
      title: 'Introducing Yourself — Medellín',
      location: 'Medellín',
      lines: [
        { speaker: 'Juan', text: 'Hola, me llamo Juan. ¿Cómo te llamas?', audio: '/audio/L1.5/phrases/d1-line1.mp3',
          annotations: [{ phrase: 'me llamo', fromLesson: 'L1.2', note: 'Used to introduce oneself.' }] },
        { speaker: 'Ana', text: 'Hola Juan, me llamo Ana. Soy de Medellín.', audio: '/audio/L1.5/phrases/d1-line2.mp3',
          annotations: [{ phrase: 'Soy de', fromLesson: 'L1.2', note: 'Indicating origin.' }] },
        { speaker: 'Juan', text: '¿Cuántos años tienes?', audio: '/audio/L1.5/phrases/d1-line3.mp3',
          annotations: [{ phrase: 'Cuántos años', fromLesson: 'L1.2', note: 'Asking for age.' }] },
        { speaker: 'Ana', text: 'Tengo veinte años. ¿Y tú?', audio: '/audio/L1.5/phrases/d1-line4.mp3',
          annotations: [{ phrase: 'Tengo', fromLesson: 'L1.2', note: 'Using \'tener\' for age.' }] },
        { speaker: 'Juan', text: 'Yo tengo veinticinco años. Soy estudiante.', audio: '/audio/L1.5/phrases/d1-line5.mp3',
          annotations: [{ phrase: 'Soy', fromLesson: 'L1.2', note: 'Describing profession/status.' }] },
        { speaker: 'Ana', text: '¡Qué bien! Yo también soy estudiante.', audio: '/audio/L1.5/phrases/d1-line6.mp3',
          annotations: [{ phrase: 'También', fromLesson: 'L1.2', note: 'Expressing agreement.' }] },
      ],
    },
    {
      id: 'dialogue-2',
      title: 'Meeting at a Café — San Juan',
      location: 'San Juan',
      lines: [
        { speaker: 'Carlos', text: 'Buenos días, soy Carlos. ¿Eres de aquí?', audio: '/audio/L1.5/phrases/d2-line1.mp3',
          annotations: [{ phrase: 'Buenos días', fromLesson: 'L1.2', note: 'Morning greeting.' }] },
        { speaker: 'Maria', text: 'Hola, no, soy de España. ¿Y tú?', audio: '/audio/L1.5/phrases/d2-line2.mp3',
          annotations: [{ phrase: 'Hola', fromLesson: 'L1.2', note: 'Standard greeting.' }] },
        { speaker: 'Carlos', text: 'Soy de Puerto Rico. ¿Qué haces aquí?', audio: '/audio/L1.5/phrases/d2-line3.mp3',
          annotations: [{ phrase: 'Soy de', fromLesson: 'L1.2', note: 'Expressing origin.' }] },
        { speaker: 'Maria', text: 'Estoy de vacaciones. ¿Eres estudiante?', audio: '/audio/L1.5/phrases/d2-line4.mp3',
          annotations: [{ phrase: 'Estudiante', fromLesson: 'L1.2', note: 'Discussing profession.' }] },
        { speaker: 'Carlos', text: 'Sí, estudio en la universidad. ¿Y tú?', audio: '/audio/L1.5/phrases/d2-line5.mp3',
          annotations: [{ phrase: 'Universidad', fromLesson: 'L1.2', note: 'Higher education context.' }] },
        { speaker: 'Maria', text: 'Soy profesora de español.', audio: '/audio/L1.5/phrases/d2-line6.mp3',
          annotations: [{ phrase: 'Profesora', fromLesson: 'L1.2', note: 'Discussing profession.' }] },
      ],
    },
  ],
  dialogueDescription: 'These dialogues demonstrate how to introduce oneself and ask about personal information in casual and semi-formal settings.',
  culturalNotes: [
    {
      title: 'Name Customs in Spanish Cultures',
      content: 'In many Spanish-speaking countries, it\'s common to have two last names: one from the father and one from the mother. This reflects family heritage and is used in formal documents.',
    },
    {
      title: 'Nicknames',
      content: 'Nicknames are widely used in Spanish-speaking cultures. They can be derived from one\'s actual name, such as \'Pepe\' for \'José\', or based on physical characteristics or personality traits.',
    },
    {
      title: 'Formal vs. Informal Introductions',
      content: 'In casual settings, introductions are often informal, using first names. In more formal contexts, such as business meetings, it\'s common to use full names and titles.',
    },
  ],
  culturalGradient: 'from-rose-50 to-pink-50',
  quiz: [
    { id: 1, type: 'mc', text: 'Which phrase means \'I am from\'?', options: ['Soy de', 'Yo tengo', 'Me llamo', 'Estoy de'], answer: 0 },
    { id: 2, type: 'tf', text: 'True or False: \'Soy estudiante\' means \'I am a student\'', answer: true },
    { id: 3, type: 'fill', text: 'Complete: \'Yo ___ mexicano\' (am)', answer: 'soy' },
    { id: 4, type: 'mc', text: 'What is the correct response to \'¿Cómo te llamas?\'?', options: ['Soy de México', 'Me llamo Ana', 'Tengo veinte años', 'Soy estudiante'], answer: 1 },
    { id: 5, type: 'tf', text: 'True or False: \'Él es profesor\' means \'He is a teacher\'', answer: true },
    { id: 6, type: 'mc', text: 'Which nationality is \'japonés\'?', options: ['Japanese', 'French', 'Italian', 'American'], answer: 0 },
    { id: 7, type: 'fill', text: 'Complete: \'Ella es ___\' (Spanish)', answer: 'española' },
    { id: 8, type: 'mc', text: 'Which phrase asks \'Where are you from?\'', options: ['¿Cuántos años tienes?', '¿Dónde vives?', '¿De dónde eres?', '¿Cuál es tu nacionalidad?'], answer: 2 },
    { id: 9, type: 'tf', text: 'True or False: \'Soy artista\' means \'I am an artist\'', answer: true },
    { id: 10, type: 'fill', text: 'Complete: \'Yo ___ veinte años\' (have)', answer: 'tengo' },
    { id: 11, type: 'mc', text: 'Which phrase means \'She is German\'?', options: ['Ella es alemana', 'Él es alemán', 'Ella es francesa', 'Ella es española'], answer: 0 },
    { id: 12, type: 'tf', text: 'True or False: \'Soy de España\' means \'I am from Spain\'', answer: true },
    { id: 13, type: 'mc', text: 'Which profession is \'enfermera\'?', options: ['Nurse', 'Engineer', 'Artist', 'Teacher'], answer: 0 },
    { id: 14, type: 'fill', text: 'Complete: \'Yo ___ Carlos\' (am)', answer: 'soy' },
    { id: 15, type: 'mc', text: 'Which phrase means \'He is Mexican\'?', options: ['Él es español', 'Él es francés', 'Él es japonés', 'Él es mexicano'], answer: 3 },
  ],
  sectionColors: {
    'prior-knowledge': { bg: 'bg-indigo-50/30', border: 'border-indigo-100' },
    'objectives': { bg: 'bg-white', border: '' },
    'personalized-context': { bg: 'bg-violet-50/30', border: 'border-violet-100' },
    'personal_info': { bg: 'bg-rose-50/30', border: 'border-rose-100' },
    'asking_questions': { bg: 'bg-pink-50/30', border: 'border-pink-100' },
    'nationalities': { bg: 'bg-red-50/30', border: 'border-red-100' },
    'professions': { bg: 'bg-blue-50/30', border: 'border-blue-100' },
    'pronunciation-tips': { bg: 'bg-yellow-50/30', border: 'border-yellow-100' },
    'pronunciation-practice': { bg: 'bg-blue-50/30', border: 'border-blue-200' },
    'flashcards': { bg: 'bg-rose-50/30', border: 'border-rose-100' },
    'matching-game': { bg: 'bg-emerald-50/30', border: 'border-emerald-100' },
    'introductions-sorting': { bg: 'bg-blue-50/30', border: 'border-blue-100' },
    'dialogues': { bg: 'bg-purple-50/30', border: 'border-purple-100' },
    'cultural': { bg: 'bg-rose-50/30', border: 'border-rose-100' },
    'knowledge-check': { bg: 'bg-indigo-50/40', border: 'border-indigo-100' },
  },
}

// Export phrase lookup for flashcard component
export const L15PhraseByAudio = phraseByAudio
