import type { LessonData } from '@/lib/types/lesson'

const PHRASES = [
  // Immediate Family
  { spanish: 'La mamá / La madre', english: 'Mom / Mother', pronunciation: 'lah mah-MAH / lah MAH-dreh', category: 'immediate', audio: 'la-mama' },
  { spanish: 'El papá / El padre', english: 'Dad / Father', pronunciation: 'ehl pah-PAH / ehl PAH-dreh', category: 'immediate', audio: 'el-papa' },
  { spanish: 'El hermano', english: 'Brother', pronunciation: 'ehl ehr-MAH-noh', category: 'immediate', audio: 'el-hermano' },
  { spanish: 'La hermana', english: 'Sister', pronunciation: 'lah ehr-MAH-nah', category: 'immediate', audio: 'la-hermana' },
  { spanish: 'El hijo', english: 'Son', pronunciation: 'ehl EE-hoh', category: 'immediate', audio: 'el-hijo' },
  { spanish: 'La hija', english: 'Daughter', pronunciation: 'lah EE-hah', category: 'immediate', audio: 'la-hija' },
  { spanish: 'El esposo / El marido', english: 'Husband', pronunciation: 'ehl ehs-POH-soh / ehl mah-REE-doh', category: 'immediate', audio: 'el-esposo' },
  { spanish: 'La esposa', english: 'Wife', pronunciation: 'lah ehs-POH-sah', category: 'immediate', audio: 'la-esposa' },
  { spanish: 'El bebé', english: 'Baby', pronunciation: 'ehl beh-BEH', category: 'immediate', audio: 'el-bebe' },
  // Extended Family
  { spanish: 'El abuelo', english: 'Grandfather', pronunciation: 'ehl ah-BWEH-loh', category: 'extended', audio: 'el-abuelo' },
  { spanish: 'La abuela', english: 'Grandmother', pronunciation: 'lah ah-BWEH-lah', category: 'extended', audio: 'la-abuela' },
  { spanish: 'El tío', english: 'Uncle', pronunciation: 'ehl TEE-oh', category: 'extended', audio: 'el-tio' },
  { spanish: 'La tía', english: 'Aunt', pronunciation: 'lah TEE-ah', category: 'extended', audio: 'la-tia' },
  { spanish: 'El primo', english: 'Cousin (male)', pronunciation: 'ehl PREE-moh', category: 'extended', audio: 'el-primo' },
  { spanish: 'La prima', english: 'Cousin (female)', pronunciation: 'lah PREE-mah', category: 'extended', audio: 'la-prima' },
  { spanish: 'El sobrino', english: 'Nephew', pronunciation: 'ehl soh-BREE-noh', category: 'extended', audio: 'el-sobrino' },
  { spanish: 'La sobrina', english: 'Niece', pronunciation: 'lah soh-BREE-nah', category: 'extended', audio: 'la-sobrina' },
  { spanish: 'El nieto', english: 'Grandson', pronunciation: 'ehl nee-EH-toh', category: 'extended', audio: 'el-nieto' },
  { spanish: 'La nieta', english: 'Granddaughter', pronunciation: 'lah nee-EH-tah', category: 'extended', audio: 'la-nieta' },
  // Describing Family
  { spanish: 'Mi familia', english: 'My family', pronunciation: 'mee fah-MEE-lee-ah', category: 'describing', audio: 'mi-familia' },
  { spanish: 'Mi mamá se llama...', english: 'My mom\'s name is...', pronunciation: 'mee mah-MAH seh YAH-mah', category: 'describing', audio: 'mi-mama-se-llama' },
  { spanish: 'Tengo dos hermanos', english: 'I have two siblings', pronunciation: 'TEHN-goh dohs ehr-MAH-nohs', category: 'describing', audio: 'tengo-dos-hermanos' },
  { spanish: 'Soy hijo/a único/a', english: 'I am an only child', pronunciation: 'soy EE-hoh OO-nee-koh', category: 'describing', audio: 'soy-hijo-unico' },
  { spanish: 'Vivimos juntos', english: 'We live together', pronunciation: 'bee-BEE-mohs HOON-tohs', category: 'describing', audio: 'vivimos-juntos' },
  { spanish: 'Mi hermano es mayor', english: 'My brother is older', pronunciation: 'mee ehr-MAH-noh ehs mah-YOHR', category: 'describing', audio: 'mi-hermano-es-mayor' },
  { spanish: 'Mi hermana es menor', english: 'My sister is younger', pronunciation: 'mee ehr-MAH-nah ehs meh-NOHR', category: 'describing', audio: 'mi-hermana-es-menor' },
  // Possessives & Key Phrases
  { spanish: 'Mi / Mis', english: 'My (singular / plural)', pronunciation: 'mee / mees', category: 'possessive', audio: 'mi-mis' },
  { spanish: 'Tu / Tus', english: 'Your (singular / plural)', pronunciation: 'too / toos', category: 'possessive', audio: 'tu-tus' },
  { spanish: 'Su / Sus', english: 'His/Her/Their (sing. / pl.)', pronunciation: 'soo / soos', category: 'possessive', audio: 'su-sus' },
  { spanish: 'Nuestro/a', english: 'Our', pronunciation: 'NWEHS-troh / NWEHS-trah', category: 'possessive', audio: 'nuestro' },
  { spanish: '¿Tienes hermanos?', english: 'Do you have siblings?', pronunciation: 'tee-EH-nehs ehr-MAH-nohs', category: 'possessive', audio: 'tienes-hermanos' },
  { spanish: '¿Cómo se llama tu mamá?', english: 'What is your mom\'s name?', pronunciation: 'KOH-moh seh YAH-mah too mah-MAH', category: 'possessive', audio: 'como-se-llama-tu-mama' },
]

const phraseByAudio: Record<string, (typeof PHRASES)[number]> = {}
PHRASES.forEach((p) => { phraseByAudio[p.audio] = p })

export const L16Data: LessonData = {
  id: 'L1.6',
  hero: {
    lessonId: 'L1.6',
    title: 'Family & Relationships',
    subtitle: 'Describing your family & loved ones',
    description: 'Learn to talk about your family, describe relationships, and use possessives. From immediate family to extended relatives — these are the words that connect you to the people who matter most.',
    image: '/images/L1.6/L1.6.jpg',
    gradient: 'from-rose-800/65 via-pink-700/55 to-fuchsia-700/65',
    accentColor: 'rose-200',
  },
  priorKnowledge: [
    {
      fromLesson: 'L1.2',
      label: 'Introductions',
      detail: '"Me llamo..." and "Soy de..." — now use them to introduce family: "Mi mamá se llama María."',
    },
    {
      fromLesson: 'L1.3',
      label: 'Numbers & Age',
      detail: '"Tengo veinte años" — now describe your family: "Tengo dos hermanos," "Mi abuela tiene setenta años."',
    },
    {
      fromLesson: 'L1.1',
      label: 'Gender Patterns',
      detail: 'Remember -O (masculine) / -A (feminine)? hermano/hermana, abuelo/abuela, tío/tía — same pattern!',
    },
  ],
  sectionTransitions: [
    { afterSection: 'immediate', text: 'You know the closest family members! Let\'s expand to the extended family.' },
    { afterSection: 'extended', text: 'Now you can name everyone in the family tree. Let\'s learn to describe your family.' },
    { afterSection: 'describing', text: 'You can talk about your family! Now let\'s learn the possessives — mi, tu, su.' },
    { afterSection: 'possessives', text: 'Great — you own the possessives! Let\'s polish the pronunciation.' },
    { afterSection: 'dialogues', text: 'You just heard real family conversations. Let\'s explore how family works in Hispanic culture.' },
    { afterSection: 'cultural', text: 'Time for the Picture Match challenge — can you identify the right family?' },
    { afterSection: 'picture-match', text: 'Final stretch — let\'s test everything you\'ve learned!' },
  ],
  personalizedVocab: [
    { spanish: 'Mi mamá se llama...', english: 'My mom\'s name is...' },
    { spanish: 'Tengo ___ hermanos', english: 'I have ___ siblings' },
    { spanish: 'Mi familia es grande/pequeña', english: 'My family is big/small' },
    { spanish: 'Vivo con mi...', english: 'I live with my...' },
    { spanish: 'Mi ___ es mayor/menor', english: 'My ___ is older/younger' },
    { spanish: 'Somos ___ en mi familia', english: 'We are ___ in my family' },
  ],
  pronunciationChallenges: [
    { spanish: 'Mi hermano se llama Carlos', pronunciation: 'mee ehr-MAH-noh seh YAH-mah KAR-lohs', english: 'My brother\'s name is Carlos', audio: 'el-hermano', tip: 'Remember: H is silent (L1.1). "Hermano" = ehr-MAH-noh, not "her-MAH-noh."' },
    { spanish: 'Tengo dos hijos', pronunciation: 'TEHN-goh dohs EE-hohs', english: 'I have two children', audio: 'el-hijo', tip: 'The J in "hijos" sounds like English H: EE-hohs. And H is silent!' },
    { spanish: '¿Cómo se llama tu abuela?', pronunciation: 'KOH-moh seh YAH-mah too ah-BWEH-lah', english: 'What is your grandmother\'s name?', audio: 'la-abuela', tip: '"Se llama" from L1.2! LL = "Y" sound in most Latin America.' },
    { spanish: 'Nuestro primo vive en México', pronunciation: 'NWEHS-troh PREE-moh BEE-beh ehn MEH-hee-koh', english: 'Our cousin lives in Mexico', audio: 'el-primo', tip: '"Nuestro" starts with NW — press lips together. V in "vive" sounds like B.' },
    { spanish: 'Mi tía tiene cincuenta años', pronunciation: 'mee TEE-ah tee-EH-neh seen-KWEHN-tah AH-nyohs', english: 'My aunt is fifty years old', audio: 'la-tia', tip: '"Tiene ___ años" from L1.3! "Cincuenta" = seen-KWEHN-tah.' },
    { spanish: 'Sus abuelos son de Colombia', pronunciation: 'soos ah-BWEH-lohs sohn deh koh-LOHM-bee-ah', english: 'Their grandparents are from Colombia', audio: 'el-abuelo', tip: '"Sus" = their/his/her (context tells which). "Son de" = they are from (L1.2).' },
  ],
  objectives: [
    { icon: '👨‍👩‍👧‍👦', title: 'Name Family Members', desc: 'Learn words for parents, siblings, grandparents, aunts, uncles, and cousins' },
    { icon: '💬', title: 'Describe Your Family', desc: 'Talk about family size, ages, and relationships' },
    { icon: '🔑', title: 'Use Possessives', desc: 'Master mi/tu/su to say "my mom," "your brother," "his family"' },
    { icon: '🌎', title: 'Understand Family Culture', desc: 'Learn how family dynamics differ across Hispanic countries' },
  ],
  sections: [
    { id: 'welcome', label: 'Welcome' },
    { id: 'prior-knowledge', label: 'What You Already Know' },
    { id: 'objectives', label: "What You'll Learn" },
    { id: 'personalized-context', label: 'See in YOUR Context' },
    { id: 'immediate', label: 'Immediate Family' },
    { id: 'extended', label: 'Extended Family' },
    { id: 'describing', label: 'Describing Family' },
    { id: 'possessives', label: 'Possessives' },
    { id: 'pronunciation-tips', label: 'Pronunciation Tips' },
    { id: 'pronunciation-practice', label: 'Pronunciation Practice' },
    { id: 'flashcards', label: 'Flashcards' },
    { id: 'matching-game', label: 'Matching Game' },
    { id: 'family-sorting', label: 'Sort the Family' },
    { id: 'dialogues', label: 'Real-World Dialogues' },
    { id: 'cultural', label: 'Cultural Insights' },
    { id: 'picture-match', label: 'Picture Match' },
    { id: 'knowledge-check', label: 'Knowledge Check' },
  ],
  audioBase: '/audio/L1.6/phrases',
  phraseSections: [
    {
      id: 'immediate',
      title: 'Immediate Family',
      description: 'Your closest relatives. Notice the masculine/feminine pattern: hermano (-o) / hermana (-a). This pattern from L1.1 appears everywhere in Spanish!',
      tabs: [
        { label: 'Parents & Spouse', color: 'rose', phrases: PHRASES.filter(p => ['la-mama', 'el-papa', 'el-esposo', 'la-esposa'].includes(p.audio)) },
        { label: 'Siblings & Children', color: 'rose', phrases: PHRASES.filter(p => ['el-hermano', 'la-hermana', 'el-hijo', 'la-hija', 'el-bebe'].includes(p.audio)) },
      ],
    },
    {
      id: 'extended',
      title: 'Extended Family',
      description: 'Beyond parents and siblings — the extended family is especially important in Hispanic culture. Many families live together or very close.',
      tabs: [
        { label: 'Grandparents & Grandchildren', color: 'purple', phrases: PHRASES.filter(p => ['el-abuelo', 'la-abuela', 'el-nieto', 'la-nieta'].includes(p.audio)) },
        { label: 'Aunts, Uncles & Cousins', color: 'purple', phrases: PHRASES.filter(p => ['el-tio', 'la-tia', 'el-primo', 'la-prima', 'el-sobrino', 'la-sobrina'].includes(p.audio)), columns: 2 },
      ],
    },
    {
      id: 'describing',
      title: 'Describing Your Family',
      description: 'Now combine family words with what you already know: names (L1.2), numbers (L1.3), and simple descriptions.',
      tabs: [
        { label: 'Talking About Family', color: 'amber', phrases: PHRASES.filter(p => p.category === 'describing'), columns: 2 },
      ],
    },
    {
      id: 'possessives',
      title: 'Possessives: Mi, Tu, Su',
      description: 'Possessives tell us WHO something belongs to. "Mi mamá" (my mom), "tu hermano" (your brother), "su hija" (his/her daughter). They change for plural: mi → mis, tu → tus, su → sus.',
      tabs: [
        { label: 'Possessives & Phrases', color: 'teal', phrases: PHRASES.filter(p => p.category === 'possessive'), columns: 2 },
      ],
    },
  ],
  pronunciationTips: [
    {
      title: 'The Masculine/Feminine Pattern',
      content: 'Family words follow the -O/-A rule perfectly: hermano/hermana, abuelo/abuela, primo/prima, tío/tía, hijo/hija, nieto/nieta. If you know one, you automatically know the other! Exception: mamá/papá don\'t follow this — they have their own forms (madre/padre are the formal versions).',
      example: '-O (male): hermano, abuelo, primo, tío | -A (female): hermana, abuela, prima, tía',
    },
    {
      title: 'Silent H in "Hijo," "Hermano"',
      content: 'Remember from L1.1 — H is always silent in Spanish. "Hijo" = EE-hoh (not "HEE-hoh"). "Hermano" = ehr-MAH-noh. The J in "hijo" makes the H-like sound, not the H itself!',
      example: 'Hijo = EE-hoh | Hija = EE-hah | Hermano = ehr-MAH-noh',
      reviewFrom: 'L1.1',
    },
    {
      title: 'Possessives: Singular vs Plural',
      content: 'Possessives match the NOUN, not the owner. "Mi hermano" (my brother) → "Mis hermanos" (my brothers). "Tu prima" → "Tus primas." The possessive adds -S when the noun is plural.',
      example: 'Mi hijo / Mis hijos | Tu prima / Tus primas | Su tío / Sus tíos',
    },
    {
      title: '"Se llama" + Family — Building on L1.2',
      content: 'In L1.2 you learned "Me llamo" (My name is). Now add possessives: "Mi mamá se llama Ana" (My mom\'s name is Ana). "Se llama" works for anyone: mi hermano se llama, tu primo se llama, su hija se llama.',
      example: 'Mi mamá se llama Ana | Mi hermano se llama Carlos | ¿Cómo se llama tu papá?',
      reviewFrom: 'L1.2',
    },
  ],
  flashcardGroups: [
    { key: 'immediate', label: 'Immediate Family', audioKeys: ['la-mama', 'el-papa', 'el-hermano', 'la-hermana', 'el-hijo', 'la-hija', 'el-esposo', 'la-esposa', 'el-bebe'] },
    { key: 'extended', label: 'Extended Family', audioKeys: ['el-abuelo', 'la-abuela', 'el-tio', 'la-tia', 'el-primo', 'la-prima', 'el-sobrino', 'la-sobrina', 'el-nieto', 'la-nieta'] },
    { key: 'describing', label: 'Describing & Possessives', audioKeys: ['mi-familia', 'tengo-dos-hermanos', 'mi-mama-se-llama', 'mi-mis', 'tu-tus', 'su-sus', 'nuestro', 'tienes-hermanos'] },
  ],
  matchPairs: [
    { left: 'La mamá', right: 'Mom' },
    { left: 'El hermano', right: 'Brother' },
    { left: 'La abuela', right: 'Grandmother' },
    { left: 'El tío', right: 'Uncle' },
    { left: 'La prima', right: 'Cousin (female)' },
    { left: 'El nieto', right: 'Grandson' },
    { left: 'Mi', right: 'My' },
    { left: 'Su', right: 'His / Her / Their' },
  ],
  matchLabels: { left: 'Spanish', right: 'English' },
  sortActivities: [
    {
      title: 'Immediate vs Extended Family',
      instruction: 'Sort each family member into the correct category.',
      buckets: ['Immediate Family', 'Extended Family'],
      items: [
        { text: 'Mamá', bucket: 'Immediate Family' },
        { text: 'Papá', bucket: 'Immediate Family' },
        { text: 'Hermano', bucket: 'Immediate Family' },
        { text: 'Hijo', bucket: 'Immediate Family' },
        { text: 'Esposa', bucket: 'Immediate Family' },
        { text: 'Abuelo', bucket: 'Extended Family' },
        { text: 'Tía', bucket: 'Extended Family' },
        { text: 'Primo', bucket: 'Extended Family' },
        { text: 'Sobrina', bucket: 'Extended Family' },
        { text: 'Nieto', bucket: 'Extended Family' },
      ],
    },
    {
      title: 'Masculine or Feminine?',
      instruction: 'Sort each family word by gender.',
      buckets: ['Masculine (-o)', 'Feminine (-a)'],
      items: [
        { text: 'Hermano', bucket: 'Masculine (-o)' },
        { text: 'Abuelo', bucket: 'Masculine (-o)' },
        { text: 'Tío', bucket: 'Masculine (-o)' },
        { text: 'Primo', bucket: 'Masculine (-o)' },
        { text: 'Nieto', bucket: 'Masculine (-o)' },
        { text: 'Hermana', bucket: 'Feminine (-a)' },
        { text: 'Abuela', bucket: 'Feminine (-a)' },
        { text: 'Tía', bucket: 'Feminine (-a)' },
        { text: 'Prima', bucket: 'Feminine (-a)' },
        { text: 'Nieta', bucket: 'Feminine (-a)' },
      ],
    },
    {
      title: 'Choose the Correct Possessive',
      instruction: 'Sort each phrase by possessive: singular (mi/tu/su) or plural (mis/tus/sus).',
      buckets: ['Singular (mi/tu/su)', 'Plural (mis/tus/sus)'],
      items: [
        { text: 'Mi hermano', bucket: 'Singular (mi/tu/su)' },
        { text: 'Tu mamá', bucket: 'Singular (mi/tu/su)' },
        { text: 'Su hijo', bucket: 'Singular (mi/tu/su)' },
        { text: 'Mi abuela', bucket: 'Singular (mi/tu/su)' },
        { text: 'Mis hermanos', bucket: 'Plural (mis/tus/sus)' },
        { text: 'Tus primas', bucket: 'Plural (mis/tus/sus)' },
        { text: 'Sus hijos', bucket: 'Plural (mis/tus/sus)' },
        { text: 'Mis abuelos', bucket: 'Plural (mis/tus/sus)' },
      ],
    },
  ],
  sortSectionId: 'family-sorting',
  sortTitle: 'Sort the Family',
  dialogues: [
    {
      id: 'dialogue-family-intro',
      title: 'Meeting the Family — Mexico City',
      location: 'Mexico City',
      lines: [
        { speaker: 'Ana', text: '¡Hola! Bienvenido a mi casa. Te presento a mi familia.', audio: '/audio/L1.6/dialogues/d1-line1.mp3',
          annotations: [{ phrase: '¡Hola!', fromLesson: 'L1.2', note: 'Hello!' }] },
        { speaker: 'David', text: '¡Mucho gusto! ¿Es tu mamá?', audio: '/audio/L1.6/dialogues/d1-line2.mp3',
          annotations: [{ phrase: 'Mucho gusto', fromLesson: 'L1.2', note: 'Nice to meet you' }] },
        { speaker: 'Ana', text: 'Sí, mi mamá se llama Carmen. Y este es mi papá, Roberto.', audio: '/audio/L1.6/dialogues/d1-line3.mp3' },
        { speaker: 'David', text: 'Mucho gusto, señora Carmen, señor Roberto.', audio: '/audio/L1.6/dialogues/d1-line4.mp3' },
        { speaker: 'Ana', text: 'Y mis hermanos: Luis tiene veinte años y Sofía tiene quince.', audio: '/audio/L1.6/dialogues/d1-line5.mp3',
          annotations: [{ phrase: 'tiene ___ años', fromLesson: 'L1.3', note: 'is ___ years old' }] },
        { speaker: 'David', text: '¡Qué familia tan bonita!', audio: '/audio/L1.6/dialogues/d1-line6.mp3' },
      ],
    },
    {
      id: 'dialogue-family-talk',
      title: 'Talking About Family — Bogotá',
      location: 'Bogotá',
      lines: [
        { speaker: 'Lucía', text: '¿Tienes hermanos?', audio: '/audio/L1.6/dialogues/d2-line1.mp3' },
        { speaker: 'Carlos', text: 'Sí, tengo tres hermanos. Dos hermanos y una hermana.', audio: '/audio/L1.6/dialogues/d2-line2.mp3',
          annotations: [{ phrase: 'tres, dos, una', fromLesson: 'L1.3', note: 'Numbers from L1.3' }] },
        { speaker: 'Lucía', text: '¡Tres! Tu familia es grande. ¿Viven juntos?', audio: '/audio/L1.6/dialogues/d2-line3.mp3' },
        { speaker: 'Carlos', text: 'Sí, vivimos con mis abuelos también. Somos ocho en la casa.', audio: '/audio/L1.6/dialogues/d2-line4.mp3' },
        { speaker: 'Lucía', text: '¡Ocho! En mi familia somos cuatro: mis papás, mi hermana y yo.', audio: '/audio/L1.6/dialogues/d2-line5.mp3' },
        { speaker: 'Carlos', text: '¿Cómo se llama tu hermana?', audio: '/audio/L1.6/dialogues/d2-line6.mp3',
          annotations: [{ phrase: '¿Cómo se llama?', fromLesson: 'L1.2', note: 'What is (her) name?' }] },
        { speaker: 'Lucía', text: 'Se llama Valentina. Tiene doce años.', audio: '/audio/L1.6/dialogues/d2-line7.mp3' },
      ],
    },
  ],
  dialogueDescription: 'Listen to real conversations where people introduce and talk about their families in Spanish-speaking countries.',
  culturalNotes: [
    {
      title: 'La Familia Extendida — More Than a Nuclear Family',
      content: 'In many Hispanic countries, grandparents, aunts, uncles, and cousins are part of daily life — not just holiday visitors. It\'s common for three generations to live in the same house or very close by. "Mi familia" often means 15-20+ people, not just parents and siblings.',
    },
    {
      title: 'Two Last Names — Apellido Paterno y Materno',
      content: 'In Spanish-speaking countries, people have two last names: father\'s first, then mother\'s. Gabriel García Márquez: García (father\'s) + Márquez (mother\'s). Women traditionally keep their names after marriage. This system honors both sides of the family.',
    },
    {
      title: 'Terms of Endearment',
      content: '"Mami" and "papi" are common even for adults talking to their parents. "Abue" for abuela/abuelo. "Tía/tío" can be used for close family friends (not real aunts/uncles). Children often call their parents\' friends "tía Laura" or "tío Miguel" as a sign of respect and closeness.',
    },
  ],
  culturalGradient: 'from-rose-50 to-pink-50',
  quiz: [
    { id: 1, type: 'mc', text: 'How do you say "my grandmother" in Spanish?', options: ['Mi abuela', 'Mi hermana', 'Mi tía', 'Mi prima'], answer: 0 },
    { id: 2, type: 'fill', text: 'Complete: "Mi mamá ___ llama María" (is named)', answer: 'se' },
    { id: 3, type: 'mc', text: '"El sobrino" means:', options: ['Cousin', 'Nephew', 'Grandson', 'Uncle'], answer: 1 },
    { id: 4, type: 'tf', text: '"Mi" changes to "mis" when the noun is plural.', answer: true },
    { id: 5, type: 'mc', text: 'You want to say "your (informal) brothers." You say:', options: ['Mi hermanos', 'Tu hermanos', 'Tus hermanos', 'Sus hermanos'], answer: 2 },
    { id: 6, type: 'fill', text: 'Complete: "Tengo ___ hermanos" (three)', answer: 'tres' },
    { id: 7, type: 'mc', text: 'Which is the correct feminine form of "primo"?', options: ['Prima', 'Primo', 'Primas', 'Primá'], answer: 0 },
    { id: 8, type: 'tf', text: '"Hijo" and "hija" both have a silent H.', answer: true },
    { id: 9, type: 'mc', text: 'Someone says "Vivimos con mis abuelos." This means:', options: ['We visit our grandparents', 'We live with my grandparents', 'Our grandparents live alone', 'My grandparents are visiting'], answer: 1 },
    { id: 10, type: 'fill', text: 'Complete: "¿Cómo se llama ___ hermana?" (your)', answer: 'tu' },
    { id: 11, type: 'mc', text: '"Su hija" can mean:', options: ['His daughter', 'Her daughter', 'Their daughter', 'All of the above'], answer: 3 },
    { id: 12, type: 'tf', text: 'In Hispanic culture, "tía" is only used for real aunts.', answer: false },
    { id: 13, type: 'mc', text: 'How do you say "My brother is older"?', options: ['Mi hermano es menor', 'Mi hermano es mayor', 'Mi hermano es grande', 'Mi hermano tiene más'], answer: 1 },
    { id: 14, type: 'fill', text: 'Complete: "Mi papá se llama Roberto y ___ mamá se llama Carmen" (my)', answer: 'mi' },
    { id: 15, type: 'mc', text: 'In Spanish-speaking countries, people typically have:', options: ['One last name', 'Two last names', 'Three last names', 'No last names'], answer: 1 },
  ],
  uniqueActivity: {
    id: 'PictureMatchL16',
    sectionId: 'picture-match',
    sectionColor: 'bg-rose-50/40',
    sectionBorder: 'border-rose-100',
  },
  sectionColors: {
    'prior-knowledge': { bg: 'bg-indigo-50/30', border: 'border-indigo-100' },
    objectives: { bg: 'bg-white', border: '' },
    'personalized-context': { bg: 'bg-violet-50/30', border: 'border-violet-100' },
    immediate: { bg: 'bg-rose-50/30', border: 'border-rose-100' },
    extended: { bg: 'bg-purple-50/30', border: 'border-purple-100' },
    describing: { bg: 'bg-amber-50/30', border: 'border-amber-100' },
    possessives: { bg: 'bg-teal-50/30', border: 'border-teal-100' },
    'pronunciation-tips': { bg: 'bg-yellow-50/30', border: 'border-yellow-100' },
    'pronunciation-practice': { bg: 'bg-blue-50/30', border: 'border-blue-200' },
    flashcards: { bg: 'bg-pink-50/30', border: 'border-pink-100' },
    'matching-game': { bg: 'bg-teal-50/30', border: 'border-teal-100' },
    'family-sorting': { bg: 'bg-blue-50/30', border: 'border-blue-100' },
    dialogues: { bg: 'bg-purple-50/30', border: 'border-purple-100' },
    cultural: { bg: 'bg-rose-50/30', border: 'border-rose-100' },
    'picture-match': { bg: 'bg-rose-50/40', border: 'border-rose-100' },
    'knowledge-check': { bg: 'bg-indigo-50/40', border: 'border-indigo-100' },
  },
}

export const L16PhraseByAudio = phraseByAudio

// Picture Match — Family descriptions to match with emoji family scenes
export const PICTURE_MATCH_FAMILIES = [
  {
    emoji: '👨‍👩‍👧‍👦',
    label: 'Familia A',
    description: 'Una mamá, un papá, una hija y un hijo',
    members: ['mamá', 'papá', 'hija', 'hijo'],
  },
  {
    emoji: '👩‍👧',
    label: 'Familia B',
    description: 'Una mamá y una hija',
    members: ['mamá', 'hija'],
  },
  {
    emoji: '👨‍👩‍👧‍👦👴👵',
    label: 'Familia C',
    description: 'Una mamá, un papá, dos hijos y los abuelos',
    members: ['mamá', 'papá', 'hijos', 'abuelo', 'abuela'],
  },
  {
    emoji: '👨‍👧‍👦',
    label: 'Familia D',
    description: 'Un papá, un hijo y una hija',
    members: ['papá', 'hijo', 'hija'],
  },
]

export const PICTURE_MATCH_ROUNDS = [
  { clue: 'Tengo dos hijos: un hijo y una hija. Mi esposa se llama María.', correct: 'Familia A' },
  { clue: 'Soy mamá. Tengo una hija. No tengo esposo.', correct: 'Familia B' },
  { clue: 'Vivimos con mis abuelos. Tengo un hermano.', correct: 'Familia C' },
  { clue: 'Mi papá tiene dos hijos. No tenemos mamá en casa.', correct: 'Familia D' },
  { clue: 'Somos seis en la casa: mamá, papá, mi hermano, yo, y los abuelos.', correct: 'Familia C' },
  { clue: 'Mi mamá y yo vivimos juntas. Soy hija única.', correct: 'Familia B' },
]
