import type { LessonData } from '@/lib/types/lesson'

const PHRASES = [
  // Restaurant Basics
  { spanish: 'El menú', english: 'The menu', pronunciation: 'ehl meh-NOO', category: 'restaurant', audio: 'el-menu' },
  { spanish: 'El mesero (el camarero)', english: 'The waiter', pronunciation: 'ehl meh-SEH-roh', category: 'restaurant', audio: 'el-mesero' },
  { spanish: 'Una mesa para dos', english: 'A table for two', pronunciation: 'OO-nah MEH-sah PAH-rah dohs', category: 'restaurant', audio: 'mesa-para-dos' },
  { spanish: 'Tengo una reservación', english: 'I have a reservation', pronunciation: 'TEHN-goh OO-nah reh-sehr-bah-see-OHN', category: 'restaurant', audio: 'tengo-reservacion' },
  { spanish: 'El plato del día', english: 'The daily special', pronunciation: 'ehl PLAH-toh dehl DEE-ah', category: 'restaurant', audio: 'plato-del-dia' },
  { spanish: '¿Qué recomienda?', english: 'What do you recommend?', pronunciation: 'keh reh-koh-mee-EHN-dah', category: 'restaurant', audio: 'que-recomienda' },
  { spanish: '¿Está incluida la propina?', english: 'Is the tip included?', pronunciation: 'ehs-TAH een-kloo-EE-dah lah proh-PEE-nah', category: 'restaurant', audio: 'incluida-propina' },
  // Main Dishes & Proteins
  { spanish: 'El pollo', english: 'Chicken', pronunciation: 'ehl POH-yoh', category: 'food', audio: 'el-pollo' },
  { spanish: 'La carne (de res)', english: 'Beef', pronunciation: 'lah KAR-neh deh rehs', category: 'food', audio: 'la-carne' },
  { spanish: 'El pescado', english: 'Fish', pronunciation: 'ehl pehs-KAH-doh', category: 'food', audio: 'el-pescado' },
  { spanish: 'El cerdo', english: 'Pork', pronunciation: 'ehl SEHR-doh', category: 'food', audio: 'el-cerdo' },
  { spanish: 'Los camarones', english: 'Shrimp', pronunciation: 'lohs kah-mah-ROH-nehs', category: 'food', audio: 'los-camarones' },
  { spanish: 'El arroz', english: 'Rice', pronunciation: 'ehl ah-ROHS', category: 'food', audio: 'el-arroz' },
  { spanish: 'Los frijoles', english: 'Beans', pronunciation: 'lohs free-HOH-lehs', category: 'food', audio: 'los-frijoles' },
  { spanish: 'Las papas (las patatas)', english: 'Potatoes', pronunciation: 'lahs PAH-pahs', category: 'food', audio: 'las-papas' },
  { spanish: 'La entrada', english: 'Appetizer', pronunciation: 'lah ehn-TRAH-dah', category: 'food', audio: 'la-entrada' },
  { spanish: 'El plato fuerte', english: 'Main course', pronunciation: 'ehl PLAH-toh FWEHR-teh', category: 'food', audio: 'el-plato-fuerte' },
  { spanish: 'El postre', english: 'Dessert', pronunciation: 'ehl POHS-treh', category: 'food', audio: 'el-postre' },
  // Describing Food
  { spanish: 'Picante', english: 'Spicy', pronunciation: 'pee-KAHN-teh', category: 'describing', audio: 'picante' },
  { spanish: 'Dulce', english: 'Sweet', pronunciation: 'DOOL-seh', category: 'describing', audio: 'dulce' },
  { spanish: 'Salado', english: 'Salty', pronunciation: 'sah-LAH-doh', category: 'describing', audio: 'salado' },
  { spanish: 'Caliente', english: 'Hot (temperature)', pronunciation: 'kah-lee-EHN-teh', category: 'describing', audio: 'caliente' },
  { spanish: 'Frío', english: 'Cold', pronunciation: 'FREE-oh', category: 'describing', audio: 'frio' },
  { spanish: 'Fresco', english: 'Fresh', pronunciation: 'FREHS-koh', category: 'describing', audio: 'fresco' },
  { spanish: 'Rico', english: 'Delicious (informal)', pronunciation: 'RREE-koh', category: 'describing', audio: 'rico' },
  { spanish: 'Asado', english: 'Grilled', pronunciation: 'ah-SAH-doh', category: 'describing', audio: 'asado' },
  // Dietary Needs & Ordering
  { spanish: 'Soy vegetariano', english: 'I am vegetarian', pronunciation: 'soy beh-heh-tah-ree-AH-noh', category: 'dietary', audio: 'soy-vegetariano' },
  { spanish: 'Soy alérgico al maní', english: 'I am allergic to peanuts', pronunciation: 'soy ah-LEHR-hee-koh ahl mah-NEE', category: 'dietary', audio: 'soy-alergico' },
  { spanish: 'Sin gluten', english: 'Gluten-free', pronunciation: 'seen GLOO-tehn', category: 'dietary', audio: 'sin-gluten' },
  { spanish: '¿Tiene opciones vegetarianas?', english: 'Do you have vegetarian options?', pronunciation: 'tee-EH-neh ohp-see-OH-nehs beh-heh-tah-ree-AH-nahs', category: 'dietary', audio: 'opciones-vegetarianas' },
  { spanish: 'Para empezar, quiero...', english: 'To start, I want...', pronunciation: 'PAH-rah ehm-peh-SAHR kee-EH-roh', category: 'dietary', audio: 'para-empezar' },
  { spanish: 'De plato fuerte, quiero...', english: 'For the main course, I want...', pronunciation: 'deh PLAH-toh FWEHR-teh kee-EH-roh', category: 'dietary', audio: 'de-plato-fuerte' },
]

const phraseByAudio: Record<string, (typeof PHRASES)[number]> = {}
PHRASES.forEach((p) => { phraseByAudio[p.audio] = p })

export const L17Data: LessonData = {
  id: 'L1.7',
  hero: {
    lessonId: 'L1.7',
    title: 'Food & Drinks',
    subtitle: 'Ordering at a restaurant like a local',
    description: 'Go beyond the café! Learn to navigate a full restaurant experience — read a menu, order appetizers and main courses, describe food, handle dietary needs, and enjoy the meal.',
    image: '/images/L1.7/L1.7.jpg',
    gradient: 'from-orange-800/65 via-amber-700/55 to-yellow-700/65',
    accentColor: 'orange-200',
  },
  priorKnowledge: [
    {
      fromLesson: 'L1.4',
      label: 'Café Basics',
      detail: '"Quiero un café," "La cuenta, por favor," "¿Cuánto es?" — you already know the basics. Now we level up!',
    },
    {
      fromLesson: 'L1.3',
      label: 'Numbers for Prices',
      detail: 'You know numbers 0-100 — essential for reading prices on the menu and paying the bill.',
    },
    {
      fromLesson: 'L1.2',
      label: 'Polite Expressions',
      detail: '"Por favor," "gracias," "disculpe" — politeness at a restaurant is key in every culture.',
    },
  ],
  sectionTransitions: [
    { afterSection: 'restaurant', text: 'You know how to get seated and navigate the restaurant. Now let\'s explore the food!' },
    { afterSection: 'food', text: 'You know the dishes! Let\'s learn to describe how food tastes.' },
    { afterSection: 'describing', text: 'Now you can describe food. Let\'s handle special dietary needs.' },
    { afterSection: 'dietary', text: 'You can order anything — even with allergies! Let\'s work on pronunciation.' },
    { afterSection: 'dialogues', text: 'You heard real restaurant conversations. Let\'s explore food culture!' },
    { afterSection: 'cultural', text: 'Time to build your own restaurant order!' },
    { afterSection: 'menu-builder', text: 'Final quiz — show what you learned!' },
  ],
  personalizedVocab: [
    { spanish: 'Una mesa para...', english: 'A table for...' },
    { spanish: '¿Qué recomienda?', english: 'What do you recommend?' },
    { spanish: 'Para empezar, quiero...', english: 'To start, I want...' },
    { spanish: 'De plato fuerte, quiero...', english: 'For the main course...' },
    { spanish: 'Soy vegetariano', english: 'I am vegetarian' },
    { spanish: '¡Está muy rico!', english: 'It is very delicious!' },
  ],
  pronunciationChallenges: [
    { spanish: 'Quiero el pollo asado con arroz', pronunciation: 'kee-EH-roh ehl POH-yoh ah-SAH-doh kohn ah-ROHS', english: 'I want the grilled chicken with rice', audio: 'el-pollo', tip: '"Quiero" from L1.4! "Pollo" = POH-yoh (LL = Y sound). Double R in "arroz" = trilled R.' },
    { spanish: '¿Tiene postre?', pronunciation: 'tee-EH-neh POHS-treh', english: 'Do you have dessert?', audio: 'sin-gluten', tip: '"¿Tiene?" from L1.4! Simple and practical — just add any noun after "¿Tiene...?"' },
    { spanish: 'El pescado está muy fresco', pronunciation: 'ehl pehs-KAH-doh ehs-TAH mooy FREHS-koh', english: 'The fish is very fresh', audio: 'el-pescado', tip: '"Está" for description of state (L1.5). "Fresco" — the FR blend is the same as English.' },
    { spanish: 'De postre, quiero flan', pronunciation: 'deh POHS-treh kee-EH-roh flahn', english: 'For dessert, I want flan', audio: 'el-postre', tip: '"De" = for/of. "Postre" stress on first syllable: POHS-treh.' },
    { spanish: 'Los camarones están picantes', pronunciation: 'lohs kah-mah-ROH-nehs ehs-TAHN pee-KAHN-tehs', english: 'The shrimp are spicy', audio: 'los-camarones', tip: '"Están" (plural of "está") because "camarones" is plural. Notice the -es ending!' },
    { spanish: '¿Qué recomienda?', pronunciation: 'keh reh-koh-mee-EHN-dah', english: 'What do you recommend?', audio: 'que-recomienda', tip: '"Recomienda" — stress on the -MIEN- syllable. The D sounds soft, almost like English "th."' },
  ],
  objectives: [
    { icon: '🍽️', title: 'Navigate a Restaurant', desc: 'Make reservations, get a table, read the menu, and order' },
    { icon: '🥩', title: 'Know the Food', desc: 'Learn proteins, sides, appetizers, main courses, and desserts' },
    { icon: '🌶️', title: 'Describe Food', desc: 'Say if food is spicy, sweet, salty, hot, cold, or delicious' },
    { icon: '🥗', title: 'Handle Dietary Needs', desc: 'Communicate allergies, vegetarian preferences, and restrictions' },
  ],
  sections: [
    { id: 'welcome', label: 'Welcome' },
    { id: 'prior-knowledge', label: 'What You Already Know' },
    { id: 'objectives', label: "What You'll Learn" },
    { id: 'personalized-context', label: 'See in YOUR Context' },
    { id: 'restaurant', label: 'At the Restaurant' },
    { id: 'food', label: 'Main Dishes & Proteins' },
    { id: 'describing', label: 'Describing Food' },
    { id: 'dietary', label: 'Dietary Needs & Ordering' },
    { id: 'pronunciation-tips', label: 'Pronunciation Tips' },
    { id: 'pronunciation-practice', label: 'Pronunciation Practice' },
    { id: 'flashcards', label: 'Flashcards' },
    { id: 'matching-game', label: 'Matching Game' },
    { id: 'food-sorting', label: 'Sort the Food' },
    { id: 'dialogues', label: 'Real-World Dialogues' },
    { id: 'cultural', label: 'Cultural Insights' },
    { id: 'menu-builder', label: 'Menu Builder' },
    { id: 'knowledge-check', label: 'Knowledge Check' },
  ],
  audioBase: '/audio/L1.7/phrases',
  phraseSections: [
    {
      id: 'restaurant',
      title: 'At the Restaurant',
      description: 'From making a reservation to asking for the daily special. These phrases get you settled and ready to order.',
      tabs: [
        { label: 'Getting Seated', color: 'orange', phrases: PHRASES.filter(p => p.category === 'restaurant') },
      ],
    },
    {
      id: 'food',
      title: 'Main Dishes & Proteins',
      description: 'The stars of any restaurant menu. Notice the articles: "el pollo" (masculine), "la carne" (feminine) — you learned this pattern in L1.5!',
      tabs: [
        { label: 'Proteins', color: 'rose', phrases: PHRASES.filter(p => ['el-pollo', 'la-carne', 'el-pescado', 'el-cerdo', 'los-camarones'].includes(p.audio)) },
        { label: 'Sides & Courses', color: 'amber', phrases: PHRASES.filter(p => ['el-arroz', 'los-frijoles', 'las-papas', 'la-entrada', 'el-plato-fuerte', 'el-postre'].includes(p.audio)), columns: 2 },
      ],
    },
    {
      id: 'describing',
      title: 'Describing Food',
      description: 'How does it taste? Is it hot or cold? Spicy or sweet? These adjectives help you describe (and order) exactly what you want.',
      tabs: [
        { label: 'Flavors & Textures', color: 'emerald', phrases: PHRASES.filter(p => p.category === 'describing'), columns: 2 },
      ],
    },
    {
      id: 'dietary',
      title: 'Dietary Needs & Ordering',
      description: 'Allergies, vegetarian options, and structuring a full order. Essential for eating safely and confidently abroad.',
      tabs: [
        { label: 'Dietary & Full Order', color: 'teal', phrases: PHRASES.filter(p => p.category === 'dietary'), columns: 2 },
      ],
    },
  ],
  pronunciationTips: [
    {
      title: '"Pollo" — LL = Y Sound',
      content: 'Remember from L1.1: LL makes a "Y" sound in most of Latin America. "Pollo" = POH-yoh (not "POH-loh"). Same pattern: "calle" = KAH-yeh, "llama" = YAH-mah. In Argentina, LL sounds more like "sh" — so "pollo" = "POH-shoh."',
      example: 'Pollo = POH-yoh | Calle = KAH-yeh | Paella = pah-EH-yah',
      reviewFrom: 'L1.1',
    },
    {
      title: 'Double R in "Arroz" — Trill It!',
      content: 'The RR (and R at the start of words) requires a tongue trill. "Arroz" = ah-RROHS with a strong trill. Practice by saying "butter" fast — the "tt" is close to a Spanish R. The trill takes practice but makes a huge difference!',
      example: 'Arroz = ah-RROHS | Rico = RREE-koh | Recomiendo = rreh-koh-mee-EHN-doh',
      reviewFrom: 'L1.1',
    },
    {
      title: '"Entrada" vs "Plato Fuerte" vs "Postre"',
      content: 'A full meal has three courses: "la entrada" (appetizer/starter), "el plato fuerte" (main course — literally "strong plate"), and "el postre" (dessert). In some countries, "entrada" means the main course (like English "entrée"), but in most of Latin America it means appetizer.',
      example: 'Entrada → Plato fuerte → Postre (Appetizer → Main → Dessert)',
    },
    {
      title: 'Building on "Quiero" from L1.4',
      content: 'You already know "Quiero un café." Now build full orders: "Para empezar, quiero la sopa." "De plato fuerte, quiero el pollo asado." "De postre, quiero flan." The structure is: context + quiero + article + dish.',
      example: 'Para empezar, quiero la sopa | De plato fuerte, quiero el pollo | De postre, quiero flan',
      reviewFrom: 'L1.4',
    },
  ],
  flashcardGroups: [
    { key: 'restaurant', label: 'Restaurant Basics', audioKeys: ['el-menu', 'el-mesero', 'mesa-para-dos', 'tengo-reservacion', 'plato-del-dia', 'que-recomienda', 'incluida-propina'] },
    { key: 'food', label: 'Dishes & Proteins', audioKeys: ['el-pollo', 'la-carne', 'el-pescado', 'el-cerdo', 'los-camarones', 'el-arroz', 'los-frijoles', 'las-papas', 'la-entrada', 'el-plato-fuerte', 'el-postre'] },
    { key: 'describing-dietary', label: 'Describing & Dietary', audioKeys: ['picante', 'dulce', 'salado', 'caliente', 'frio', 'fresco', 'rico', 'asado', 'soy-vegetariano', 'sin-gluten'] },
  ],
  matchPairs: [
    { left: 'El pollo', right: 'Chicken' },
    { left: 'La carne', right: 'Beef' },
    { left: 'El pescado', right: 'Fish' },
    { left: 'Picante', right: 'Spicy' },
    { left: 'Dulce', right: 'Sweet' },
    { left: 'La entrada', right: 'Appetizer' },
    { left: 'El plato fuerte', right: 'Main course' },
    { left: 'El postre', right: 'Dessert' },
  ],
  matchLabels: { left: 'Spanish', right: 'English' },
  sortActivities: [
    {
      title: 'Course Order',
      instruction: 'Sort each item into the correct course.',
      buckets: ['Entrada (Appetizer)', 'Plato Fuerte (Main)', 'Postre (Dessert)'],
      items: [
        { text: 'Sopa', bucket: 'Entrada (Appetizer)' },
        { text: 'Ensalada', bucket: 'Entrada (Appetizer)' },
        { text: 'Pollo asado', bucket: 'Plato Fuerte (Main)' },
        { text: 'Carne con arroz', bucket: 'Plato Fuerte (Main)' },
        { text: 'Pescado con papas', bucket: 'Plato Fuerte (Main)' },
        { text: 'Flan', bucket: 'Postre (Dessert)' },
        { text: 'Helado', bucket: 'Postre (Dessert)' },
        { text: 'Churros', bucket: 'Postre (Dessert)' },
      ],
    },
    {
      title: 'Flavor Profile',
      instruction: 'Sort each food by its typical flavor.',
      buckets: ['Dulce (Sweet)', 'Salado (Savory)', 'Picante (Spicy)'],
      items: [
        { text: 'Flan', bucket: 'Dulce (Sweet)' },
        { text: 'Helado', bucket: 'Dulce (Sweet)' },
        { text: 'Churros', bucket: 'Dulce (Sweet)' },
        { text: 'Arroz con pollo', bucket: 'Salado (Savory)' },
        { text: 'Pescado', bucket: 'Salado (Savory)' },
        { text: 'Camarones al ajillo', bucket: 'Salado (Savory)' },
        { text: 'Salsa habanero', bucket: 'Picante (Spicy)' },
        { text: 'Chile jalapeño', bucket: 'Picante (Spicy)' },
      ],
    },
    {
      title: 'True or False?',
      instruction: 'Sort each statement.',
      buckets: ['True', 'False'],
      items: [
        { text: '"El plato fuerte" is the main course', bucket: 'True' },
        { text: '"Picante" means spicy', bucket: 'True' },
        { text: '"Mesero" and "camarero" both mean waiter', bucket: 'True' },
        { text: '"Fresco" means fresh', bucket: 'True' },
        { text: '"La entrada" always means main course', bucket: 'False' },
        { text: '"Caliente" means spicy', bucket: 'False' },
        { text: '"Pollo" sounds like "POH-loh"', bucket: 'False' },
        { text: '"El postre" is the appetizer', bucket: 'False' },
      ],
    },
  ],
  sortSectionId: 'food-sorting',
  sortTitle: 'Sort the Food',
  dialogues: [
    {
      id: 'dialogue-restaurant-mx',
      title: 'Ordering at a Restaurant — Oaxaca, Mexico',
      location: 'Oaxaca',
      lines: [
        { speaker: 'Mesero', text: 'Buenas tardes. ¿Mesa para cuántos?', audio: '/audio/L1.7/dialogues/d1-line1.mp3',
          annotations: [{ phrase: 'Buenas tardes', fromLesson: 'L1.2', note: 'Good afternoon' }] },
        { speaker: 'Cliente', text: 'Para dos, por favor. Tengo una reservación a nombre de García.', audio: '/audio/L1.7/dialogues/d1-line2.mp3',
          annotations: [{ phrase: 'por favor', fromLesson: 'L1.2', note: 'Please' }] },
        { speaker: 'Mesero', text: 'Perfecto. Aquí tienen el menú. El plato del día es mole negro con pollo.', audio: '/audio/L1.7/dialogues/d1-line3.mp3' },
        { speaker: 'Cliente', text: '¿El mole es muy picante?', audio: '/audio/L1.7/dialogues/d1-line4.mp3' },
        { speaker: 'Mesero', text: 'Un poco picante, pero muy rico. ¿Tiene alguna alergia?', audio: '/audio/L1.7/dialogues/d1-line5.mp3' },
        { speaker: 'Cliente', text: 'No. Para empezar, quiero la sopa de tortilla. De plato fuerte, el mole negro.', audio: '/audio/L1.7/dialogues/d1-line6.mp3' },
        { speaker: 'Mesero', text: '¡Excelente elección! ¿Y de postre?', audio: '/audio/L1.7/dialogues/d1-line7.mp3' },
        { speaker: 'Cliente', text: 'De postre, flan, por favor.', audio: '/audio/L1.7/dialogues/d1-line8.mp3' },
      ],
    },
    {
      id: 'dialogue-restaurant-ar',
      title: 'At a Parrilla — Buenos Aires',
      location: 'Buenos Aires',
      lines: [
        { speaker: 'Mozo', text: 'Bienvenidos. ¿Qué van a pedir?', audio: '/audio/L1.7/dialogues/d2-line1.mp3' },
        { speaker: 'Turista', text: '¿Qué recomienda? Es mi primera vez aquí.', audio: '/audio/L1.7/dialogues/d2-line2.mp3' },
        { speaker: 'Mozo', text: 'El asado es espectacular. También las empanadas de carne.', audio: '/audio/L1.7/dialogues/d2-line3.mp3' },
        { speaker: 'Turista', text: 'Soy vegetariano. ¿Tiene opciones vegetarianas?', audio: '/audio/L1.7/dialogues/d2-line4.mp3' },
        { speaker: 'Mozo', text: 'Sí, tenemos una provoleta y ensalada caprese. También papas a la crema.', audio: '/audio/L1.7/dialogues/d2-line5.mp3' },
        { speaker: 'Turista', text: 'Perfecto. Quiero la provoleta y la ensalada, por favor.', audio: '/audio/L1.7/dialogues/d2-line6.mp3',
          annotations: [{ phrase: 'Quiero', fromLesson: 'L1.4', note: 'I want' }] },
        { speaker: 'Mozo', text: '¿Y para tomar?', audio: '/audio/L1.7/dialogues/d2-line7.mp3' },
        { speaker: 'Turista', text: 'Un agua mineral, por favor. ¿Está incluida la propina?', audio: '/audio/L1.7/dialogues/d2-line8.mp3',
          annotations: [{ phrase: 'por favor', fromLesson: 'L1.2', note: 'Please' }] },
        { speaker: 'Mozo', text: 'No, la propina no está incluida. Diez por ciento es lo común.', audio: '/audio/L1.7/dialogues/d2-line9.mp3' },
      ],
    },
  ],
  dialogueDescription: 'Listen to real restaurant conversations in Mexico and Argentina — two very different food cultures!',
  culturalNotes: [
    {
      title: 'Meal Times Are Different',
      content: 'Lunch ("la comida" or "el almuerzo") is the biggest meal of the day in most Hispanic countries, usually between 1-3 PM. Dinner ("la cena") is lighter and later — often 8-10 PM. In Spain, dinner can start at 10 PM! Don\'t expect restaurants to be busy at 6 PM.',
    },
    {
      title: 'Tipping Varies by Country',
      content: 'Mexico: 10-15% is standard. Argentina: 10% in cash is preferred. Spain: Tipping is not expected but rounding up is common. Colombia: A 10% "propina voluntaria" is usually added to the bill — you can decline it. Always ask "¿Está incluida la propina?" to avoid double-tipping.',
    },
    {
      title: 'The Magic of "Sobremesa"',
      content: 'You learned "sobremesa" in L1.4 — the tradition of lingering at the table after a meal to talk. In Hispanic culture, rushing to leave after eating is considered rude. The meal is a social event, not just food. Enjoy the conversation!',
    },
  ],
  culturalGradient: 'from-orange-50 to-amber-50',
  quiz: [
    { id: 1, type: 'mc', text: 'You want a table for two. You say:', options: ['Una mesa para uno', 'Una mesa para dos', 'Dos mesas, por favor', 'Quiero dos'], answer: 1 },
    { id: 2, type: 'fill', text: 'Complete: "¿Qué ___?" (do you recommend)', answer: 'recomienda' },
    { id: 3, type: 'mc', text: '"El plato fuerte" means:', options: ['The appetizer', 'The dessert', 'The main course', 'The strong plate'], answer: 2 },
    { id: 4, type: 'tf', text: '"Picante" means hot (temperature).', answer: false },
    { id: 5, type: 'mc', text: 'You are allergic to peanuts. You say:', options: ['Quiero maní', 'No tengo maní', 'Soy alérgico al maní', 'El maní está rico'], answer: 2 },
    { id: 6, type: 'fill', text: 'Complete: "Para empezar, ___ la sopa" (I want)', answer: 'quiero' },
    { id: 7, type: 'mc', text: 'Which word means "shrimp"?', options: ['Cerdo', 'Camarones', 'Camarero', 'Carne'], answer: 1 },
    { id: 8, type: 'tf', text: '"Caliente" and "picante" mean the same thing.', answer: false },
    { id: 9, type: 'mc', text: '"Asado" means:', options: ['Fried', 'Boiled', 'Grilled', 'Raw'], answer: 2 },
    { id: 10, type: 'fill', text: 'Complete: "Soy ___" (vegetarian)', answer: 'vegetariano' },
    { id: 11, type: 'mc', text: 'The correct meal order is:', options: ['Postre → Entrada → Plato fuerte', 'Entrada → Plato fuerte → Postre', 'Plato fuerte → Entrada → Postre', 'Entrada → Postre → Plato fuerte'], answer: 1 },
    { id: 12, type: 'tf', text: 'In most Hispanic countries, lunch is the biggest meal of the day.', answer: true },
    { id: 13, type: 'mc', text: '"El mesero" and "el camarero" both mean:', options: ['The chef', 'The waiter', 'The manager', 'The customer'], answer: 1 },
    { id: 14, type: 'fill', text: 'Complete: "¿Está incluida la ___?" (tip)', answer: 'propina' },
    { id: 15, type: 'mc', text: 'In Argentina, the waiter is often called:', options: ['Mesero', 'Camarero', 'Mozo', 'Garçon'], answer: 2 },
  ],
  uniqueActivity: {
    id: 'MenuBuilderL17',
    sectionId: 'menu-builder',
    sectionColor: 'bg-orange-50/40',
    sectionBorder: 'border-orange-100',
  },
  sectionColors: {
    'prior-knowledge': { bg: 'bg-indigo-50/30', border: 'border-indigo-100' },
    objectives: { bg: 'bg-white', border: '' },
    'personalized-context': { bg: 'bg-violet-50/30', border: 'border-violet-100' },
    restaurant: { bg: 'bg-orange-50/30', border: 'border-orange-100' },
    food: { bg: 'bg-rose-50/30', border: 'border-rose-100' },
    describing: { bg: 'bg-emerald-50/30', border: 'border-emerald-100' },
    dietary: { bg: 'bg-teal-50/30', border: 'border-teal-100' },
    'pronunciation-tips': { bg: 'bg-yellow-50/30', border: 'border-yellow-100' },
    'pronunciation-practice': { bg: 'bg-blue-50/30', border: 'border-blue-200' },
    flashcards: { bg: 'bg-amber-50/30', border: 'border-amber-100' },
    'matching-game': { bg: 'bg-teal-50/30', border: 'border-teal-100' },
    'food-sorting': { bg: 'bg-blue-50/30', border: 'border-blue-100' },
    dialogues: { bg: 'bg-purple-50/30', border: 'border-purple-100' },
    cultural: { bg: 'bg-orange-50/30', border: 'border-orange-100' },
    'menu-builder': { bg: 'bg-orange-50/40', border: 'border-orange-100' },
    'knowledge-check': { bg: 'bg-indigo-50/40', border: 'border-indigo-100' },
  },
}

export const L17PhraseByAudio = phraseByAudio

// Menu Builder — Build a complete restaurant order based on a scenario
export const MENU_ITEMS = {
  entradas: [
    { name: 'Sopa de tortilla', emoji: '🍲', tags: ['caliente', 'vegetariano'] },
    { name: 'Ensalada mixta', emoji: '🥗', tags: ['frío', 'vegetariano', 'sin gluten'] },
    { name: 'Empanadas de carne', emoji: '🥟', tags: ['caliente', 'carne'] },
    { name: 'Ceviche', emoji: '🐟', tags: ['frío', 'pescado', 'sin gluten'] },
  ],
  platosFuertes: [
    { name: 'Pollo asado con arroz', emoji: '🍗', tags: ['caliente', 'sin gluten'] },
    { name: 'Carne con papas', emoji: '🥩', tags: ['caliente', 'carne', 'sin gluten'] },
    { name: 'Pescado a la plancha', emoji: '🐟', tags: ['caliente', 'pescado', 'sin gluten'] },
    { name: 'Pasta con verduras', emoji: '🍝', tags: ['caliente', 'vegetariano'] },
  ],
  postres: [
    { name: 'Flan', emoji: '🍮', tags: ['dulce', 'sin gluten'] },
    { name: 'Helado de chocolate', emoji: '🍨', tags: ['dulce', 'frío', 'sin gluten'] },
    { name: 'Churros con chocolate', emoji: '🍩', tags: ['dulce', 'caliente'] },
    { name: 'Fruta fresca', emoji: '🍇', tags: ['dulce', 'frío', 'vegetariano', 'sin gluten'] },
  ],
}

export const MENU_BUILDER_ROUNDS = [
  { scenario: 'You want a hot appetizer, any main course, and a cold dessert.', requirements: { entrada: ['caliente'], postre: ['frío'] } },
  { scenario: 'You are vegetarian. Choose an appetizer and a main course.', requirements: { entrada: ['vegetariano'], platoFuerte: ['vegetariano'] } },
  { scenario: 'You need gluten-free options for all three courses.', requirements: { entrada: ['sin gluten'], platoFuerte: ['sin gluten'], postre: ['sin gluten'] } },
  { scenario: 'You love seafood! Pick a seafood appetizer and a fish main course.', requirements: { entrada: ['pescado'], platoFuerte: ['pescado'] } },
]
