import type { LessonData } from '@/lib/types/lesson'

const PHRASES = [
  // Morning Routine
  { spanish: 'Me despierto', english: 'I wake up', pronunciation: 'meh dehs-pee-EHR-toh', category: 'morning', audio: 'me-despierto' },
  { spanish: 'Me levanto', english: 'I get up', pronunciation: 'meh leh-BAHN-toh', category: 'morning', audio: 'me-levanto' },
  { spanish: 'Me ducho', english: 'I shower', pronunciation: 'meh DOO-choh', category: 'morning', audio: 'me-ducho' },
  { spanish: 'Me visto', english: 'I get dressed', pronunciation: 'meh BEES-toh', category: 'morning', audio: 'me-visto' },
  { spanish: 'Desayuno', english: 'I eat breakfast', pronunciation: 'deh-sah-YOO-noh', category: 'morning', audio: 'desayuno' },
  { spanish: 'Salgo de casa', english: 'I leave the house', pronunciation: 'SAHL-goh deh KAH-sah', category: 'morning', audio: 'salgo-de-casa' },
  // Daytime Activities
  { spanish: 'Trabajo', english: 'I work', pronunciation: 'trah-BAH-hoh', category: 'daytime', audio: 'trabajo' },
  { spanish: 'Estudio', english: 'I study', pronunciation: 'ehs-TOO-dee-oh', category: 'daytime', audio: 'estudio' },
  { spanish: 'Almuerzo', english: 'I eat lunch', pronunciation: 'ahl-MWEHR-soh', category: 'daytime', audio: 'almuerzo' },
  { spanish: 'Camino', english: 'I walk', pronunciation: 'kah-MEE-noh', category: 'daytime', audio: 'camino' },
  { spanish: 'Cocino', english: 'I cook', pronunciation: 'koh-SEE-noh', category: 'daytime', audio: 'cocino' },
  { spanish: 'Limpio la casa', english: 'I clean the house', pronunciation: 'LEEM-pee-oh lah KAH-sah', category: 'daytime', audio: 'limpio-la-casa' },
  { spanish: 'Hago ejercicio', english: 'I exercise', pronunciation: 'AH-goh eh-hehr-SEE-see-oh', category: 'daytime', audio: 'hago-ejercicio' },
  // Evening & Night
  { spanish: 'Ceno', english: 'I eat dinner', pronunciation: 'SEH-noh', category: 'evening', audio: 'ceno' },
  { spanish: 'Leo un libro', english: 'I read a book', pronunciation: 'LEH-oh oon LEE-broh', category: 'evening', audio: 'leo-un-libro' },
  { spanish: 'Veo televisión', english: 'I watch TV', pronunciation: 'BEH-oh teh-leh-bee-see-OHN', category: 'evening', audio: 'veo-television' },
  { spanish: 'Me acuesto', english: 'I go to bed', pronunciation: 'meh ah-KWEHS-toh', category: 'evening', audio: 'me-acuesto' },
  { spanish: 'Me duermo', english: 'I fall asleep', pronunciation: 'meh DWEHR-moh', category: 'evening', audio: 'me-duermo' },
  // Time Expressions
  { spanish: 'Por la mañana', english: 'In the morning', pronunciation: 'pohr lah mah-NYAH-nah', category: 'time', audio: 'por-la-manana' },
  { spanish: 'Por la tarde', english: 'In the afternoon', pronunciation: 'pohr lah TAR-deh', category: 'time', audio: 'por-la-tarde' },
  { spanish: 'Por la noche', english: 'At night', pronunciation: 'pohr lah NOH-cheh', category: 'time', audio: 'por-la-noche' },
  { spanish: 'Temprano', english: 'Early', pronunciation: 'tehm-PRAH-noh', category: 'time', audio: 'temprano' },
  { spanish: 'Tarde', english: 'Late', pronunciation: 'TAR-deh', category: 'time', audio: 'tarde' },
  { spanish: 'Todos los días', english: 'Every day', pronunciation: 'TOH-dohs lohs DEE-ahs', category: 'time', audio: 'todos-los-dias' },
  { spanish: 'Los fines de semana', english: 'On weekends', pronunciation: 'lohs FEE-nehs deh seh-MAH-nah', category: 'time', audio: 'fines-de-semana' },
  // Likes & Preferences
  { spanish: 'Me gusta...', english: 'I like...', pronunciation: 'meh GOOS-tah', category: 'likes', audio: 'me-gusta' },
  { spanish: 'No me gusta...', english: 'I don\'t like...', pronunciation: 'noh meh GOOS-tah', category: 'likes', audio: 'no-me-gusta' },
  { spanish: 'Me gusta cocinar', english: 'I like to cook', pronunciation: 'meh GOOS-tah koh-see-NAHR', category: 'likes', audio: 'me-gusta-cocinar' },
  { spanish: 'Me gusta leer', english: 'I like to read', pronunciation: 'meh GOOS-tah leh-EHR', category: 'likes', audio: 'me-gusta-leer' },
  { spanish: 'Prefiero...', english: 'I prefer...', pronunciation: 'preh-fee-EH-roh', category: 'likes', audio: 'prefiero' },
  { spanish: 'Normalmente', english: 'Normally, usually', pronunciation: 'nohr-mahl-MEHN-teh', category: 'likes', audio: 'normalmente' },
  { spanish: 'Siempre', english: 'Always', pronunciation: 'see-EHM-preh', category: 'likes', audio: 'siempre' },
  { spanish: 'A veces', english: 'Sometimes', pronunciation: 'ah BEH-sehs', category: 'likes', audio: 'a-veces' },
]

const phraseByAudio: Record<string, (typeof PHRASES)[number]> = {}
PHRASES.forEach((p) => { phraseByAudio[p.audio] = p })

export const L18Data: LessonData = {
  id: 'L1.8',
  hero: {
    lessonId: 'L1.8',
    title: 'Daily Routines',
    subtitle: 'A day in your life, in Spanish',
    description: 'Describe your daily routine from morning to night. Learn reflexive verbs, time expressions, and how to talk about what you like to do. This lesson connects everything you\'ve learned into real daily life.',
    image: '/images/L1.8/L1.8.jpg',
    gradient: 'from-cyan-800/65 via-teal-700/55 to-emerald-700/65',
    accentColor: 'cyan-200',
  },
  priorKnowledge: [
    {
      fromLesson: 'L1.3',
      label: 'Telling Time',
      detail: '"Son las siete," "a las ocho" — you need time to describe when you do things: "Me levanto a las siete."',
    },
    {
      fromLesson: 'L1.6',
      label: 'Possessives & Family',
      detail: '"Mi mamá cocina," "mis hermanos estudian" — describe what your family does every day.',
    },
    {
      fromLesson: 'L1.7',
      label: 'Food Vocabulary',
      detail: '"Desayuno café con pan," "almuerzo pollo con arroz" — meals are part of your daily routine!',
    },
  ],
  sectionTransitions: [
    { afterSection: 'morning', text: 'Your morning routine is set! Now let\'s see what you do during the day.' },
    { afterSection: 'daytime', text: 'Work, study, cook — you know the daytime activities. Now let\'s wind down.' },
    { afterSection: 'evening', text: 'From morning to night, you can describe your whole day! Let\'s add time expressions.' },
    { afterSection: 'time-likes', text: 'You can say when and what you like! Let\'s work on pronunciation.' },
    { afterSection: 'dialogues', text: 'You heard real daily routines. Let\'s explore how daily life differs across countries.' },
    { afterSection: 'cultural', text: 'Time to build your own daily schedule in Spanish!' },
    { afterSection: 'schedule-builder', text: 'Final quiz — show everything you\'ve learned in Level 1!' },
  ],
  personalizedVocab: [
    { spanish: 'Me despierto a las...', english: 'I wake up at...' },
    { spanish: 'Trabajo todos los días', english: 'I work every day' },
    { spanish: 'Me gusta...', english: 'I like...' },
    { spanish: 'Por la mañana, yo...', english: 'In the morning, I...' },
    { spanish: 'Los fines de semana...', english: 'On weekends...' },
    { spanish: 'Normalmente ceno a las...', english: 'I normally eat dinner at...' },
  ],
  pronunciationChallenges: [
    { spanish: 'Me levanto a las siete de la mañana', pronunciation: 'meh leh-BAHN-toh ah lahs see-EH-teh deh lah mah-NYAH-nah', english: 'I get up at seven in the morning', audio: 'me-levanto', tip: '"A las siete" from L1.3! "Mañana" — the Ñ sounds like "ny" (L1.1).' },
    { spanish: 'Me gusta cocinar por la noche', pronunciation: 'meh GOOS-tah koh-see-NAHR pohr lah NOH-cheh', english: 'I like to cook at night', audio: 'me-gusta-cocinar', tip: '"Me gusta" + infinitive (-AR, -ER, -IR). "Cocinar" ends in -AR — stress the last syllable.' },
    { spanish: 'Siempre desayuno a las ocho', pronunciation: 'see-EHM-preh deh-sah-YOO-noh ah lahs OH-choh', english: 'I always eat breakfast at eight', audio: 'desayuno', tip: '"Siempre" = always. "Desayuno" — stress on YOO. "A las ocho" from L1.3.' },
    { spanish: 'Hago ejercicio los sábados', pronunciation: 'AH-goh eh-hehr-SEE-see-oh lohs SAH-bah-dohs', english: 'I exercise on Saturdays', audio: 'hago-ejercicio', tip: '"Hago" = I do/make. H is silent (L1.1). "Ejercicio" has 5 syllables!' },
    { spanish: 'Me acuesto tarde los viernes', pronunciation: 'meh ah-KWEHS-toh TAR-deh lohs bee-EHR-nehs', english: 'I go to bed late on Fridays', audio: 'me-acuesto', tip: '"Viernes" from L1.3! V sounds like B in Spanish: bee-EHR-nehs.' },
    { spanish: 'Almuerzo a la una', pronunciation: 'ahl-MWEHR-soh ah lah OO-nah', english: 'I eat lunch at one', audio: 'almuerzo', tip: '"A la una" (not "a las" — 1:00 is singular). "Almuerzo" = ahl-MWEHR-soh.' },
  ],
  objectives: [
    { icon: '🌅', title: 'Describe Your Morning', desc: 'Wake up, shower, get dressed, eat breakfast — all in Spanish' },
    { icon: '💼', title: 'Talk About Your Day', desc: 'Work, study, cook, exercise, and other daily activities' },
    { icon: '🌙', title: 'Evening Routine', desc: 'Dinner, reading, TV, bedtime — wind down in Spanish' },
    { icon: '❤️', title: 'Express Preferences', desc: 'Use "me gusta" to say what you like and prefer to do' },
  ],
  sections: [
    { id: 'welcome', label: 'Welcome' },
    { id: 'prior-knowledge', label: 'What You Already Know' },
    { id: 'objectives', label: "What You'll Learn" },
    { id: 'personalized-context', label: 'See in YOUR Context' },
    { id: 'morning', label: 'Morning Routine' },
    { id: 'daytime', label: 'Daytime Activities' },
    { id: 'evening', label: 'Evening & Night' },
    { id: 'time-likes', label: 'Time & Preferences' },
    { id: 'pronunciation-tips', label: 'Pronunciation Tips' },
    { id: 'pronunciation-practice', label: 'Pronunciation Practice' },
    { id: 'flashcards', label: 'Flashcards' },
    { id: 'matching-game', label: 'Matching Game' },
    { id: 'routine-sorting', label: 'Sort the Routine' },
    { id: 'dialogues', label: 'Real-World Dialogues' },
    { id: 'cultural', label: 'Cultural Insights' },
    { id: 'schedule-builder', label: 'Schedule Builder' },
    { id: 'knowledge-check', label: 'Knowledge Check' },
  ],
  audioBase: '/audio/L1.8/phrases',
  phraseSections: [
    {
      id: 'morning',
      title: 'Morning Routine',
      description: 'Start your day in Spanish! Notice the "me" before some verbs — these are reflexive verbs (actions you do to yourself). "Me levanto" = I get (myself) up.',
      tabs: [
        { label: 'Getting Ready', color: 'amber', phrases: PHRASES.filter(p => p.category === 'morning'), columns: 2 },
      ],
    },
    {
      id: 'daytime',
      title: 'Daytime Activities',
      description: 'What you do during the day. These are regular -AR and -ER verbs in the "yo" (I) form. Notice the pattern: -o ending for "I" — trabajo, estudio, cocino.',
      tabs: [
        { label: 'Work & Activities', color: 'blue', phrases: PHRASES.filter(p => p.category === 'daytime'), columns: 2 },
      ],
    },
    {
      id: 'evening',
      title: 'Evening & Night',
      description: 'Winding down after a long day. More reflexive verbs: "me acuesto" (I go to bed), "me duermo" (I fall asleep).',
      tabs: [
        { label: 'Evening Activities', color: 'purple', phrases: PHRASES.filter(p => p.category === 'evening') },
      ],
    },
    {
      id: 'time-likes',
      title: 'Time Expressions & Preferences',
      description: '"Por la mañana," "todos los días," "a veces" — when do you do things? Plus "me gusta" to say what you enjoy!',
      tabs: [
        { label: 'When?', color: 'teal', phrases: PHRASES.filter(p => p.category === 'time'), columns: 2 },
        { label: 'Likes & Frequency', color: 'emerald', phrases: PHRASES.filter(p => p.category === 'likes'), columns: 2 },
      ],
    },
  ],
  pronunciationTips: [
    {
      title: 'Reflexive Verbs: "Me" Before the Verb',
      content: 'Some daily actions are reflexive — you do them TO yourself. "Levantarse" (to get up) becomes "me levanto" (I get up). The pattern: me despierto, me ducho, me visto, me acuesto. "Me" always goes BEFORE the verb in statements.',
      example: 'Me levanto (I get up) | Me ducho (I shower) | Me acuesto (I go to bed)',
    },
    {
      title: 'The "Yo" Form: Always Ends in -O',
      content: 'For "I" (yo), regular verbs always end in -O: trabajo, estudio, cocino, camino, ceno, leo. This is the easiest pattern in Spanish — just change the ending to -O! Exception: "soy" (I am) and "voy" (I go).',
      example: 'Trabaj-O | Estudi-O | Cocin-O | Camin-O | Cen-O | Le-O',
    },
    {
      title: '"Me Gusta" — A Different Structure',
      content: '"Me gusta" literally means "it pleases me." That\'s why you say "me gusta cocinar" (cooking pleases me), not "yo gusto cocinar." For plural things: "me gustan los libros" (books please me). The verb changes, not the "me."',
      example: 'Me gusta cocinar (I like to cook) | Me gustan los libros (I like books)',
    },
    {
      title: 'Time of Day: "Por la..." from L1.3',
      content: 'You learned "de la mañana" (AM) in L1.3 for clock time. Now use "por la mañana" for general time of day. "Por" = during/in. "De" = specific clock time. "Trabajo por la mañana" (I work in the morning) vs "Trabajo a las nueve de la mañana" (I work at 9 AM).',
      example: 'Por la mañana = in the morning (general) | A las 9 de la mañana = at 9 AM (specific)',
      reviewFrom: 'L1.3',
    },
  ],
  flashcardGroups: [
    { key: 'morning', label: 'Morning Routine', audioKeys: ['me-despierto', 'me-levanto', 'me-ducho', 'me-visto', 'desayuno', 'salgo-de-casa'] },
    { key: 'day-evening', label: 'Day & Evening', audioKeys: ['trabajo', 'estudio', 'almuerzo', 'cocino', 'hago-ejercicio', 'ceno', 'leo-un-libro', 'veo-television', 'me-acuesto', 'me-duermo'] },
    { key: 'time-likes', label: 'Time & Preferences', audioKeys: ['por-la-manana', 'por-la-tarde', 'por-la-noche', 'temprano', 'todos-los-dias', 'fines-de-semana', 'me-gusta', 'siempre', 'a-veces', 'normalmente'] },
  ],
  matchPairs: [
    { left: 'Me levanto', right: 'I get up' },
    { left: 'Me ducho', right: 'I shower' },
    { left: 'Desayuno', right: 'I eat breakfast' },
    { left: 'Almuerzo', right: 'I eat lunch' },
    { left: 'Me acuesto', right: 'I go to bed' },
    { left: 'Me gusta', right: 'I like' },
    { left: 'Siempre', right: 'Always' },
    { left: 'A veces', right: 'Sometimes' },
  ],
  matchLabels: { left: 'Spanish', right: 'English' },
  sortActivities: [
    {
      title: 'Time of Day',
      instruction: 'Sort each activity by when you typically do it.',
      buckets: ['Por la mañana', 'Por la tarde', 'Por la noche'],
      items: [
        { text: 'Me despierto', bucket: 'Por la mañana' },
        { text: 'Me ducho', bucket: 'Por la mañana' },
        { text: 'Desayuno', bucket: 'Por la mañana' },
        { text: 'Almuerzo', bucket: 'Por la tarde' },
        { text: 'Trabajo', bucket: 'Por la tarde' },
        { text: 'Hago ejercicio', bucket: 'Por la tarde' },
        { text: 'Ceno', bucket: 'Por la noche' },
        { text: 'Me acuesto', bucket: 'Por la noche' },
      ],
    },
    {
      title: 'Reflexive or Regular?',
      instruction: 'Sort: does the verb need "me" (reflexive) or not?',
      buckets: ['Reflexive (me...)', 'Regular (no me)'],
      items: [
        { text: 'Levanto → Me levanto', bucket: 'Reflexive (me...)' },
        { text: 'Ducho → Me ducho', bucket: 'Reflexive (me...)' },
        { text: 'Visto → Me visto', bucket: 'Reflexive (me...)' },
        { text: 'Acuesto → Me acuesto', bucket: 'Reflexive (me...)' },
        { text: 'Trabajo', bucket: 'Regular (no me)' },
        { text: 'Estudio', bucket: 'Regular (no me)' },
        { text: 'Cocino', bucket: 'Regular (no me)' },
        { text: 'Camino', bucket: 'Regular (no me)' },
      ],
    },
    {
      title: 'Frequency: Always, Sometimes, or Never?',
      instruction: 'Sort each phrase by frequency.',
      buckets: ['Siempre (Always)', 'A veces (Sometimes)', 'Nunca (Never)'],
      items: [
        { text: 'Me despierto', bucket: 'Siempre (Always)' },
        { text: 'Desayuno', bucket: 'Siempre (Always)' },
        { text: 'Me acuesto', bucket: 'Siempre (Always)' },
        { text: 'Hago ejercicio', bucket: 'A veces (Sometimes)' },
        { text: 'Cocino', bucket: 'A veces (Sometimes)' },
        { text: 'Leo un libro', bucket: 'A veces (Sometimes)' },
        { text: 'Vuelo a la luna', bucket: 'Nunca (Never)' },
        { text: 'Hablo con dinosaurios', bucket: 'Nunca (Never)' },
      ],
    },
  ],
  sortSectionId: 'routine-sorting',
  sortTitle: 'Sort the Routine',
  dialogues: [
    {
      id: 'dialogue-routine-mx',
      title: 'A Typical Day — Guadalajara, Mexico',
      location: 'Guadalajara',
      lines: [
        { speaker: 'Profesor', text: 'Hoy vamos a hablar de nuestra rutina diaria. María, ¿a qué hora te levantas?', audio: '/audio/L1.8/dialogues/d1-line1.mp3' },
        { speaker: 'María', text: 'Me levanto a las seis y media. Me ducho, me visto y desayuno.', audio: '/audio/L1.8/dialogues/d1-line2.mp3',
          annotations: [{ phrase: 'seis y media', fromLesson: 'L1.3', note: 'Six thirty' }] },
        { speaker: 'Profesor', text: '¿Y qué desayunas?', audio: '/audio/L1.8/dialogues/d1-line3.mp3' },
        { speaker: 'María', text: 'Normalmente desayuno café con pan y fruta.', audio: '/audio/L1.8/dialogues/d1-line4.mp3',
          annotations: [{ phrase: 'café, pan, fruta', fromLesson: 'L1.4', note: 'Food from L1.4' }] },
        { speaker: 'Profesor', text: '¿Qué haces por la tarde?', audio: '/audio/L1.8/dialogues/d1-line5.mp3' },
        { speaker: 'María', text: 'Trabajo hasta las cinco. Después hago ejercicio y cocino. Me acuesto a las diez.', audio: '/audio/L1.8/dialogues/d1-line6.mp3',
          annotations: [{ phrase: 'cinco, diez', fromLesson: 'L1.3', note: 'Numbers from L1.3' }] },
      ],
    },
    {
      id: 'dialogue-weekend-co',
      title: 'Weekend Plans — Medellín, Colombia',
      location: 'Medellín',
      lines: [
        { speaker: 'Andrés', text: '¿Qué haces los fines de semana?', audio: '/audio/L1.8/dialogues/d2-line1.mp3' },
        { speaker: 'Camila', text: 'Los sábados me levanto tarde. No trabajo los fines de semana.', audio: '/audio/L1.8/dialogues/d2-line2.mp3',
          annotations: [{ phrase: 'sábados', fromLesson: 'L1.3', note: 'Saturdays (days of the week)' }] },
        { speaker: 'Andrés', text: '¿Te gusta cocinar?', audio: '/audio/L1.8/dialogues/d2-line3.mp3' },
        { speaker: 'Camila', text: '¡Sí! Me gusta mucho cocinar. Los domingos cocino para mi familia.', audio: '/audio/L1.8/dialogues/d2-line4.mp3',
          annotations: [{ phrase: 'mi familia', fromLesson: 'L1.6', note: 'My family (L1.6)' }] },
        { speaker: 'Andrés', text: 'A mí me gusta leer. Leo por la noche, siempre.', audio: '/audio/L1.8/dialogues/d2-line5.mp3' },
        { speaker: 'Camila', text: '¿Y haces ejercicio?', audio: '/audio/L1.8/dialogues/d2-line6.mp3' },
        { speaker: 'Andrés', text: 'A veces. Camino por el parque los domingos por la mañana.', audio: '/audio/L1.8/dialogues/d2-line7.mp3' },
      ],
    },
  ],
  dialogueDescription: 'Listen to people describe their daily routines and weekend habits in Mexico and Colombia.',
  culturalNotes: [
    {
      title: 'The Siesta — More Than a Nap',
      content: 'In Spain and parts of Latin America, "la siesta" (a midday rest) is a tradition. Many shops close between 2-5 PM. While less common in cities today, the culture of a long lunch break and slower afternoons remains. Don\'t expect everything to be open at 3 PM!',
    },
    {
      title: 'Meal Times Vary by Country',
      content: 'Mexico: breakfast 8-9 AM, lunch ("comida") 2-3 PM, dinner 8-9 PM. Spain: breakfast 8-9 AM, lunch 2-3 PM, dinner 9-10 PM. Colombia: breakfast 7-8 AM, lunch 12-1 PM, dinner 7-8 PM. The biggest meal is almost always lunch, not dinner.',
    },
    {
      title: '"Madrugador" vs "Noctámbulo"',
      content: 'Spanish has fun words for morning and night people: "madrugador" (early riser, from "madrugar" = to wake up very early) and "noctámbulo" or "trasnochador" (night owl). In Latin America, social events often start late — a party at 9 PM might not get going until 11 PM!',
    },
  ],
  culturalGradient: 'from-cyan-50 to-teal-50',
  quiz: [
    { id: 1, type: 'mc', text: '"Me levanto" means:', options: ['I lift something', 'I get up', 'I get dressed', 'I go to bed'], answer: 1 },
    { id: 2, type: 'fill', text: 'Complete: "___ despierto a las siete" (I wake up)', answer: 'Me' },
    { id: 3, type: 'mc', text: 'Which is a reflexive verb?', options: ['Trabajo', 'Cocino', 'Me ducho', 'Estudio'], answer: 2 },
    { id: 4, type: 'tf', text: '"Me gusta cocinar" literally means "Cooking pleases me."', answer: true },
    { id: 5, type: 'mc', text: '"Por la mañana" means:', options: ['In the morning', 'At morning time', 'Before morning', 'Until morning'], answer: 0 },
    { id: 6, type: 'fill', text: 'Complete: "Me gusta ___ un libro" (to read)', answer: 'leer' },
    { id: 7, type: 'mc', text: 'What is the "yo" form of "cocinar"?', options: ['Cocinas', 'Cocina', 'Cocino', 'Cocinamos'], answer: 2 },
    { id: 8, type: 'tf', text: '"Siempre" means "sometimes."', answer: false },
    { id: 9, type: 'mc', text: 'You eat lunch. You say:', options: ['Desayuno', 'Almuerzo', 'Ceno', 'Como'], answer: 1 },
    { id: 10, type: 'fill', text: 'Complete: "Los fines de ___" (weekends)', answer: 'semana' },
    { id: 11, type: 'mc', text: '"A veces hago ejercicio" means:', options: ['I always exercise', 'I sometimes exercise', 'I never exercise', 'I like to exercise'], answer: 1 },
    { id: 12, type: 'tf', text: 'In Spain, dinner is typically eaten at 6 PM.', answer: false },
    { id: 13, type: 'mc', text: 'The opposite of "temprano" (early) is:', options: ['Rápido', 'Tarde', 'Noche', 'Después'], answer: 1 },
    { id: 14, type: 'fill', text: 'Complete: "Me ___ a las diez de la noche" (I go to bed)', answer: 'acuesto' },
    { id: 15, type: 'mc', text: 'Which is the correct order of a typical day?', options: ['Ceno → Desayuno → Almuerzo', 'Desayuno → Almuerzo → Ceno', 'Almuerzo → Desayuno → Ceno', 'Desayuno → Ceno → Almuerzo'], answer: 1 },
  ],
  uniqueActivity: {
    id: 'ScheduleBuilderL18',
    sectionId: 'schedule-builder',
    sectionColor: 'bg-cyan-50/40',
    sectionBorder: 'border-cyan-100',
  },
  sectionColors: {
    'prior-knowledge': { bg: 'bg-indigo-50/30', border: 'border-indigo-100' },
    objectives: { bg: 'bg-white', border: '' },
    'personalized-context': { bg: 'bg-violet-50/30', border: 'border-violet-100' },
    morning: { bg: 'bg-amber-50/30', border: 'border-amber-100' },
    daytime: { bg: 'bg-blue-50/30', border: 'border-blue-100' },
    evening: { bg: 'bg-purple-50/30', border: 'border-purple-100' },
    'time-likes': { bg: 'bg-teal-50/30', border: 'border-teal-100' },
    'pronunciation-tips': { bg: 'bg-yellow-50/30', border: 'border-yellow-100' },
    'pronunciation-practice': { bg: 'bg-blue-50/30', border: 'border-blue-200' },
    flashcards: { bg: 'bg-cyan-50/30', border: 'border-cyan-100' },
    'matching-game': { bg: 'bg-teal-50/30', border: 'border-teal-100' },
    'routine-sorting': { bg: 'bg-blue-50/30', border: 'border-blue-100' },
    dialogues: { bg: 'bg-purple-50/30', border: 'border-purple-100' },
    cultural: { bg: 'bg-cyan-50/30', border: 'border-cyan-100' },
    'schedule-builder': { bg: 'bg-cyan-50/40', border: 'border-cyan-100' },
    'knowledge-check': { bg: 'bg-indigo-50/40', border: 'border-indigo-100' },
  },
}

export const L18PhraseByAudio = phraseByAudio

// Schedule Builder — drag activities into time slots
export const SCHEDULE_ACTIVITIES = [
  { emoji: '🛏️', label: 'Me levanto', time: 'morning' },
  { emoji: '🚿', label: 'Me ducho', time: 'morning' },
  { emoji: '🥐', label: 'Desayuno', time: 'morning' },
  { emoji: '💼', label: 'Trabajo', time: 'afternoon' },
  { emoji: '🍽️', label: 'Almuerzo', time: 'afternoon' },
  { emoji: '🏃', label: 'Hago ejercicio', time: 'afternoon' },
  { emoji: '🍲', label: 'Ceno', time: 'night' },
  { emoji: '📖', label: 'Leo un libro', time: 'night' },
  { emoji: '😴', label: 'Me acuesto', time: 'night' },
]

export const SCHEDULE_ROUNDS = [
  { clue: 'Me levanto temprano. Desayuno café. Trabajo por la mañana. Almuerzo a la una. Por la noche, ceno y me acuesto.', slots: ['Me levanto', 'Desayuno', 'Trabajo', 'Almuerzo', 'Ceno', 'Me acuesto'] },
  { clue: 'Me ducho por la mañana. Estudio por la tarde. Hago ejercicio después. Leo un libro por la noche.', slots: ['Me ducho', 'Estudio', 'Hago ejercicio', 'Leo un libro'] },
  { clue: 'Me levanto, me ducho, desayuno. Después trabajo todo el día. Ceno tarde y me acuesto a las once.', slots: ['Me levanto', 'Me ducho', 'Desayuno', 'Trabajo', 'Ceno', 'Me acuesto'] },
]
